- Src/IronPython/Runtime/ByteArray.cs
Fixed the bug, that if iterating over a bytearray, a System.Byte instead of an integer was returned. Issue: https://github.com/IronLanguages/main/issues/1237 (ip2)
> Fix byte-array iterator result

- Src/IronPython/Runtime/PythonOptions.cs
Set true division as the default option: `type(1/2)` will return `<type float>`.
> Set true division as default

- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Runtime/Enumerate.cs
- Src/IronPython/Runtime/Types/PythonTypeInfo.cs
Iterable must now implement `__next__` instead of `next`. Builtin `next` now calls `__next__`.
Works pretty well:
```python
>>> class Test04:
...     def __init__(self):
...         self.l = iter([1, 2, 3, 4])
...     def __iter__(self):
...         return self
...     def __next__(self):
...         return next(self.l)
...
>>> for a in Test04():
...     print (a)
```
Old style does not work anymore:
```python
>>> class Test05:
...     def __init__(self):
...         self.l = iter([1, 2, 3, 4])
...     def __iter__(self):
...         return self
...     def next(self):
...         return next(self.l)
...
>>> for b in Test05():
...     print (b)
...
TypeError: instance has no next() method
```
> PEP 3114 -- Renaming iterator.next() to iterator.__next__()

- appveyor.yml
- make.cmd
* Drop .NET 3.5 from make.cmd
Signed-off-by: Tim Orling <timothy.t.orling@linux.intel.com>
> Use nunit3 syntax for all test-* targets

- .travis.yml
- Makefile
- make.cmd
Since NUnit 3.4, the ```--labels=All``` flag outputs the name of
each test case as it is run.
Signed-off-by: Tim Orling <timothy.t.orling@linux.intel.com>
> make.cmd: output labels as tests run

- Src/IronPython/Modules/Builtin.cs
Re-adds callable which was removed in #118. The function was added back in Python 3.2.
> Re-add callable

- Src/IronPython.Modules/_random.cs
- WhatsNewInPython30.md
This removes the jumpahead per What's New in Python3 and updates the _random module to use the fixes from IronPython2.
> random module updates

- Src/IronPython/Runtime/Operations/LongOps.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- WhatsNewInPython30.md
This removes the L suffix for repr of long.
> Remove L suffix from repr of long

- WhatsNewInPython30.md
- WhatsNewInPython31.md
- WhatsNewInPython32.md
I haven't checked if any of it was done. I imagine some of the standard library changes are already "done" if the module is pure Python...
> Add What's New In Python 3.1 and 3.2

- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Modules/_ast.cs
Basically this reads the metaclass keyword and then injects `__metaclass__` into the class body.
Thought this would unblock some tests but it looks like we just end up running into other stuff (e.g. PEP3135).
> Temporarily get metaclasses working with old infrastructure

- Src/IronPython/Compiler/Ast/AssignmentStatement.cs
- Src/IronPython/Compiler/Ast/AstMethods.cs
- Src/IronPython/Compiler/Ast/PythonWalker.Generated.cs
- Src/IronPython/Compiler/Ast/SequenceExpression.cs
- Src/IronPython/Compiler/Ast/StarredExpression.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/IronPython.csproj
- Src/IronPython/Modules/_ast.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
Partial implementation of PEP 3132. This is for the assignment unpacking part of it (e.g. `a, *b = [1,2,3,4]`). There are more implicit unpacking cases that are not handled by this PR (e.g. `for a, *b in [(1, 2, 3), (4, 5, 6, 7)]: print(b)`).
> Assignment unpacking from PEP 3132

- Src/StdLib/Lib/inspect.py
This should be reverted once keyword only arguments are properly implemented.
> Temporarily avoid use of keyword only argument until properly implemented

- Src/IronPythonTest/Cases/CaseExecuter.cs
Also, as a side effect of turning off debug mode, the tests run in a fraction of the time (e.g. 18 seconds on my machine!)
> Turn off debug mode when running tests

- Src/IronPython/Compiler/Ast/ReturnStatement.cs
- Src/IronPython/Compiler/GeneratorRewriter.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Runtime/Exceptions/PythonExceptions.Generated.cs
- Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
- Src/IronPython/Runtime/Exceptions/StopIterationException.Generated.cs
- Src/IronPython/Runtime/Generator.cs
- Src/Scripts/generate_exceptions.py
Prep work for PEP380. Returning a value from a generator will result in a StopIteration exception with the returned value.
> Support return with value from generators

- Src/IronPython.Modules/math.cs
The CPython `test_math` expects an `OverflowError` for large factorial values.
> Add limit to factorial

- Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
Woke up in the middle of the night and this case popped into my head:
```Python
try:
raise Exception()
except Exception as e:
e.with_traceback(None)
assert e.__traceback__ is None
```
Not sure if I like the fix though...
> Fix issue with with_traceback

- Src/IronPython.Modules/nt.cs
- Src/IronPython/Modules/_fileio.cs
- Src/IronPython/Modules/_io.cs
- Src/IronPython/Runtime/OutputWriter.cs
- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPython/Runtime/PythonFile.cs
Replaces `sys.stdout`, `sys.stdin` and `sys.stderr` to use `TextIOWrapper`.
> Replace PythonFile with FileIO for standard streams

- Src/IronPython/Modules/_io.cs
Fixes the following which leads to a `StackOverflowException`
```Python
import io
class Test(io.IOBase):
pass
dir(Test())
```
> Fix issue when using dir on an instance of subclass of IOBase

- Src/IronPython.Modules/_codecs.cs
- Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
In Python 3, mbcs encode/decode no longer ignores the errors parameter. This is currently causing a lot of tests to fail.
> Enable errors on mbcs encode/decode

- Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
- Src/IronPython/Runtime/Types/PythonType.cs
Types are gone, everything is now a class. Also the exceptions module is gone (exceptions are part of the builtin module).
> Change type to class and remove exceptions module

- Src/StdLib/Lib/test/test_syntax.py
Prevents an infinite loop if the test doesn't fail as expected. Might be worth making a PR to CPython for this one.
> Fix blocking test in test_syntax

- Src/IronPython/Compiler/Ast/SequenceExpression.cs
The following two statements should raise `SyntaxError`:
```Python
["a"] = [1]
[a + 1] = [1]
```
They currently raise a `SystemError` (or an assertion failure in Debug mode).
> Fix bug with assigning to a sequence

- Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
An incorrect argument was being added to exceptions raised without a value.
```Python
try:
raise Exception
except Exception as e:
assert len(e.args) == 0
```
> Prevent incorrect argument from being added to exceptions

- Src/StdLib/Lib/test/test_unpack.py
Updates the error message in `test_unpack` to match the CPython 3.5 exception message (which is what we output).
> Get test_unpack working

- Src/IronPython/Runtime/Types/PythonTypeDictSlot.cs
- Src/IronPython/Runtime/Types/PythonTypeWeakRefSlot.cs
Adds `__set__` to `getset_descriptor` types to resolve the following issues:
```Python
import inspect
class test(object): pass
assert not inspect.ismethoddescriptor(test.__weakref__)
assert not inspect.ismethoddescriptor(test.__dict__["__dict__"])
```
> Add __set__ to getset_descriptor types

- Src/StdLib/Lib/test/test_sort.py
Disables two tests which rely on reference counting in order to work properly.
> Disable some tests in test_sort

- Src/IronPython/Runtime/Operations/InstanceOps.cs
- Src/IronPython/Runtime/Types/PythonTypeInfo.cs
Fixes the following:
```
list(iter("123"))
list(iter(b"123"))
```
which were returning key/value pairs.
Note that the same code appears in the ipy2.7 branch however it does not appear to get called...
> Fix iter of str and bytes

- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
Would fail the following:
```Python
a, *b = [1]
```
Also removes a test from the ignore list (it was raising an assertion error due to this bug).
> Fix bug with argument unpacking

- Src/IronPythonTest/Cases/CaseExecuter.cs
This seems to do the trick (and doesn't appear to break any other test).
> Get test_math passing under test suite

- Src/IronPython/Modules/_fileio.cs
This aligns the file sharing mode for opening files with what C Python does.
> Align with C Python sharing mode for files

- Src/IronPython/Modules/_fileio.cs
The underlying file should not get closed if closefd is False. There are some corner cases that I am missing for sure, so please review.
> Fix the issue where the underlying file gets closed when it shouldn't

- Src/IronPython.Modules/_winapi.cs
- Src/IronPython.Modules/msvcrt.cs
- Src/IronPython.Modules/winsound.cs
- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPython/Runtime/PythonModuleAttribute.cs
This is somewhat different than the implementation for IPy2.
This allows passing a list (params PlatformID[]) of supported platforms,
or an enum value for a predefined list of supported platforms.
> Add ability to mark supported platforms for a PythonModule.

- Src/IronPython/Runtime/Descriptors.cs
- Src/IronPython/Runtime/Types/PythonType.cs
Add \_\_init__ methods to avoid object.\_\_init__ deprecation warnings. Add \_\_isabstractmethod__ implementations.
> Fix several tests in test_abc.py

- Src/IronPython/Compiler/Ast/ScopeStatement.cs
Prevents test_scope from failing with a syntax error.
> Don't raise syntax error when deleting variable references in nested scope

- Src/IronPython/Compiler/Parser.cs
The IPy code looks at _statements[0].Documentation to get the documentation for a class. If the metaclass is present in the class definition, it becomes the the first statement and it's Documentation is null. This fixes this issue by making the metaclass assignment at a minimum the second statement in the class's suite.
> Fix issue with metaclass assignment corrupting __doc__

- Src/IronPython/Modules/array.cs
Covers: IronLanguages/main@12765e7, IronLanguages/main#1472 and IronLanguages/main#1527.
Also removes read/write which are gone in Python 3.
> Update array with 2.7 fixes

- Src/IronPython/Modules/Builtin.cs
Fixes `make` failing, as `sort()` had the same argument removed but this didn't.
> Removed cmp argument from sorted()

- README.md
Hi,
I don't know how critical this is, but I ran into it twice, so I thought I'd updated the `README` to explicitly mention cloning this repository recursively. (Without this, you run `make` and wonder why the DLR project files are missing.)
> README: clarify cloning with submodules

- .editorconfig
- Build/Common.proj
- Src/IronPython.Modules/_collections.cs
- Src/IronPython/Runtime/DictionaryOps.cs
- Src/IronPython/Runtime/Operations/ObjectOps.cs
- Src/IronPython/Runtime/PythonDictionary.cs
- Src/IronPython/Runtime/Types/MappingProxy.cs
- Src/IronPythonConsoleAny/IronPythonConsoleAny.csproj
- WhatsNewInPython30.md
Changes dictionary `keys`, `values` and `items` methods to return views instead of lists. Also eliminated the `iterkeys`, `itervalues` and `iteritems` methods.
This is a somewhat experimental PR in that it also makes `PythonDictionary.cs` IPY2/IPY3 compatible using preprocessor directived (meaning that the exact same file should work in both code bases).
Edit: `test_dictviews` should be passing all tests except for pickling related stuff.
> Dictionary views

- Src/IronPython.Modules/_collections.cs
- Src/IronPython.Modules/_operator.cs
- Src/IronPython/Runtime/Binding/PythonProtocol.Operations.cs
- Src/IronPython/Runtime/List.cs
- Src/IronPython/Runtime/Method.cs
- Src/IronPython/Runtime/Operations/InstanceOps.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/PythonDictionary.cs
- Src/IronPython/Runtime/PythonTuple.cs
- Src/IronPython/Runtime/SetStorage.cs
- Src/IronPython/Runtime/Types/PythonTypeInfo.cs
- Tests/test_in.py
- Adds extra tests to cover more cases than what's in `test_contains`.
- Fixes a bug with https://github.com/IronLanguages/ironpython3/pull/347
- Applies the patch from: https://github.com/IronLanguages/ironpython2/pull/240
- Fixes what appeared to be an unreachable code path in `PythonTypeInfo`.
This PR also applies to IPY2.
> Fix test_contains

- Src/IronPython.Modules/IterTools.cs
itertools.ifilterfalse and zip_longest had their "i" prefixes removed, and itertools.ifilter, imap, and izip were replaced by builtins.
Resolves #267.
> Update itertools method names

- Src/IronPython.Modules/_collections.cs
- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/List.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/PythonTuple.cs
- Src/IronPython/Runtime/Range.cs
- Src/IronPython/Runtime/Set.cs
- Src/StdLib/Lib/test/test_iterlen.py
- Tests/test_iteratorlength.py
Add `__length_hint__` to built in types as described in #6.
This also disables a test which was crashing the test runner; I don't think this crash is related to the changes.
> Add `__length_hint__` support for built in types

- Src/IronPython/Modules/_io.cs
Prevents `input` from blocking. Might consider porting this over to ipy2 as well.
> Use read1 instead of read

- Src/IronPython.Modules/cmath.cs
- Src/IronPython/Modules/array.cs
- Src/IronPython/Runtime/List.cs
These methods/constants were added prior to Python 3.4.
> Implement List.copy, cmath.isfinite, array.typecodes

- Src/IronPython/Lib/iptest/type_util.py
- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Modules/_io.cs
- Src/IronPython/Modules/sys.cs
- Src/IronPython/Runtime/Operations/DecimalOps.cs
- Src/IronPython/Runtime/Operations/FloatOps.cs
- Src/IronPython/Runtime/Operations/IntOps.Generated.cs
- Src/IronPython/Runtime/Operations/LongOps.cs
- Src/Scripts/generate_alltypes.py
- Src/StdLib/Lib/test/test_hash.py
- Tests/test_numberhash.py
The hashing is made to match the 32-bit implementation of CPython so we can keep using `int` as the return type.
Issues:
- Hashing of complex number doesn't match CPython (for non-real numbers).
- Hashing of `System.Decimal` is incorrect (https://github.com/IronLanguages/ironpython2/issues/527).
Resolves https://github.com/IronLanguages/ironpython3/issues/268
> Add sys.hash_info and update number hashing

- Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
- Src/IronPythonTest/Util/IniParser.cs
I wonder if I should have been more explicit? For example `[AllCPython.test_email.*]` instead of `[AllCPython.test_email]`?
> Make tests inherit properties

- Src/IronPython/Compiler/Ast/FunctionDefinition.cs
- Src/IronPython/Compiler/Ast/Parameter.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Compiler/PythonGlobal.cs
- Src/IronPython/Compiler/PythonGlobalVariableExpression.cs
- Src/IronPython/Modules/_ast.cs
- Src/IronPython/Runtime/Binding/MetaPythonFunction.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/PythonFunction.Generated.cs
- Src/IronPython/Runtime/PythonFunction.cs
- Src/Scripts/generate_calls.py
- Src/StdLib/Lib/inspect.py
- Tests/test_regressions.py
- Most of `AllCPython.test_keywordonlyarg` is passing except for stuff related to error messages, and SyntaxError for too many arguments.
- We probably need to add some sort of mechanism so that a C# defined method can have keyword-only arguments. Perhaps a `KeywordOnlyAttribute`?
> Keyword only args

- Src/IronPython/Runtime/Operations/ComplexOps.cs
- Tests/test_numberhash.py
Resolves #436.
Implement hashing of complex numbers that adheres to CPython's
standard. Add a unit test verifying that the hash uses both
the real and imaginary components to verify the quality of the
hash.
Some things I was unsure about:
- The code path when the complex's imaginary value is unnecessary (181-183), but I left it thinking that it makes clear that the value is essentially coerced to a double.
- Line 185 is excessively long, but it seems as though the convention for this repository is to keep statements on a single line, regardless the length.
> Properly implement hashing of complex numbers

- Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
- Src/StdLib/Lib/numbers.py
- Src/StdLib/Lib/xml/dom/xmlbuilder.py
- Removes non-existent tests and orders alphabetically
- Changes `xml/dom/xmlbuilder.py` to not raise a syntax error (async keyword)
- Temporarily adds `long` to integer types to get more stuff working
> Clean up tests

- .vsts-ci.yml
The current Ubuntu image we are using will be deprecated on December 1, 2018, this moves to the "new" VM image
> Update to new image and job format

- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Runtime/Filter.cs
- Src/IronPython/Runtime/Map.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Zip.cs
Resolves #503
This is just a direct copying of the map / filter / zip builtins from the Builtin.cs file into their own classes.
However it appears that the (CPython) 3 implementation of these classes differs from the current ones in more fundamental ways, returning stateful iterators instead of an enumerable.
``` python
x = map(lambda x:x+5, [10, 20 , 30])
print(list(x)) # => [15, 25, 35]
print(list(x)) # => []
```
Should these classes be rewritten to implement the `IEnumerator` interface instead of `IEnumerable`?
> [WIP] Make classes for map/filter/zip

- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
Although Python 3.4 documentation states that arguments to [`exec`](https://docs.python.org/3.4/library/functions.html#exec) and [`eval`](https://docs.python.org/3.4/library/functions.html#eval) should be strings, the CPython accepts bytes and bytearray as well. Furthermore, some tests included in the Python standard library assume that `exec` can accept byte strings. This makes sense since the documentation of [`compile`](https://docs.python.org/3.4/library/functions.html#compile) explicitly states that a byte string is accepted.
Support for byte strings and bytearray arguments of `compile` in IronPython already exists.
> Accept byte string as argument to exec and eval

- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPython/Runtime/PythonList.cs
Prep work to eliminate `__cmp__`.
> Only use __lt__ in list.sort

- Src/StdLib/Lib/os.py
- Src/StdLib/Lib/test/support/__init__.py
Revert this when https://github.com/IronLanguages/ironpython3/issues/2 is implemented.
> Bypass surrogateescape in test.support

- make.ps1
The location of `pwsh` is system-dependent. On my Ubuntu Linux, it is `/snap/bin/pwsh`; on my macOS it is `/usr/local/bin/pwsh`. However, the location of `env` is the same on all Unix-like systems.
> Make make.ps1 executable in a portable way

- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonAsciiEncoding.cs
- Src/IronPython/Runtime/PythonEncoding.cs
- Src/IronPythonTest/EncodingTest.cs
This is primarily to enable `PythonAsciiEncoding` to work with the `PythonEncoding` family (`PythonSurrogateEscapeEncoding`, `PythonSurrogatePassEncoding`, and future user-registered encoding error handlers).
The old `PythonAsciiEncoding` was assuming that all fallbacks were stateless. With this change, the workaround for `surrogateescape` to downgrade `PythonAsciiEncoding` to .NET `Encoding.ASCII` is not necessary anymore.
Also, some tests are added to test workings of `PythonAsciiEncoding` with `PythonSurrogateEscapeEncoding`.
> Make PythonAsciiEncoding compliant with System.Text.Encoding protocol

- NuGet.config
I have finally got the build working on my macOS, but it required a change in the NuGet API URL. The old URL points to a non-existent resource and I don't know how the build could have been working on Linux, CI, or on macOS for other people. Perhaps some clever rewriting rules that I don't have. Anyway, the correct URL for the packages index can be easily verified in a web browser.
> Correct NuGet API URL

- Src/IronPython/Runtime/MemoryView.cs
- Src/IronPython/Runtime/Types/PythonType.cs
- Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
- Tests/test_dict.py
- Tests/test_hash.py
It looks like test_hash is just missing a few small changes. The first is that `__hash__` is not inherited when `__eq__` is implemented as of Python 3. The second is that the memoryview type was made hashable if the underlying type is bytes and the buffer is readonly (otherwise throws a ValueError). This is new in Python 3.3.
I couldn't figure out how to create a readonly int buffer without making a memoryview over bytes and then casting it, which isn't yet implemented.
I don't have any checks for the dimensionality of the memoryview because it seems like CPython allows hashing of reshaped memory (this is Python 3.6.6):
```
>>> x = memoryview(bytes(b'abcd'))
>>> x.format
'B'
>>> x.cast('B', shape=[2,2])
<memory at 0x000001CCD9687B40>
>>> y = x.cast('B', shape=[2,2])
>>> y.format
'B'
>>> …
```
> Get test_hash passing

- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonEncoding.cs
- Src/IronPythonTest/EncodingTest.cs
- Tests/test_surrogatepass.py
To perform _surrogatepass_ during decoding, the correct value of `index` of the fallback buffer is essential. Therefore I have added a workaround for the dotnet/corefx#29898 bug. The bug should be resolved in .NET Core 3.0 (and presumably Mono 5.18), but there are still some other frameworks around with it that we want to support.
> Add 'surrogatepass' codec error handler

- Documentation/differences-from-c-python.md
Notes from my recent work with .NET encodings. 
I've only documented differences that are not results of bugs in IronPython or CPython, but rather result of how .NET operates, so it is unlikely they will ever be resolved. Perhaps it is even not desirable to resolve them — after all IronPython is a .NET language.
> Document differences with CPython around handling encodings

- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonAsciiEncoding.cs
- Src/IronPython/Runtime/PythonEncoding.cs
- Tests/test_codecs.py
- Tests/test_unicode.py
To get encoding names on .NET Core, the code detects the most common encodings and gives (most of) them [canonical .NET names](https://docs.microsoft.com/en-us/dotnet/api/system.text.encodinginfo.name?view=netframework-4.7.2). These are not always the same as [CPython's canonical names](https://docs.python.org/3/library/codecs.html?highlight=codecs#standard-encodings), however, all of them are recognized by CPython as at least aliases. I think it is more appropriate to use .NET names here as the code tries to give a name to a .NET object, possibly user-created. Also, it will align the names when run on .NET Core with names from .NET Frm/Mono.
Here are the differences:
| IronPython (and CPython alias) | CPython | .NET Framework |
| --- | --- | --- |
| us-ascii | ascii | us-ascii |
| …
> Interop with System.Text.Encoding, DecoderFallbackException and EncoderFallbackException

- Documentation/differences-from-c-python.md
- Src/IronPython/Compiler/Tokenizer.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPythonTest/EncodingTest.cs
This makes 'utf-7' codec behaviour much closer to CPython's, although still not quite 100%. The documentation and tests are updated accordingly.
As a part of this change I had to extend `EncodingInfoWrapper` to support yet another usage variant, on top of the existing two. As the code was becoming more obscure, I took the liberty to simplify `EncodingInfoWrapper` and eliminate `EncodingWrapper` altogether. The remaining functionality in `EncodingInfoWrapper` had little to do with wrapping `EncodingInfo` any more and a new name `EncodingSingletonFactory` seemed more fitting.
> Allow optional characters in UTF-7

- Src/IronPython/Runtime/Operations/ListOfTOps.cs
- Tests/test_list.py
Resolves #456.
Root cause: After finding an operator with the default operator name, the OperatorResolver bails, and doesn't search for operators with the alternate operator name.
I'm inclined to preserve the current semantics of .NET interop in this case. My understanding of the current policy for member resolution is: find one name for the given member in one class and return only that implementation and its overloads. Standard resolution (ie. looking for the method `__getitem__` itself) has a very high priority, so it it can be used to override most behavior where the underlying class cannot be modified.
That said, I'm also open to going back and solving this by changing member resolution; it's just that I didn't find a reason to do so.
Additional notes:
- `Equals()` is the alternate …
> Allow slicing of List<T>

- Src/IronPython/Runtime/Types/PythonTypeInfo.cs
- Tests/test_strformat.py
Do not resolve methods on Object other forms of member resolution have
been exhausted.
Resolves #465.
Root cause:
> values that live on object need to run before the StandardResolver
> which will pick up values off of object.
There are two things I'm trying to address in this pull request:
- We want to allow types to override object's `__format__` by being IFormattable, but we also want a type to be able to define `__format__` in order to override its IFormattable behavior.
- This issue is likely to happen again whenever we add anything else to ObjectOps.
One potential issue here is that this changes the order of member resolution for `__str__` `__new__` `__repr__` `__hash__` and `__iter__` slightly. While it doesn't seem to have caused any failures on currently enabled tests, if we have …
> Allow IFormattable objects to override __format__

- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Runtime/MemoryStreamContentProvider.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/PythonAsciiEncoding.cs
- Src/IronPython/Runtime/PythonContext.cs
- Tests/encoded_files/cp11334_bad2.py
- Tests/modules/io_related/test_codecs.py
This PR contains mostly error message improvements (to align them more closely with CPython's) and `eval` changes for the bytes-like overload. Perfect alignment will probably not be practical as CPython may generate different error messages depending whether the code is imported, compiled inline, or run from a file given on the command line.
With these changes, `test.test_source_encoding` from StdLib passes (excluding two minor implementation-dependent incompatibilities with CPython).
> Implement PEP-263 and PEP-3120 (WIP 2)

- Src/IronPython.Modules/math.cs
- Src/IronPython.Modules/pyexpat.cs
- Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
Apply division before mutliplication to avoid getting infinity for
large values passed to math.log1p().
Root cause: 
The term log(v1) * v0 is too large to represent in a double for very large v0.
This affects the results of many inputs to log1p:
```
import math
import random 
log = math.log
for _ in range (100):
v0 = random.random() * 1024
v1 = v0 + 1.0
logA = log(v1) * v0 / (v1 - 1.0)
logB = log(v1) * (v0 / (v1 - 1.0))
if (logA != logB):
print('Differing results on input', v0, '---', logA, '!=', logB)
```
Yields several results, but it seems to be within the acceptable margin for test_math. CPython appears to use `log1p()` from the C standard library, but I'm not completely certain of this claim. I tried some of the results from the above in CPython, and got results that matched neither, …
> Get test_math passing

- Src/StdLib/Lib/test/test_source_encoding.py
This change is needed to get `test_source_encoding` working for IronPython.
It is a temporary fix until a proper solution to the compatibility issue is known and implemented.
> Make test_source_encoding.test_issue2301 implementation independent

- Src/IronPython.Modules/nt.cs
- Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
This by no means fixes all `OSError` incompatibilites with CPython 3. It was meant to fix primarily `FileNotFoundError` on file/directory delete. This is order to get `AllCPython.test_source_encoding` passing.
Ideally, proper subclass creation should happen in a more generic place (maybe in `CreatePythonThrowable`?) so that e.g. `OSError(2, 'xxx')` in Python automatically creates `FileNotFoundError(2, 'xxx')` instead.
> Fix some OSError subtype handling in the nt module

- Src/IronPython/Modules/_bytesio.cs
- Src/IronPython/Runtime/MemoryView.cs
- Src/IronPython/Runtime/TypecodeOps.cs
- Tests/test_memoryview.py
Refactor MemoryView to refer to the beginning and ending byte of the
underlying buffer rather than the index of the underlying buffer.
Implement cast() to change the shape and format of the memoryview. Add
tests in IronPython.test_memoryview for this behavior.
Hi, sorry for showing up with such a large commit. I understand if this isn't a high priority since we don't have much by way of C buffers. In any case, I want to get some feedback on whether this change is warranted at the moment and whether the approach is sufficiently clear and/or acceptable before proceeding.
Motivating behavior: with cast() it's possible to have a memoryview that is not aligned with the underlying buffer.
General approach: make `_start` and `_end` refer to the actual byte locations in the buffer. When getting …
> Implement cast() on memoryview

- Src/IronPython.Modules/_codecs.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Tests/encoded_files/ok_encoding_nonascii.py
- Tests/encoded_files/ok_encoding_whitespace.py
- Tests/modules/io_related/test_codecs.py
- Tests/test_class.py
- Tests/test_codecs.py
- Tests/test_excinfo.py
- Tests/test_exec.py
This is primarily making `IronPython.test_codecs` and `IronPython.modules.io_related.test_codecs` runnable under CPython, to make sure that the assumptions made in those tests actually hold. And indeed there was one case where the test was assuming wrong. No practical significance, but still it demonstrated the validity of checking with CPython. Perhaps it would be good to extend the CI to run IronPython tests under CPython on each pull request. The tests can use `@unittest.skipUnlessIronPython` or conditionals `is_ironpython` or `is_cpython` to differentiate behaviour if needed. Any such difference will then be explicit.
Further, I (re)enabled some tests for cases that are no longer problematic or could easily be fixed (fixes included).
> Make codecs tests runnable under CPython

- Src/IronPython/Compiler/UncollectableCompilationMode.cs
- Src/IronPython/Runtime/Binding/BindingHelpers.cs
- Src/IronPython/Runtime/Binding/ConversionBinder.cs
- Src/IronPython/Runtime/Binding/MetaBuiltinFunction.cs
- Src/IronPython/Runtime/Binding/MetaPythonType.Calls.cs
- Src/IronPython/Runtime/Binding/MetaUserObject.Members.cs
- Src/IronPython/Runtime/Binding/MetaUserObject.cs
- Src/IronPython/Runtime/Binding/PythonBinaryOperationBinder.cs
- Src/IronPython/Runtime/Binding/PythonBinder.cs
- Src/IronPython/Runtime/Binding/PythonExtensionBinder.cs
- Src/IronPython/Runtime/Binding/PythonGetMemberBinder.cs
- Src/IronPython/Runtime/Binding/PythonOverloadResolver.cs
- Src/IronPython/Runtime/Binding/PythonProtocol.Operations.cs
- Src/IronPython/Runtime/ClrModule.cs
- Src/IronPython/Runtime/Converter.cs
- Src/IronPython/Runtime/Operations/InstanceOps.cs
- Src/IronPython/Runtime/Operations/ObjectOps.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/PythonTypeOps.cs
- Src/IronPython/Runtime/PythonDocumentationProvider.cs
- Src/IronPython/Runtime/Types/BuiltinFunction.cs
- Src/IronPython/Runtime/Types/NewTypeInfo.cs
- Src/IronPython/Runtime/Types/NewTypeMaker.cs
- Src/IronPython/Runtime/Types/PythonType.cs
- Src/IronPython/Runtime/Types/PythonTypeInfo.cs
- Src/IronPython/Runtime/Types/ReflectedField.cs
Based on IronLanguages/dlr#180
> Remove the usage of some ReflectionUtils methods

- Tests/modules/io_related/test_codecs.py
- Tests/test_codecs_stdlib.py
The IronPython test apparatus allows for inclusion/exclusion of test sets on a module basis. `test_codecs` from stdlib is a large module with over 200 tests, half of them are not passing yet, so this test module is skipped. But the other half of the tests in it provides invaluable coverage and prevents regression.
This PR adds test module `test_codecs_stdlib`, which selectively runs those tests from `test_codecs` that are currently passing. Once IronPython development progresses enough for the whole `test_codecs` to pass, `test_codecs_stdlib` can be removed.
> Add selected tests from stdlib codecs

- Src/IronPython.Modules/_codecs.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
- Tests/test_codecs_stdlib.py
Some of the test from stdlib now pass. Additional tests added.
Something like this will have to be done for UTF-16 as well, but in a separate PR.
> Implement UTF-32 support in codecs module

- .gitignore
- Src/IronPython/Runtime/Operations/FloatOps.cs
- Src/StdLib/Lib/test/test_pow.py
- Tests/test_pow.py
Hopefully this is the right way to do it.
The float path is tested through test_clrnuminterop.py.
> Implemented Support pow of negative numbers with fractional powers #504

- Src/StdLib/Lib/test/test_codecs.py
- Tests/test_codecs_stdlib.py
IronPython's strings are in the UTF-16 form thus decoding a surrogate pair always results in two characters. Consequently, decoding a broken surrogate pair with a `replace` error handler results in **two** U+FFFD rather than one as it is in case of CPython.
> Modify tests in stdlib to account for UTF-16 strings in .NET

- Src/IronPython.Modules/_bisect.cs
- Src/IronPython/Runtime/Operations/InstanceOps.cs
- Src/IronPython/Runtime/PythonContext.cs
Removed `GetComparer` related dead code and modernizes PythonContext. Part of prep work to eliminate `__cmp__`.
> PythonContext cleanup

- Src/IronPython.Modules/_codecs.cs
- Tests/test_codecs_stdlib.py
Deprecated since Python 3.3. Removed in Python 3.8.
https://bugs.python.org/issue36297
> Deprecate unicode_internal codec

- Src/IronPython.Modules/_codecs.cs
Because decoding processes input as sequence of bytes, rather than chars, I think it is cleaner to use byte tests rather than the full-blown Unicode char tests.
The code stays functionally the same. It should have went with #666.
> Cleanup utf-7

- Src/IronPython.Modules/_codecs.cs
- Src/IronPython/Runtime/LiteralParser.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
The exceptions are used by raw-unicode-escape codec.
This PR is part of raw-unicode-escape implementation.
> Fix Unicode parse exceptions

- Src/IronPython.Modules/_codecs.cs
- Src/IronPython/Compiler/Tokenizer.cs
- Src/IronPython/Modules/unicodedata.cs
- Src/IronPython/Runtime/LiteralParser.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
- Tests/test_codecs_stdlib.py
This PR was meant to just implement decoding of `unicode-escape`, but since `unicode-escape` shares code with the literal parser, the latter got dragged in as well. Some subtle bugs in the literal parser got exposed, which I've hopefully fixed now. I have not added any tests for the parser; I've started doing it in `test_syntax`, but it turns out the whole test currently does not pass. I guess there is more work to be done on the parser. I'm wondering whether the parser is not a higher priority than the codecs.
> Implement decoding for 'unicode-escape' codec

- Src/IronPython.Modules/_codecs.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
- Tests/test_codecs_stdlib.py
Implementation of the class `UnicodeEscapeEncoding` gives priority to the methods accepting `string` rather than the usual `char[]` because this is how we use the encoding and it matches the parameter type of supporting methods. This reduces the number of type conversions needed.
> Implement encoding of (raw-)unicode-escape codec

- Src/IronPython.Modules/_codecs.cs
- Src/IronPython/Runtime/LiteralParser.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
- Tests/test_codecs_stdlib.py
And here [we have it](https://github.com/IronLanguages/ironpython3/pull/676#discussion_r346542744): `LiterslParser.ParseBytes` with `normalizeLineEndings: false`.
This is an RFC at this moment because of a regression: the old code supported `replace` error handler, which is temporarily gone. In the new code, error handlers will be implemented differently and I'd rather have this submission reviewed and agreed on before moving forward.
> Fix codecs.escape_decode

- Src/IronPython.Modules/_codecs.cs
`escape_encode` is bytes => bytes encoding, so there is no need to go though `StringBuilder`. 
This function could also have been implemented by a call to `StringOps.ReprEncode`, but `ReprEncode` is string => string, so it would either be bytes -> string => string -> bytes, or, if `ReprEncode` were made generic, bytes =>string -> bytes. Since `escape_encode` is simple as it is, I think it is not worth messing with `ReprEncode`.
> Clean up escape_encode

- Src/IronPython.Modules/_codecs.cs
- Src/IronPython/Runtime/LiteralParser.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
- Tests/test_codecs_stdlib.py
Similarities to `escape_decode` turned out to be smaller than I expected.
> Implement error handling for (raw-)unicode-escape codec

- Src/IronPython/Runtime/Binding/PythonProtocol.Operations.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPythonTest/Conversions.cs
- Tests/modules/misc/test__weakref.py
- Tests/modules/system_related/test_nt.py
- Tests/test_attr.py
- Tests/test_builtinfunc.py
- Tests/test_bytes.py
- Tests/test_dict.py
- Tests/test_tuple.py
Remove type comparison fallbacks for the '<', '>', '<=', and '>='
operators and throw a TypeError instead when no suitable comparator is
found between two types.
Listed in #33.
> Remove comparison operator fallbacks

- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonContext.cs
- Tests/modules/io_related/test_codecs.py
Current `codecs` module lacks a number of standalone error handling functions (or, to be exact, the exported symbols are not callable):
```
>>> import codecs
>>> [ f for f in dir(codecs) if f.endswith("errors")]
['backslashreplace_errors', 'ignore_errors', 'replace_errors', 'strict_errors', 'xmlcharrefreplace_errors']
```
This PR implements `strict_errors` as a pilot; if the approach is agreed upon, I will implement the remaining ones in a similar fashion.
I am not quite sure whether using a delegate to put into the error handlers dictionary is the right way; perhaps there is a better, more ironpythonic way of doing it. As it is now, there are some subtle differences between IronPython and CPython regarding the type:
_CPython_:
```
>>> codecs.strict_errors
<built-in function …
```
> Implement codecs.strict_errors

- Src/IronPython/Runtime/Binding/ConversionBinder.cs
- Src/IronPython/Runtime/Binding/PythonProtocol.Operations.cs
- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Operations/IListOfByteOps.cs
- Src/IronPython/Runtime/Operations/InstanceOps.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/PythonTypeOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonBytesIterator.cs
- Src/IronPython/Runtime/PythonHiddenAttribute.cs
- Src/IronPython/Runtime/PythonStrIterator.cs
Renames and moves the `str_iterator` and `bytes_iterator` types to new files and marks its C# members are `PythonHidden`. Also allows `PythonHiddenAttribute` on properties.
> Clean up str/bytes iterator code

- .gitignore
- Src/IronPython/Lib/iptest/test_env.py
The value of `sys.platform` in CPython on Linux is `linux`, while IronPython reports `posix`. Many tests that are not meant to be run on Linux are guarded by `is_posix`, so I have extended the definition of it to include what CPython reports. In this way I am able to verify the tests with CPython while working on Linux.
CPython is apparently more detailed in `sys.platform` than IronPython (which only differentiates `darwin`), and adding only `'linux'` here is not exhaustive for all POSIX systems. CPython will report `posix` as `os.name` (which includes the `darwin` case) and `sys.platform` as `unknown` if not recognized.
Note that the value of `sys.platform` is printed out on REPL start, right after `on`:
<pre><code>Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 …
> Enable testing with CPython on Linux

- Tests/modules/io_related/test_codecs.py
There seems to be a race condition in `__inport__` in CPython 3.4 on Linux, that a 10 ms delay solves.
> Test codecs linux

- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
It works, but I feel uneasy about using a type which name starts with an underscore, although the type itself is public. Is it the right way of doing? If not, here is an alternative implementation of `ignore_errors`, which I can push in the next commit:
```csharp
private static object IgnoreErrors(CodeContext context, object unicodeError) {
switch (unicodeError) {
case PythonExceptions.BaseException _:
var ptype = DynamicHelpers.GetPythonType(unicodeError);
if (ptype.Name == "UnicodeDecodeError" || ptype.Name == "UnicodeEncodeError") {
if (ptype.TryGetBoundAttr(context, unicodeError, "end", out object ret) && ret is int end) {
return PythonTuple.MakeTuple(string.Empty, end);
}
}
goto default;
case DecoderFallbackException dfe: 
return PythonTuple.MakeTuple(string.Empty, dfe.Index + …
```
> Implement codecs.ignore_errors

- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
This PR implements `replace_errors`, `backslashreplace_errors` and `xmlcharrefreplace_errors` from `codecs`. In the positive cases (i.e. valid `UnicodeError` instances), the functions behave like their CPython counterparts.
Negative cases are more interesting. CPython seems to coerce invalid range values:
```python
>>> import codecs as cd
>>> cd.backslashreplace_errors(UnicodeEncodeError("X", "abcd", 2, 6, "-"))
('\\x63\\x64', 4)
>>> cd.backslashreplace_errors(UnicodeEncodeError("X", "abcd", -2, 2, "-"))
('\\x61\\x62', 2)
>>> cd.backslashreplace_errors(UnicodeEncodeError("X", "abcd", -2, 6, "-"))
('\\x61\\x62\\x63\\x64', 4)
```
However, it does not do it consistently:
```python
>>> cd.backslashreplace_errors(UnicodeEncodeError("X", "abcd", 4, 4, "-"))
('\\x64', 4)
>>> …
```
> Implement codecs.*replace_errors

- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonEncoding.cs
- Src/IronPythonTest/EncodingTest.cs
- Tests/modules/io_related/test_codecs.py
This PR implements the `codecs.surrogateescape_errors` builtin function with the accompanying tests. The same caveat applies as for the previous error handlers: in case of misconstructed `UnicodeError` the way how the range gets coerced may sometimes differ from CPython, but in no instance will it throw `IndexError`.
During testing I discovered that my original understanding of [PEP 383](https://www.python.org/dev/peps/pep-0383/) was wrong. I thought that PEP 383 forbids smuggling of ASCII characters, but it actually forbids smuggling of ASCII bytes. Consequently, `surrogateescape` cannot be meaningfully used with wide-char encodings, like UTF-16 or UTF-32. The Python documentation doesn't mention it, but the PEP does say it is intended for ASCII-compatible encodings only. On the bright …
> Surrogateescape errors

- Documentation/building.md
Hi.  
I've noticed 'building.md' is out-dated so I wrote a patch to catch up.   
Here's description of the changes.
- Submodule [DLR@19ef3b5](https://github.com/IronLanguages/dlr/tree/19ef3b59c9f5a0255ee1286a897095ba00773c3e) requires .NET Core SDK 3.0.100 in its [global.json]( https://github.com/IronLanguages/dlr/blob/19ef3b59c9f5a0255ee1286a897095ba00773c3e/global.json).  
- According to [the Download page](https://dotnet.microsoft.com/download/visual-studio-sdks), .Net Core SDK 3.0 is not supported on Visual Studio 15.x.
> Update documentation to catch up build requirements.

- Tests/interop/net/field/test_field_misc.py
- Tests/interop/net/field/test_fields_inside_enum.py
- Tests/interop/net/field/test_initonly_fields.py
- Tests/interop/net/field/test_instance_fields.py
- Tests/interop/net/field/test_literal_fields.py
- Tests/interop/net/field/test_static_fields.py
- Tests/interop/net/property/test_indexercs.py
- Tests/interop/net/property/test_property.py
- Tests/modules/io_related/test_codecs.py
- Tests/test_datetime.py
- Tests/test_function.py
- Tests/test_hash.py
- Tests/test_methoddispatch.py
- Tests/test_regressions.py
- Tests/test_struct.py
Hi,   
I wrote a patch to resolve #714.  
I looked around `Tests/**.py` and replaced deprecated API aliases as described in [the unittest documentation](https://docs.python.org/3/library/unittest.html#deprecated-aliases).  
Here are some descriptions of the changes:   
- Replaced `assertEquals()` to `assertEqual()`
- Replaced `assertNotEquals()` to `assertNotEqual()`
- Replaced `assertRaisesRegexp()` to `assertRaisesRegex()`
> Fix usage of deprecated unittest APIs

- Src/IronPython.Modules/_weakref.Generated.cs
- Src/IronPython.Modules/_weakref.cs
- Tests/modules/misc/test__weakref.py
Add slots for all comparison operators which delegate to the object
being proxied.
Resolves #697
> Make weakref proxies delegate comparison operators

- Src/IronPython.Modules/_thread.cs
- Src/IronPython.Modules/winreg.cs
- Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
- Tests/test_regressions.py
Hi, 
I wrote a patch to resolve #410.  
The code shown in #410 causes a deadlock because `_set_sentinel()` is not implemented as `threading.py` expects; an lock object returned by `_set_sentinel()` should be released on its thread exit.  
I also implemented a lacking feature, timeout for `acquire()` as well. 
According to [the documentation](https://docs.python.org/3/library/threading.html#threading.Lock.acquire), timeout is only supported on blocking acquire.
> Making `test_winreg` passes.

- Src/IronPython/Compiler/Ast/PythonNameBinder.cs
- Src/IronPython/Compiler/Parser.cs
- Tests/test_dict.py
- Tests/test_regressions.py
Hi, this PR resolves #451.  
This PR contains some patching solutions which run at the AST stage.   
1. `__class__` in the AST are converted to `name_of_the_class.__class__`.  
2. `super()` in the AST are converted to `super(name_of_the_class.__class__, 1st argument)`. 
As a result, `__class__` in non-global context are completely removed.  
-----
`unbound variable $localContext` is caused by referencing \_\_class__ in non-global context like...  
```
class in_global(object):
def __init__(self):
super().__init__()
```
```
def f():
class in_function_scope(object):
def __init__(self):
super().__init__()
```
`FunctionDefinition.cs` has some handling code for "\_\_class__" keyword, but this code works only if a ClassDefinition is declared in global context, because it's relying on …
> Get super() and __class__ works in non-global context.

- Src/IronPython/Compiler/Ast/WithStatement.cs
- Tests/test_excinfo.py
Resolves https://github.com/IronLanguages/ironpython3/issues/726
> Save/restore exc_info in context manager

- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
This PR implements the `codecs.surrogatepass_errors` builtin function with the accompanying tests. It completes the implementation of `codecs.*_errors` builtins. There are still a few loose ends in those error handlers, which I will fix up in separate PRs (e.g., support for `UnicodeTranslateError`).
But a bigger issue is that there is now quite some duplicate error handling code:
* `codecs.strict_errors` and `StringOps.ExceptionFallback`
* `codecs.replace_errors` and `StringOps.ReplacementFallback`
* `codecs.ignore_errors` and `StringOps.PythonDecoderFallback`
* `codecs.xmlcharrefreplace_errors` and `StringOps.XmlCharRefEncoderReplaceFallback`
* `codecs.backslashreplace_errors` and `StringOps.BackslashEncoderReplaceFallback`
* `codecs.surrogateescape_errors` and …
> Implement codecs.surrogatepass_errors

- Src/IronPython/Runtime/Binding/PythonProtocol.Operations.cs
- Src/IronPython/Runtime/Operations/ObjectOps.cs
- Src/IronPython/Runtime/Types/PythonTypeInfo.cs
- Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
Default to negating the result of `__eq__` when the `__ne__` slot is not
defined. Enable test_compare.py.
Looks like the earlier issues in this file have been fixed by other changes. According to the definition at `https://docs.python.org/3/reference/datamodel.html#object.__ne__`,
> By default, __ne__() delegates to __eq__() and inverts the result unless it is NotImplemented. There are no other implied relationships among the comparison operators, for example, the truth of (x<y or x==y) does not imply x<=y.
It doesn't look like the behavior the test is looking for has changed in later Python versions; in 3.8,
```
class C:
def __init__(self):
pass
def __ne__(self, other):
print('A')
return NotImplemented
def __eq__(self, other):
print('B')
return True
print(C() != 3)
```
Prints
```
A
True …
```
> Get test_compare passing

- Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
Practically, `UnicodeTranslateError` is handled only in `strict`, `ignore`, and `replace` handlers. In all other standard handlers it throws `TypeError` with a custom message.
These scenarios are covered by `test_codeccallbacks.py` from stdlib, but I don't know when this test module will be enabled so I added a few simple tests in `modules/io_relates_test_codecs.py`.
I also added a method to `_UnicodeTranslateError` to provide the same display of the error message as CPython's. There are no tests for that, though.
> Support UnicodeTranslateError in error handlers

- Src/IronPython.Modules/_codecs.cs
- Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
- Tests/modules/io_related/test_codecs.py
`codecs.charmap_*` functions are heavily under-tested. Python's StdLib has only one lightweight test (which I enable here) and depends on good coverage through testing of `iso-8859` encodings, which in turn depend on the charmap functionality. In IronPython, however, those encodings are dirrectly pulled from the .NET library, rather than going through charmap. So I have added some extensive tests for `charmap_encode` in its basic form.
`charmap_decode` and `charmap_build` are still to go.
> Fix codecs.charmap_encode

- Tests/test_datetime.py
By no means comprehensive update to `test_datetime`. Simply to get the test passing on 2020-02-29.
> Make IronPython.test_datetime passing on Feb 29

- Src/IronPython.Modules/_codecs.cs
- Src/Scripts/generate.py
- Tests/modules/io_related/test_codecs.py
- Tests/test_codecs_stdlib.py
`codecs.charmap_encode`/`decode` use a different encoding class (`EncodingMapEncoding`) when given a map in optimized form than when given a regular dictionary (`CharmapEncoding`). I have considered merging those classes, but ultimately decided to keep them separate. There are some similarities, but shared code is not that big.
Curiosity: CPython's `charmap_build` produces a regular Python dict (hence unoptimized) unless byte 0 maps to character NUL. IronPython will always produce an optimized map (`<class 'EncodingMap'>`).
> Fix codecs.charmap in optimized form

- Src/IronPython.Modules/_codecs.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/modules/io_related/test_codecs.py
This PR has more than just nullable annotations. I have gone though the whole API surface for `_codecs` to determine whether parameters should allow `None` or not and I have extended the tests to cover that. Once `NotNullAttribute` was properly assigned, the nullable annotations followed.
It was a worthwhile exercise that uncovered a few bugs. Also, I have made a surprising discovery: most CPython's `encode` and `decode` functions will treat `None` error handler as `"strict"`. I have updated the code accordingly. This is fortunate, as `a null` check is much more efficient than string comparison, so `null` is the default now.
> Add nullable annotations in _codecs

- Src/IronPython.Modules/_codecs.cs
- Tests/test_codecs_stdlib.py
Python StdLib has a wide array of codecs, but there are subtle differences between them and other codecs sets, notably codecs from .NET and codecs from Win32 API. In principle, the Python codecs are preferred for Python programs, but in some circumstances one may want to use other codecs. CPython recognizes that and offers access to Win32 codecs through `codecs.code_page_encode` and `codecs.code_page_decode`. 
One notable difference is that Win32 encoder (`WideCharToMultiByte`), when used with the `'replace'` error handler, will attempt to downgrade a diacritical character to its Latin equivalent if the original character cannot be encoded. For instance, 'Ł' is replaced by 'L', and 'ÿ' is replaced by 'y'.
IronPython uses .NET codecs in many circumstances where Python StdLib codecs should …
> Implement rudimentary code_page_encode and code_page_decode

- Src/IronPython/Runtime/Binding/ConversionBinder.cs
As discussed in #762, point 6.
> Remove automatic conversion from string to ByteArray in Binder

- Src/IronPython/Runtime/Operations/ArrayOps.cs
- Tests/test_array.py
Fixes:
```
>>> System.Array[System.Byte](1000)
TypeError: expected object with __len__ function, got int
```
> Accept int parameter(s) in System.Array constructor

- Build.proj
- Src/IronPythonConsole/IronPythonConsole.csproj
Unfortunately, .NET Core 3.1 on macOS does not produce a standalone executable, so the shell script is still needed.
> Fix failing tests on .NET Core 3.1 on macOS

- Src/IronPython.Modules/_codecs.cs
- Src/IronPython/Compiler/Tokenizer.cs
- Src/IronPython/Runtime/LiteralParser.cs
- Tests/modules/io_related/test_codecs.py
- Tests/test_bytes.py
Was:
```
>>> print(b"ÿ")
b'\xff'
```
Now:
```
>>> print(b"ÿ")
File "<stdin>", line 1
print(b"ÿ")
^
SyntaxError: bytes can only contain ASCII literal characters.
```
> Report SyntaxError for non-ASCII characters in bytes literals

- Src/IronPython/Runtime/Operations/IListOfByteOps.cs
Was:
```
>>> print(b"'")
b'\''
```
Now:
```
>>>  print(b"'")
b"'"
```
Double quotes are used only if needed to quote single quotes and no other double quotes need to be quoted. The previous sentence was supposed to be a clarification...
> Use double quotes for bytes representation

- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/Operations/IListOfByteOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
Several related bugs in `split`/`rsplit` fixed, mostly for `bytes`/`bytearray`.
Assorted examples:
Was:
```
>>> import sys
>>> b'<tag></></tag>'.split(b'</>')
[b'', b'g', b'', b'tag', b'']
>>> b'A,B,C,D'.split(b',', sys.maxsize-100)
MemoryError: Array dimensions exceeded supported range.
>>> b'A B C'.split(maxsplit=1)
TypeError: split() got an unexpected keyword argument 'maxsplit'
```
Now:
```
>>> import sys
>>> b'<tag></></tag>'.split(b'</>')
[b'<tag>', b'</tag>']
>>> b'A,B,C,D'.split(b',', sys.maxsize-100)
[b'A', b'B', b'C', b'D']
>>> b'A B C'.split(maxsplit=1)
[b'A', b'B C']
```
> Fix split/rsplit

- IronPythonAnalyzer/IronPythonAnalyzer/IronPythonAnalyzerAnalyzer.cs
- Src/IronPython.Modules/IronPython.Modules.csproj
- Src/IronPython.Modules/_codecs.cs
- Src/IronPython.Modules/_ctypes/CData.cs
- Src/IronPython.Modules/winreg.cs
- Src/IronPython.SQLite/Connection.cs
- Src/IronPython.SQLite/Cursor.cs
- Src/IronPython/Compiler/Tokenizer.cs
- Src/IronPython/IronPython.csproj
- Src/IronPython/Modules/_bytesio.cs
- Src/IronPython/Modules/_io.cs
- Src/IronPython/Modules/array.cs
- Src/IronPython/Runtime/ArrayData.cs
- Src/IronPython/Runtime/Binding/ConversionBinder.cs
- Src/IronPython/Runtime/Binding/PythonOverloadResolver.cs
- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/BytesLikeAttribute.cs
- Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
- Src/IronPython/Runtime/IBufferProtocol.cs
- Src/IronPython/Runtime/LiteralParser.cs
- Src/IronPython/Runtime/MemoryView.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/interop/net/dynamic/test_dynamic_regressions.py
- Tests/modules/io_related/test_codecs.py
- Tests/test_bytes.py
- Tests/test_codecs_stdlib.py
This the first step of a feasibility study of using `Span` for bytes-like objects (triggered by #762). I address here my first concern for encodings not having access to the underlying `byte[]` hence needing to copy data to a new array every time on decode.
I did the experiments in net45; I didn't want to get sidetracked by the target upgrade. Once the project target is upgraded to .NET 4.6, we can use/override `Encoding.GetString(bytes*, ...)`, which will eliminate a few copy actions in my feasibility code. Since those changes are straightforward, there is no need to address them in this exercise.
My first concern was the feasibility of `Span` (i.e. byte pointer overloads) for `UnicodeEscapeEncoding`. This encoding depends on `LiteralParser`, which in its turn serves two masters, …
> Unsafe encoding

- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Slice.cs
Was:
```
>>> plist = [1, 2]
>>> plist[0:None:2<<222] = [0]
ValueError: too many items in the enumerator need 0 have 1
>>> plist[0:None:2<<222] = [111, 222]
ValueError: too many items in the enumerator need 0 have 2
```
Now:
```
>>> plist = [1, 2]
>>> plist[0:None:2<<222] = [0]
>>> plist
[0, 2]
>>> plist[0:None:2<<222] = [111, 222]
ValueError: too many items in the enumerator need 1 have 2
```
Which is the same as CPython, except that the message for `ValueError` reads `attempt to assign sequence of size 2 to extended slice of size 1`. Do we care about the error message?
The …
> Fix list assignment using extended slice with big integers

- Src/IronPython.Modules/_ctypes/Array.cs
- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/MemoryView.cs
- Src/IronPython/Runtime/Operations/ArrayOps.cs
- Src/IronPython/Runtime/Operations/IListOfByteOps.cs
- Src/IronPython/Runtime/Operations/ListOfTOps.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonList.cs
- Src/IronPython/Runtime/PythonRange.cs
- Src/IronPython/Runtime/Slice.cs
This is the continuation of #777. Hopefully I have fixed all places. I see a lot of similar, but ultimately tricky calculations being done in different places, so I propose to move `GetSliceLength` and `CoalesceToInt32` from `MemoryView` to `PythonOps` and let the rest of the code to use those functions.
> Fix sequence assignments using extended slice with big integers

- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Runtime/Converter.cs
- Src/IronPython/Runtime/Operations/PythonCalls.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/test_builtinfunc.py
- Tests/test_unicode_stdlib.py
Sorry for a large commit; things turned out to be more interdependent than I expected. The `str` API is still not quite done, even with null handling; I have fixed only the obvious issues.
----
It turns out that my changes in `PythonCalls` were not exactly the same as in #789: I didn't have `[NotNull]` on `func` objects. Why is it needed?
> Add nullable annotations to StringOps

- Src/IronPython/Runtime/Bytes.cs
- Tests/test_bytes_stdlib.py
This is not exactly like `bytearray` does it, but follows the agreed convention to provide a separate overload ISO a default value for a parameter, if Python does not define such default.
> Support error handler in constructing bytes from string with encoding

- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/PythonBytesIterator.cs
- Tests/test_bytes.py
Adds ability to initialize `bytes`/`bytearray` with objects implementing `__index__`.
This solution may still change once `long`/'int` unification is done.
> Support bytes/bytearray initialization through __index__

- Src/IronPython.Modules/IterTools.cs
- Src/IronPython.Modules/_collections.cs
- Src/IronPython.Modules/_functools.cs
- Src/IronPython/Runtime/Filter.cs
- Src/IronPython/Runtime/Map.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/SetStorage.cs
- Src/IronPython/Runtime/SimpleNamespace.cs
- Src/IronPython/Runtime/Zip.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Src/IronPythonTest/Cases/CaseExecuter.cs
- Src/IronPythonTest/Cases/CaseGenerator.cs
- Src/IronPythonTest/Cases/IronPythonCases.cs
- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Tests/test_unicode_stdlib.py
- Add `__reduce__` methods to `map`, `filter`, `zip`, `_functools.partial`, `itertools.*`
- Fix recursive repr in `SimpleNamespace`, `set`, `defaultdict`
- Fix `__str__` of string subclass
- Testing cleanup
> Resolve various StackOverflowExceptions in tests

- Src/IronPython.Modules/_weakref.cs
- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/FunctionCode.cs
- Src/IronPython/Runtime/Operations/DecimalOps.cs
- Src/IronPython/Runtime/Operations/ObjectOps.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/PythonDictionary.cs
- Src/IronPython/Runtime/PythonRange.cs
- Src/IronPython/Runtime/Types/BuiltinFunction.cs
- Src/IronPython/Runtime/Types/PythonType.cs
Removes comparisons from `type` and adds rich comparison methods to `object`.
> Comparison cleanup

- Src/IronPython/Lib/iptest/ipunittest.py
- Tests/modules/system_related/test_sys_getframe.py
- Tests/test_class.py
- Tests/test_weakref.py
Caused `IronPython.test_weakref` to be ridiculously slow...
> Get rid of force_gc

- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/StdLib/Lib/fractions.py
- Tests/test_isinstance2.py
There are some checks for `isinstance(val, int)` in the stdlib (e.g. `fractions` and `ipaddress`) which end up failing when `val` is a `BigInteger`. This forces `isinstance` to return `true` in that case.
Reverts the workaround in https://github.com/IronLanguages/ironpython3/pull/845
Related to https://github.com/IronLanguages/ironpython3/issues/52
> Make isinstance(val, int) return true for long

- Src/IronPython/Lib/iptest/__init__.py
- Src/IronPython/Modules/Builtin.cs
- Src/Scripts/generate_alltypes.py
- Src/StdLib/Lib/numbers.py
- Src/StdLib/Lib/pickle.py
- Src/StdLib/Lib/test/test_array.py
- Tests/interop/net/field/test_initonly_fields.py
- Tests/interop/net/field/test_literal_fields.py
- Tests/modules/io_related/test__bytesio.py
- Tests/modules/misc/test_math.py
- Tests/modules/misc/test_operator.py
- Tests/modules/system_related/test_nt.py
- Tests/modules/type_related/test_array.py
- Tests/test_bigint.py
- Tests/test_bool.py
- Tests/test_builtinfunc.py
- Tests/test_bytes.py
- Tests/test_clrnuminterop.py
- Tests/test_datetime.py
- Tests/test_dict.py
- Tests/test_function.py
- Tests/test_ironmath.py
- Tests/test_kwarg.py
- Tests/test_list.py
- Tests/test_number.py
- Tests/test_strformat.py
- Tests/test_tuple.py
Related to https://github.com/IronLanguages/ironpython3/issues/52
> Remove long from builtin

- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Runtime/ClrModule.cs
- Src/IronPython/Runtime/DictionaryOps.cs
- Src/IronPython/Runtime/Operations/InstanceOps.cs
- Src/IronPython/Runtime/PythonList.cs
- Src/IronPython/Runtime/SimpleNamespace.cs
- WhatsNewInPython30.md
Rename original `list.sort()` to `list.Sort()` so that it could still be called from c#
Listed in #33
> key and reverse arguments are keyword only, for builtin.sorted() and list.sort()

- Src/IronPython.Modules/array.cs
- Tests/modules/type_related/test_array.py
Apparently, `memoryview` used to initialize `array.array` is treated as an iterable, not a bytes-like object. This is true also for other objects implementing Python buffer protocol (like Numpy's ND-arrays), exept for `bytes` and `bytearray`.
`array.array.frombytes`, on the other hand, always treats its argument as a bytes-like object.
> Fix array.array construction from memoryview

- Tests/test_surrogateescape.py
The behaviour of the `surrogateescape` error handler is only well defined for ASCII-compatible encodings. From [PEP 383](https://www.python.org/dev/peps/pep-0383/#discussion):
> Encodings that are not compatible with ASCII are not supported by this specification
Both UTF-16 and UTF-32 are not ASCII compatible. CPython, however, does not raise `NotImplementedError` with these encodings when `surrogateescape` is used. It will often produce something, and sometimes fail with `UnicodeDecodeError` /`UnicodeEncodeError`. IronPython tries to mimic CPython's behaviour in those cases. The efforts seem to be largely successful for the UTF-16 case, but not so for UTF-32 case, in which case the CPython's behaviour is less consistent. Therefore I have disabled the `surrogateescape` test with UTF-32 …
> Get test_surrogateescape passing with CPython

- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Tests/test_methodbinder1.py
- Tests/test_methodbinder2.py
- Tests/test_methoddispatch.py
Enables test_methodbinder1, test_methodbinder2 and test_methoddispatch.
Related PRs:
- https://github.com/IronLanguages/ironpython3/pull/828
- https://github.com/IronLanguages/ironpython3/pull/891
> Enable some tests

- .github/workflows/main.yml
- Src/IronPython.Modules/zipimport.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Modules/_fileio.cs
- Src/IronPython/Runtime/Importer.cs
- Src/IronPython/Runtime/Types/Mro.cs
- Src/IronPython/Runtime/Types/PythonType.cs
- Src/IronPython/Runtime/Types/PythonTypeInfo.cs
- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Tests/ImpTest/__init__.py
- Tests/ImpTest/imptestmod.py
- Tests/test_doc.py
- Tests/test_imp.py
There are still a tests which are marked as `expectedFailure` which need to be debugged (note that they also fail with CPython).
> Enable test_imp

- Src/IronPython/Runtime/Binding/PythonOverloadResolver.cs
- Src/IronPython/Runtime/Converter.cs
- Tests/test_memoryview.py
- Tests/test_methodbinder2.py
This resolves the problem with `System.UIntPtr` from #868.  `BigInteger` to `UInt64` is now performed at narroving level _One_, just like for `Int64`. This puts it at a higher preference level than the conversion from `BigInteger` to `Int32`/`UInt32`, which are done at narrowing level _All_ (lowest).
It does not address the fact that `double`/`float` will be preferred over `ulong`. This is because conversion from `BigInteger` to `Double` and `Single` is already done at narrowing level _None_ (highest priority), which normally means no data loss. This is not entirely accurate:
```
>>> import System 
>>> int(float(System.UInt64.MaxValue)) - System.UInt64.MaxValue
1
>>> int(float(0xFFFFFFFFFFFFFFFF)) - 0xFFFFFFFFFFFFFFFF
-2047
>>> System.UInt64.MaxValue - 0xFFFFFFFFFFFFFFFF        
0
``` …
> Prefer BigInteger to UInt64 conversion over to Int32/UInt32

- Src/IronPython/Runtime/Binding/MetaPythonFunction.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Tests/test_kwarg.py
- Tests/test_regressions.py
In cases where a parameter is pulled from a positional argument or
keyword argument, ensure that it does not also appear in an unpacked
dictionary going to kwargs.
Resolves #866
> Validate arguments are not duplicated in kwargs

- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Tests/modules/network_related/test__socket.py
Fixes one of the remaining problems from the change in #916.
It appears that without process isolation, the server port is owned by the kernel, which then refuses connections from a regular user process. With process isolation, the server process is `ipy` and runs under the same user ID as the client.
I am not sure whether this patch is not simply masking a deeper issue with the current `_socket` implementation.
> Fix test__socket failure on macOS

- Src/IronPython/Modules/sys.cs
- Tests/modules/system_related/test_sys.py
Add Array.Sort to the keys array prior to publication in sys.builtin_module_names so that it is properly sorted as expected.
> Fix the sort on the builtin module names array (#875)

- Src/IronPython.Modules/_codecs.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPython/Runtime/PythonEncoding.cs
- Tests/modules/io_related/test_codecs.py
`PythonEncoderFallback` in `StringOps` had the ability to support custom encoding error handlers, but only those that provide fallback data as string. On the other hand, `PythonEncoderFallback` in `PythonEncoding` has the ability to process fallback data in a form of raw bytes, but not string and it did not support custom error handlers. In Python, a custom error handler may produce fallback data as either string or bytes.
This PR merges both solutions into one: `PythonErrorHandlerEncoding.PythonHandlerEncoderFallback` so that custom error handlers during encoding may be correctly supported.
Moving the encoding cursor from a custom error handler is still not supported.
> Support custom encoding error handler

- Tests/modules/network_related/test__socket.py
This should provide enough information whether socket test failures are due to problems on the client or the server side. Then more detailed reporting can be implemented on the problematic side to investigate further.
> Report error exit code of test socket server

- Tests/modules/network_related/test__socket.py
Follow up on #927: more diagnostic info on the client side. 
I also increased the maximum wait time to 20 s because on my old mac 10 s was sometimes not enough when a number of tests were running in parallel.
> Report wait time of failed wait for test socket server

- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Src/StdLib/Lib/subprocess.py
- Src/StdLib/Lib/test/regrtest.py
- Src/StdLib/Lib/test/test_uuid.py
> Use System.Diagnostics.Process to implement subprocess.Popen, which could be used on posix and windows

- Src/IronPython/Runtime/PythonEncoding.cs
- Tests/modules/io_related/test_codecs.py
This is a continuation of #923, which I inadvertently closed. Commits form Aug 08 have been already reviewed by @slozier.
> Eliminate data copy when encoding string with PythonEncoding (2)

- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
This works fine on Windows, but not so on macOS/Linux. Apparently, `Mutex` implementation in Mono doesn't work as expected. As a workaround, I run tests with `-frameworks notcoreapp2.1,netcoreapp3.1` and then Mono separately.
I don't know how to make it work under Mono. I am making this pull request anyway since it is better than nothing. @slozier, @jameslan, any ideas?
> Disable parallel execution for test_gettext

- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/Operations/ByteOps.cs
- Src/IronPython/Runtime/Operations/IntOps.cs
- Src/IronPython/Runtime/Types/TypeCache.Generated.cs
- Src/Scripts/generate_typecache.py
- Tests/test_bytes.py
- Tests/test_bytes_stdlib.py
This is primarily to support the following case (from stdlib tests):
```python
class BytesSubclass(bytes):
pass
class SomeClass:
def __bytes__(self):
return BytesSubclass(b'abc')
assert type(bytes(SomeClas())) is BytesSubclass
```
Also an opportunity to clean up constructor overloads in `Bytes`.
> Implement Bytes.__new__

- IronPythonAnalyzer/IronPythonAnalyzer/IronPythonAnalyzerAnalyzer.cs
- Src/IronPython/Runtime/Binding/PythonOverloadResolver.cs
- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/BytesLikeAttribute.cs
- Tests/test_bytes.py
I had to tweak `bytes` construction a little again. Apparently, it is not only  "always call `__bytes__`", but also  "always call `__index__`" — except when constructing from `str` or `int` derived classes…
A similar story in `bytearray`.
> Support __index__ on additional code paths in Bytes/ByteArray construction

- make.ps1
Useful to see at a glance for a long run whether anything has failed that is already off-screen.
> Report failed test jobs during a test run

- Src/StdLib/Lib/test/support/__init__.py
The `test.support.reap_threads` method takes a snapshot of known threads and then after the test complets it does repeated `gc.collect` calls until the until the threads created by the test are cleaned up.
Since our threads run in a .NET thread, it may not be a thread know to the `threading` module when the snapshot is taken. Because of this the `gc.collect` loop only ends after 100 iterations. This modification ensures that the current thread is present in the snapshot and so the loop ends.
> Resolve test_smtplib failures

- Src/IronPython.Modules/hashlib/MD5CryptoServiceProvider.cs
- Src/IronPython.Modules/hashlib/SHA1CryptoServiceProvider.cs
- Src/IronPython.Modules/hashlib/SHA224.cs
- Src/IronPython.Modules/hashlib/SHA256Managed.cs
- Src/IronPython.Modules/hashlib/SHA384Managed.cs
- Src/IronPython.Modules/hashlib/SHA512Managed.cs
- Src/IronPython.Modules/hashlib/SHAConstants.cs
- Src/IronPython.Modules/hashlib/_hashlib.cs
- Src/IronPython.Modules/hashlib/_md5.cs
- Src/IronPython.Modules/hashlib/_sha1.cs
- Src/IronPython.Modules/hashlib/_sha256.cs
- Src/IronPython.Modules/hashlib/_sha512.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
.NET Core does not use managed implementations for its hashing algorithms. Because of this the `copy` methods were failing. This brings in managed implementations for the algorithms from Mono (https://github.com/mono/mono/tree/mono-4.0.5.1/mcs/class/corlib/System.Security.Cryptography)
> Fix hashlib copy on .NET Core

- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/Operations/IntOps.cs
Resolves #955, that is, the debug mode tests pass and the error message for `int.from_bytes("abc", 'big')` is aligned with CPython.
It does not resolve the underlying issue, for which I have created a separate issue report (#957).
> Prevent using str type arg in int.from_bytes

- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonEncoding.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Tests/modules/io_related/test_codecs.py
- Tests/test_codeccallbacks_stdlib.py
- Tests/test_codecs.py
This is the decoding counterpart of #914 and #941. Apart from consolidating the code and preparing for incremental decoding support (in file i/o), a direct functional benefit is that custom decoding error handlers are now allowed to provide surrogate code points.
It also eliminates almost all data copy steps when using `PythonEncoding`, the only one remaining I am aware of is when using `(raw-)unicode-escape` encoding with a custom error handler. I consider this an infrequent scenario, besides, the input will usually not be very large. Also, in such usage there are more inefficiencies at play (e.g. the input data is processed thrice rather than once). Because of this and since this encoding is notorious for difficulties of fitting into the .NET encoding framework, I am inclined to leave …
> Support custom decoding error handler

- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPythonTest/EngineTest.cs
- Tests/encoded_files/cp20472.py
- WhatsNewInPython30.md
This is the last bit of the work to use UTF-8 as default source encoding that I am aware of.
The test for encoding used by `ScriptEngine` was already in place (disabled) but it wasn't testing the right thing. I went to the [CodePlex archive](https://archive.codeplex.com/?p=ironpython) to look up the original report 20472 (_Issue with non-unicode script file encoding_) and fixed the test to test for that.
One caveat: if the user uses `CreateScriptSourceFromFile(file, System.Text.Encoding.Default)`, UTF-8 will be used rather than `Encoding.Default` which on .NET Framework is the active Windows code page. Perhaps this is OK, since the IronPython 3 default **is** UTF-8. If this is not right, the solution might be to modify `Microsoft.Scripting.Utils.StringUtils.DefaultEncoding` to use a clone …
> Use UTF-8 as default with ScriptEngine

- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/test_bytes.py
- Tests/test_str.py
This also aligns error types and warnings with CPython's.
> Eliminate data copy when calling str() on a bytes-like object

- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/Operations/IntOps.cs
- Tests/test_bytes.py
- Tests/test_memoryview.py
Fixes:
```python
class BytesBytesSubclass(bytes):
def __bytes__(self):
return BytesBytesSubclass(b"xyz")
assert int.from_bytes(BytesBytesSubclass(b"abc"), 'big') == int.from_bytes(b"xyz", 'big')
```
Also:
```python
assert int.from_bytes(memoryview(b"abc")[::2], 'big') == int.from_bytes(b"ac", 'big')
```
> Make int.from_bytes recognize __bytes__ in all cases

- Src/IronPython/Runtime/Operations/FloatOps.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
As a bonus: one data copy less.
> Replace BytesLikeAttribute usage with IBufferProtocol in FloatOps

- Src/IronPython.Modules/binascii.cs
- Src/IronPython.Modules/zlib/ZlibModule.cs
- Src/IronPython/Runtime/BufferProtocol.cs
Here is an example where `PythonIndexAttribute` would be quite useful, and on a different type than `int`. The `crc` parameter for `binascii.crc32`, (and `value` parameter for `zlib.crc32`) honours `__index__` and accepts any integer value, but for any value not fitting in `UInt32`, the value is masked, i.e. the 32 least significant bits are taken and interpreted as unsigned. I suspect something similar for `zlib.adler32`, though I haven't tesed it. In general, I suspect honouring `__index__` is quite widespread and the error handling differences can be clamping, masking, `OverflowError`, `ValueError`.
----
`zlib.crc32` seems to do the same as `binascii.crc32` so I assume it is OK for it to return `object` as well?
----
It can be risky to convert `IBufferProtocol` to `IList` in a general …
> Use IBufferProtocol in zlib

- Src/IronPython.Modules/_warnings.cs
- Src/IronPython/Hosting/PythonOptionsParser.cs
- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPython/Runtime/PythonOptions.cs
So in the end I did not implement support for `-bbb`, `-bbbb` and the like. They are nowhere documented and I wonder if anybody is using this in the wild. Anyway, since `PythonOptions.BytesWarning` is an int-backed enum now, it should be fairly easy to add such support in the future, if the need arises.
> Complete support of commandline options -b and -bb

- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
`IronPython.modules.system_related.test_nt` uses fixed file, directory, and environment variable names.
> Disable parallel execution for test_nt

- Src/IronPython.Modules/bz2/BZ2Compressor.cs
- Src/IronPython.Modules/bz2/BZ2Decompressor.cs
- Src/IronPython.Modules/bz2/BZ2Module.cs
- Src/IronPython.Modules/zlib/Compress.cs
- Src/IronPython.Modules/zlib/Decompress.cs
`BZ2Compress.cs` and `BZ2Decompress.cs` are small could be merged into `BZ2Module.cs` (which is practically empty), but I suppose are kept separate to keep the same structure as of `zlib`.
> Use IBufferProtocol in compressors and decompressors

- Src/IronPython/Runtime/PythonContext.cs
- Src/StdLib/Lib/base64.py
Calling flush on the standard file stream is the same approach CPython uses. Resolves https://github.com/IronLanguages/ironpython3/issues/791. Also related to https://github.com/IronLanguages/ironpython3/issues/938.
@jameslan
> Flush std files on shutdown

- Tests/interop/net/method/test_arguments.py
Matches IronLanguages/dlr#247.
Tests marked with `# msg` may need a review. I think the messages are correct, but a different message (from a different angle) would also be acceptable.
Labels `!!!` or `FIXME` indicate unexpected or erroneous behaviour.
`TODO` means more tests needed.
> Update test_arguments to match DLR

- Src/IronPython/Runtime/BufferProtocol.cs
The assertion was too restrictive.
> Fix assertion for IsCContiguous test on IPythonBuffer

- Src/IronPython/Lib/iptest/ipunittest.py
- Tests/test_missing.py
This is instead marking `test_dynamic_regressions` `NotParallelSafe`. Probably helps in other places too.
> Use separate test directories per framework

- Src/IronPython/Hosting/PythonOptionsParser.cs
- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPython/Runtime/PythonOptions.cs
I often find myself disabling the importlib bootstrapping when debugging, this adds an options to do it without having to amend the code.
> Add command line argument to disable importlib bootstrapping

- Tests/interop/net/method/test_arguments.py
- Tests/test_dlrkwarg.py
- Tests/test_function.py
Matches IronLanguages/dlr#250.
> Update tests to expect no binding by keyword to *args/**kwargs

- Src/IronPython/Runtime/Types/DocBuilder.cs
Fixes:
```
>>> import System
>>> help(System.Math.Exp)
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\_sitebuiltins.py", line 103, in __call__
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 1843, in __call__
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 1876, in help
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 1630, in doc
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 1623, in render_doc
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 373, in document
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 1364, in docroutine
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 90, in getdoc
File …
```
> Fix __doc__ string processing

- .github/workflows/main.yml
- Build/steps.yml
- Package/nuget/IronPython.StdLib.nuspec
- Package/nuget/IronPython.nuspec
- make.ps1
Rollout of 16.8 on CI images has started so see if it works.
> Re-enable packaging

- Src/IronPython/Runtime/Types/DocBuilder.cs
- Src/IronPython/Runtime/Types/DynamicHelpers.cs
- Src/IronPython/Runtime/Types/PythonType.cs
Fixes:
```
>>> import System
>>> help(System.Reflection.CustomAttributeExtensions.GetCustomAttribute)
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\_sitebuiltins.py", line 103, in __call__
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 1843, in __call__
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 1876, in help
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 1630, in doc
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 1623, in render_doc
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 373, in document
File "C:\Code\ironlang\ironpython3\Src\StdLib\Lib\pydoc.py", line 1364, in docroutine
File …
```
> Handle generic parameter types as return types of builtins in DocBuilder

- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Src/StdLib/Lib/urllib/request.py
Workaround for https://github.com/IronLanguages/ironpython3/issues/1050
> Bypass _scproxy import on macOS

- Src/IronPython/Runtime/Importer.cs
- Tests/import_extant/_vendor/packaging/_structures.py
- Tests/import_extant/_vendor/packaging/version.py
- Tests/import_extant/extern/__init__.py
- Tests/test_importext.py
Resolves #936.
I still want to add tests.
> Use qualified module name from import statement during importing

- Src/IronPython/Compiler/Ast/Comprehension.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
`[lambda: i for i in [1,2]]` should bind the `i` correctly now.
> Fix binding freevars in comprehension scope

- Src/IronPython/Compiler/Ast/Comprehension.cs
- Src/IronPython/Compiler/Ast/PythonAst.cs
- Src/IronPython/Compiler/Ast/PythonNameBinder.cs
- Src/IronPythonTest/EngineTest.cs
- Src/StdLib/Lib/sre_compile.py
- Tests/test_closure.py
Resolves #817.
Redesigning the inheritance hierarchy would have been a more elegant solution, but that perhaps for another time.
Credit for the tests to the work/discussion done under #1073.
@slozier @isaiah
> Support rewriting of comprehension scopes

- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
Part of https://github.com/IronLanguages/ironpython3/issues/489. I believe the issue was fixed with https://github.com/IronLanguages/ironpython3/pull/1083.
> Remove IsolationLevel on test_dictcomp and test_setcomp

- Src/IronPython.Modules/_datetime.cs
- Src/IronPython.Modules/time.cs
- Src/StdLib/Lib/test/test_nntplib.py
- Tests/modules/system_related/test_time.py
The `assertRaises` started failing with the change of year. Related to https://github.com/IronLanguages/main/issues/239
Also patches `test_nntplib`. See https://bugs.python.org/issue42794
> Fix test_time

- Src/IronPython.Modules/_datetime.cs
- Src/IronPython/Modules/_locale.cs
- Src/IronPython/Runtime/Binding/PythonBinder.cs
- Src/IronPython/Runtime/ByteArray.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/Operations/DecimalOps.cs
- Src/IronPython/Runtime/Operations/InstanceOps.cs
- Src/IronPython/Runtime/Operations/IntOps.Generated.cs
- Src/IronPython/Runtime/Operations/LongOps.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonFunction.cs
- Src/IronPython/Runtime/Types/BuiltinFunction.cs
- Src/IronPython/Runtime/Types/DocBuilder.cs
- Src/IronPython/Runtime/Types/PythonType.cs
- Src/IronPython/Runtime/Types/PythonTypeInfo.cs
- Src/Scripts/generate_alltypes.py
also does some cleanup of `__cmp__`.
> Add rich comparison operators to number types

- Src/IronPython.Modules/_ctypes/_ctypes.cs
- Src/IronPython.Modules/nt.cs
- Src/IronPython/Modules/_ast.cs
- Src/IronPython/Runtime/Operations/IntOps.cs
- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPython/Runtime/PythonFunction.cs
- Src/IronPython/Runtime/Types/PythonType.cs
- Src/StdLib/Lib/test/test_builtin.py
- Tests/gen_stdlib_test.py
- Tests/test_functools_stdlib.py
- Tests/test_isinstance.py
Some misc changes for 3.5. Also adds `__qualname__` to `function` and `type` (part of https://github.com/IronLanguages/ironpython3/issues/30)
Just for the sake of clarity, these are the changes that are 3.5 specific:
- `_ast.AsyncFunctionDef` (which is just a stub)
- `pow(-1, -2, 3)` throws a `ValueError` instead of a `TypeError`
Everything else should be applicable to 3.4.
> Misc changes

- Src/Scripts/test_cgcheck.py
Resolves #902. `generate_indicetest` is blocked as it doesn't have a main function and breaks `test_main()`.
> Generate list of generators in test_cgcheck

- Src/IronPython/Modules/unicodedata.cs
- Src/IronPython/Runtime/LiteralParser.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1114
> Add namereplace error handler

- Src/IronPython/Compiler/Ast/FunctionDefinition.cs
- Src/IronPython/Compiler/Ast/PythonAst.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Compiler/PythonCompilerOptions.cs
- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Runtime/CompileFlags.cs
- Src/IronPython/Runtime/FunctionAttributes.cs
- Src/IronPython/Runtime/Generator.cs
- Src/IronPython/Runtime/ModuleOptions.cs
- Src/StdLib/Lib/__future__.py
- Src/StdLib/Lib/test/test_pep479.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1116. Tests and changes to the stdlib are from CPython 3.5.
> Add generator_stop

- Src/IronPython/Compiler/Ast/Comprehension.cs
> Fix debug assertion in ComprehensionScope.GetParentClosureTuple

- Src/IronPython/Compiler/Ast/ScopeStatement.cs
- Tests/test_nonlocal.py
The existing code was already skipping the global scope when resolving nonlocal references, but failed to account for global variables introduced into local scopes with the `global` statement.
> Prevent nonlocal binding to global variables

- Src/IronPython/Compiler/Ast/AstMethods.cs
- Src/IronPython/Compiler/Ast/DictionaryExpression.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Tests/test_unpack.py
Part of https://github.com/IronLanguages/ironpython3/issues/100
> Add dict unpacking

- Src/IronPython/Compiler/Ast/AstMethods.cs
- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Src/IronPython/Compiler/Ast/NameExpression.cs
- Src/IronPython/Compiler/Ast/ScopeStatement.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Tests/test_class.py
- Tests/test_namebinding.py
- Tests/test_scope_stdlib.py
Resolves #1030.
The original bug got fixed in CPython 3.4 ([bpo-17853](https://bugs.python.org/issue17853)) because of an interesting metaclass scenario. I tried to add that scenario to the IronPython tests, but it fails, presumably because [PEP 3115](https://www.python.org/dev/peps/pep-3115/) is not implemented yet? Are the old-style metaclasses supposed to work?
> Prefer local class namespace over lexical scoping

- Src/IronPython/Compiler/Ast/PythonAst.cs
- Src/IronPython/Compiler/Ast/StarredExpression.cs
- Src/IronPython/Compiler/Parser.cs
Moves the starred expression checks out of parser which resolves the following:
```Python
import ast
try:
ast.parse("*a")
except SyntaxError:
assert False
```
> Move starred expression checks out of parser

- Src/IronPython/Compiler/Ast/AstMethods.cs
- Src/IronPython/Compiler/Ast/Expression.cs
- Src/IronPython/Compiler/Ast/ListExpression.cs
- Src/IronPython/Compiler/Ast/SequenceExpression.cs
- Src/IronPython/Compiler/Ast/SetExpression.cs
- Src/IronPython/Compiler/Ast/StarredExpression.cs
- Src/IronPython/Compiler/Ast/TupleExpression.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/StdLib/Lib/test/test_unpack_ex.py
- Tests/test_unpack.py
Part of https://github.com/IronLanguages/ironpython3/issues/100
> Unpack sequences

- Src/IronPython/Compiler/Ast/Arg.cs
- Src/IronPython/Compiler/Ast/AstMethods.cs
- Src/IronPython/Compiler/Ast/CallExpression.cs
- Src/IronPython/Compiler/Ast/DictionaryExpression.cs
- Src/IronPython/Compiler/Ast/SetExpression.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Modules/_ast.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/StdLib/Lib/test/test_grammar.py
- Src/StdLib/Lib/test/test_unpack_ex.py
Resolves https://github.com/IronLanguages/ironpython3/issues/100. Brings in test_unpack_ex from CPython 3.5 as well as some changes from test_grammar.
> Unpack function arguments

- Src/IronPython/Compiler/Ast/CallExpression.cs
- Src/IronPython/Compiler/Ast/PythonNameBinder.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Modules/_ast.cs
Code refactoring of `CallExpression`.
It came up when I was looking into keyword arguments for metaclasses (#1163), which most likely will have an impact on `CallExpression` as it is now. So before starting with metaclasses, I wanted to get this one out of the way, since it brings a public interface change.
> Separate positional and keyword arguments in CallExpression

- Src/IronPython/Compiler/Ast/AstMethods.cs
- Src/IronPython/Compiler/Ast/CallExpression.cs
- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Src/IronPython/Compiler/Ast/FlowChecker.cs
- Src/IronPython/Compiler/Ast/PythonNameBinder.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Modules/_ast.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Tests/test_class.py
@slozier I know you are not a huge fan of `Compiler.Ast.Arg`, but the reason I changed the type of `ClassDefinition.Bases` from a ro list of `Expression` to a ro list of `Arg` is to align it more closely with `CallExpression`. [PEP 3115](https://www.python.org/dev/peps/pep-3115/) specifically declares that:
> the parameter list passed to a class definition will now support all of the features of a function call
so ideally this should be handled by the same code path as a function call. Indeed, this is what I think CPython does with routing class creation with a call to the internal `__build_class__` function. 
I looked first at implementing it here too, but eventually decided not to go ahead with such approach. The way how arguments are handled in `CallExpression` is tailored to what the …
> Support starred arguments as class bases

- Src/IronPython/Modules/_ast.cs
- Tests/test_ast.py
Fixes the `ast` side of https://github.com/IronLanguages/ironpython3/pull/1152 https://github.com/IronLanguages/ironpython3/pull/1153 https://github.com/IronLanguages/ironpython3/pull/1170
> Update AST for extended unpacking

- Src/IronPython/Compiler/Ast/CallExpression.cs
- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Src/IronPython/Compiler/Ast/Expression.cs
- Src/IronPython/Compiler/Ast/FlowChecker.cs
- Src/IronPython/Compiler/Ast/IndexExpression.cs
- Src/IronPython/Compiler/Ast/Keyword.cs
- Src/IronPython/Compiler/Ast/ListExpression.cs
- Src/IronPython/Compiler/Ast/Node.cs
- Src/IronPython/Compiler/Ast/PythonNameBinder.cs
- Src/IronPython/Compiler/Ast/PythonWalker.Generated.cs
- Src/IronPython/Compiler/Ast/SequenceExpression.cs
- Src/IronPython/Compiler/Ast/SetExpression.cs
- Src/IronPython/Compiler/Ast/StarredExpression.cs
- Src/IronPython/Compiler/Ast/TupleExpression.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Modules/_ast.cs
- Src/Scripts/generate_calls.py
Gets rid of the annoying (to me) `Arg` construct. :smile:
@BCSharp if you have any feedback. Not sure if this will creates merge conflicts with your PR.
> Remove IronPython.Compiler.Ast.Arg

- README.md
Hello,
Top level statements were introduced in C# with .NET 5.  
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/top-level-statements
For the comparison to be fair, I think the readme should use this.
> Updated C# snippet in the README.md to use top level statements.

- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Src/StdLib/Lib/mimetypes.py
Changes to the standard library should be reverted once https://github.com/IronLanguages/ironpython3/issues/1182 is resolved.
> Avoid StackOverflowException in mimetypes

- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/Types/PythonType.cs
- Tests/test_metaclass.py
It addresses a part of the problem reported in #1154 (duplicate calls to `__prepare__`) and several other related issues. Off the top of my head:
* removes duplicate calls to `__init__`
* supports inheriting of `__prepare__`, `__new__`, `__init__` by metaclasses
* supports `__prepare__` on a function used as "metaclass"
* fixes interplay when mixing metaclasses provided classes and functions in various scenarios
* ...
> Improve metaclass logic

- Src/IronPython/Modules/sys.cs
- Src/StdLib/Lib/test/test_builtin.py
- Src/StdLib/Lib/test/test_codecs.py
- Tests/test_builtinfunc.py
- Tests/test_nonlocal.py
Using `0xffff` for `sys.maxunicode` is probably more accurate since our implementation of unicode is closer that of CPython 3.2.
Some Python code uses this value to check if they can use "wide" characters, for example, from `docutils`:
```Python
if sys.maxunicode >= 0x10FFFF: # "wide" build
delimiters += '\U00010100\U00010101\U0001039f\U000103d0\U00010857'
```
Another example from `pyyaml`:
```Python
has_ucs4 = sys.maxunicode > 0xffff
```
In both these modules, we end up with errors about "invalid" character ranges in a regular expressions:
```Python
re.compile("[\U00010000-\U0010ffff]")
```
> re.error: parsing "[-]" - [x-y] range in reverse order.
> Change sys.maxunicode to 0xffff

- Src/IronPython/Runtime/Types/PythonType.cs
- Tests/test_metaclass.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1208
> Fix setter on metaclass

- Src/IronPython.Modules/_collections.cs
Adds `copy`, `index`, `insert`, `__contains__`, `__add__` and `__mul__` to `deque`.
> Add methods to deque

- Src/IronPython/Runtime/Operations/PythonOps.cs
- Tests/test_builtin_stdlib.py
- Tests/test_metaclass.py
Resolves:
```py
class test(type):
def __repr__(self):
return "A"
class test2(metaclass=test):
pass
assert repr(test2) == "A"
```
which was causing a failure in the `typing` tests.
> Fix repr of metaclass

- Src/IronPython/Compiler/Parser.cs
We don't actually support it so better to fail with a syntax error...
Also "fixes" the following check that `jinja2` does:
```py
exec('async def _():\n async for _ in ():\n  yield _')
```
which fails with a `NullReferenceException` because `async for` isn't implemented.
> Report syntax error on async def

- Src/IronPython.Modules/zipimport.cs
- Tests/test_zipimport.py
Resolves the following:
````py
assert str(zipimport.ZipImportError("test")) == "test"
````
which was throwing a `TypeError`.
> Fix str of ZipImportError

- Src/IronPython.Modules/ModuleOps.cs
- Src/IronPython.Modules/_ctypes/Array.cs
- Src/IronPython.Modules/_ctypes/ArrayType.cs
- Src/IronPython.Modules/_ctypes/MemoryHolder.cs
- Src/IronPython.Modules/_ctypes/SimpleCData.cs
- Src/IronPython.Modules/_ctypes/_ctypes.cs
- Src/IronPython.Modules/nt.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
There are a bunch of tests that broke in the transition from ipy2 (mostly due to str/unicode changes). This re-enables some of them.
> Enable some ctypes tests

- .github/workflows/main.yml
- .vsts-ci.yml
- make.ps1
Reverts some changes from https://github.com/IronLanguages/ironpython3/pull/1095 once CI upgrades to VS 2022.
> Don't use VS prerelease

- Build/After.targets
- Build/net5.0-windows.props
- Build/net6.0-windows.props
- Directory.Build.props
Fixes intermittent build failures of _IronPython.Wpf_ and _IronPython.SQLite_ when parallel builds are enabled with multiple target frameworks.
> Separate intermediate item directories for .NET 5 and 6 builds

- Src/IronPython/Runtime/PythonOptions.cs
Resolves https://github.com/IronLanguages/ironpython3/issues/1313
Sample usage:
```c#
var engine = Python.CreateEngine(new Dictionary<string, object> { {"NoImportLib", true } });
```
> Allow NoImportLib in release mode

- Src/IronPythonConsole/IronPythonConsole.csproj
- Src/IronPythonTest/IronPythonTest.csproj
.NET Core 2.1 is end of life but is used to test .NET Standard 2.0 assemblies.
> Disable warning about using end-of-life .NET Core 2.1

- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
This test creates temporary fixed-name modules.
> Disable parallel execution of test_traceback

- Src/StdLib/Lib/numbers.py
- Src/StdLib/Lib/pickle.py
- Src/StdLib/Lib/test/test_long.py
Follow-up on #1329 (issue #52).
> Revert workarounds in StdLib for Issue #52

- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Tests/modules/system_related/test__locale.py
- Tests/test_stdmodules.py
- Tests/test_str.py
- Tests/test_strformat.py
Prevents bogus test failures in subsequent tests under some circumstances (e.g. locale "en_CA" and .NET 6.0).
> Restore locale after testing

- Src/IronPython.Modules/time.cs
- Tests/modules/system_related/test__locale.py
- Tests/test_stdmodules.py
- Tests/test_strformat.py
Fun fact: since .NET 5.0, AM/PM in Canada becomes a.m./p.m. CPython doesn't buy it.
> Fix strptime

- Src/IronPython/Runtime/Operations/CharOps.cs
- Tests/test_str.py
For some reasons, `System.Char` was lacking constructors. It made it convoluted to create instances of this type:
```pycon
>>> from System import Char, IConvertible
>>> Char()
TypeError: Char() takes at least 2147483647 arguments (0 given)
>>> Char(65)
TypeError: cannot create instances of Char
>>> IConvertible.ToChar(65, None)   
A
>>> type(IConvertible.ToChar(65, None))
<class 'Char'>
```
The constructors bring `Char` more in line with other .NET primitive value types:
```pycon
>>> from System import Char
>>> Char('A')
A
>>> Char(65)
A
```
> Define constructors for System.Char

- Src/IronPython/Runtime/Operations/BigIntegerOps.cs
- Tests/test_ironmath.py
Follow-up on #1347 and https://github.com/IronLanguages/ironpython3/pull/1329 (issue https://github.com/IronLanguages/ironpython3/issues/52).
Special point of interest: `op_Division`.
> Remove obsolete BigIntegerV2 API from BigIntegerOps

- Src/IronPython/Runtime/Binding/PythonBinder.cs
This brings `Int32` more in line with other primitive .NET integral types and `int` itself.
> Relegate Int32 to non-Python-type level

- Src/IronPython/Runtime/Exceptions/SystemExitException.cs
This mimics CPython on Windows, when run directly from the shell prompt or with `os.system`. However, `test_stdconsole` fails when run under CPython because `os.spawnv` throws `OSError` when the process returns a negative value, rather than passing it as the return value (IronPython's `os.spawnv` passes it through, maybe a bug?). 
The story is different on Linux/maxOS. Here exit codes are always unsigned byte size and the lowest 8 bits from the `exit` argument, if it fits in 64 bits. Otherwise, CPython returns 255, (which is what -1 translates to). So to achieve CPython compatibility on Unix, `SystemExitException.GetExitCode`should return -1 only `if (b > long.MaxValue || b < long.MinValue)`, (maybe the story is different on 32-bit systems, I don't have any), otherwise just return the …
> Fix sys.exit() with large negative exit code

- Src/IronPython/Runtime/ClrModule.cs
Now that all enums are serialized correctly, `clr.Serialize` can serialize `Int32` efficiently.
> Serialize Int32 directly

- Src/IronPython/Runtime/Operations/BigIntegerOps.cs
- Tests/test_ironmath.py
Follow-up on https://github.com/IronLanguages/ironpython3/pull/1347 and https://github.com/IronLanguages/ironpython3/pull/1329 (issue https://github.com/IronLanguages/ironpython3/issues/52).
> Finish IConvertible members in BigIntegerOps

- Src/IronPython/Runtime/Operations/BigIntegerOps.cs
- Tests/test_ironmath.py
Follow-up on https://github.com/IronLanguages/ironpython3/pull/1347 and https://github.com/IronLanguages/ironpython3/pull/1329 (issue https://github.com/IronLanguages/ironpython3/issues/52).
> Support large enums in int constructor

- Src/IronPython.Modules/_ssl.cs
- Tests/modules/network_related/test__ssl.py
Part of https://github.com/IronLanguages/ironpython3/issues/1162
> Add _ssl.MemoryBIO

- Src/IronPython/Runtime/Operations/IntOps.Generated.cs
- Src/Scripts/generate_alltypes.py
- Tests/test_cliclass.py
This makes the overflow handling in the integer constructors internally consistent and in line with the binder.
> Check for overflow in integer constructors

- Src/IronPython.Modules/_struct.cs
- Tests/test_regressions.py
- Tests/test_struct_stdlib.py
> Use __index__ if needed to pack integer values in struct

- Src/IronPython/Runtime/Binding/ConversionBinder.cs
- Src/IronPython/Runtime/Operations/BigIntegerOps.cs
- Src/IronPython/Runtime/Operations/ComplexOps.cs
- Src/IronPython/Runtime/Operations/FloatOps.cs
- Src/IronPython/Runtime/Types/PythonTypeInfo.cs
- Tests/test_complex.py
- Tests/test_complex_stdlib.py
A thought: move `TryToFloat` to `PythonOps`?
> Fix complex.__new__

- Src/IronPython.Modules/_ssl.cs
Resolves https://github.com/IronLanguages/ironpython3/issues/1305
> Use CopyWithPrivateKey

- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Runtime/Operations/BigIntegerOps.cs
- Src/IronPython/Runtime/Operations/IntOps.Generated.cs
- Src/IronPython/Runtime/Operations/IntOps.cs
- Src/Scripts/generate_alltypes.py
Follow-up on #1347 and https://github.com/IronLanguages/ironpython3/pull/1329 (issue https://github.com/IronLanguages/ironpython3/issues/52).
There are many changes in this PR but most of them is just reordering of methods in `IntOps` and `BigIntegerOps` to align them with the order in `IntOps.Generated.cs`. Makes browsing, comparing, and reviewing easier.
From the functional changes:
* in `IntOps`:
* `__abs__` removed (was erroneous)
* `__float__` removed (was redundant)
* in `BigIntegerOps`, to align with the other numeric Ops:
* `__pos__` renamed `Plus` (although actually it is redundant)
* `__abs__` renamed `Abs` (could have been internal)
There are possibly more redundant methods or methods that could have been internal, but I am not going to hunt them down.
> Cleanup IntOps

- Src/IronPython/Runtime/LiteralParser.cs
- Tests/test_complex.py
- Tests/test_complex_stdlib.py
Noticed this while reviewing https://github.com/IronLanguages/ironpython3/pull/1385
> Don't overflow on complex constructor

- Src/IronPython/Runtime/Operations/BigIntegerOps.cs
- Src/IronPython/Runtime/Operations/IntOps.Generated.cs
- Src/IronPython/Runtime/Operations/IntOps.cs
- Src/Scripts/generate_alltypes.py
- Tests/test_int.py
Normally I would not add a Python-specific method to a non-Python type (except for dunder methods), but this method can be quite useful on integral types.
> Implement to_bytes for all integer types

- Src/IronPython/Lib/iptest/test_env.py
- Src/IronPython/Runtime/Operations/IntOps.cs
- Tests/test_cliclass.py
- Tests/test_int.py
Instances of `Int32` behave as if being instances of an anonymous subtype of `int`. Therefore, for the sake of type system consistency, any attributes of `int` should be also present on instances of both `int` and `Int32`. This was already the case for regular Python attributes, but not for Python-hidden attributes. This PR sets it straight. Arguably, there is little chance that the static attributes are going to be accessed through an instance rather than the type, but here they are to avoid surprises. Who knows, maybe some code-generating use case assumes that it is possible, as it should be.
Ideally I would like to see those Python-hidden properties and …
> Mimic BigInteger members on Int32

- Src/IronPython.Modules/_csv.cs
- Src/IronPython/Runtime/Binding/MetaUserObject.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/PythonList.cs
- Src/IronPythonTest/EngineTest.cs
Since `__long__` is gone, to avoid confusion, `XxxConvertToLong` is renamed to `XxxConvertToInt`, while the old `XxxConvertToInt` is gone. Plus some cleanup. A couple of functional changes are fixes:
* If `__int__` returns a `BigInteger` instance, a conversion call site with return type `Int32` succeeds or throws `OverflowException` if the value does not fit in 32 bits. Previously it was always throwing `TypeErrorException` with a rather cryptic message: `__int__ returned non-int (int)`, regardless of the value.
* If `__complex__` returns non-complex, `TypeErrorException` with a proper message is returned `__complex__ returned non-complex (xxx)` rather than …
> Rename ConvertToLong to ConvertToInt

- Src/IronPython.Modules/ModuleOps.cs
- Src/IronPython.Modules/_ctypes/Array.cs
- Src/IronPython.Modules/_ctypes/ArrayType.cs
- Src/IronPython.Modules/_ctypes/CData.cs
- Src/IronPython.Modules/_ctypes/CFuncPtr.cs
- Src/IronPython.Modules/_ctypes/Field.cs
- Src/IronPython.Modules/_ctypes/Pointer.cs
- Src/IronPython.Modules/_ctypes/PointerType.cs
- Src/IronPython.Modules/_ctypes/SimpleCData.cs
- Src/IronPython.Modules/_ctypes/SimpleType.cs
- Src/IronPython.Modules/_ctypes/StructType.cs
- Src/IronPython.Modules/_ctypes/Structure.cs
- Src/IronPython.Modules/_ctypes/Union.cs
- Src/IronPython.Modules/_ctypes/UnionType.cs
- Src/IronPython.Modules/_ctypes/_ctypes.cs
Prepares ground for #1297.
It is a simple, not-functional change but because of the rename it touches many places so I submit it as a separate PR to keep subsequent PRs small (hopefully).
> Convert internal field CData._memHolder to property CData.MemHolder

- Src/IronPython.Modules/_ctypes/ArrayType.cs
- Src/IronPython.Modules/_ctypes/MemoryHolder.cs
- Src/IronPython.Modules/_ctypes/SimpleType.cs
- Src/IronPython.Modules/_ctypes/StructType.cs
- Src/IronPython.Modules/_ctypes/_ctypes.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Tests/test_ctypes_frombuffer_stdlib.py
Part of https://github.com/IronLanguages/ironpython3/issues/1404
> Update from_buffer_copy to accept an IBufferProtocol

- Src/IronPython/Runtime/Operations/BoolOps.cs
- Src/IronPython/Runtime/Operations/IntOps.Generated.cs
- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Src/Scripts/generate_alltypes.py
- Tests/test_complex.py
- Tests/test_numtypes.py
It looks like this test has never been run on IronPython 3 before — it was still using Python 2 syntax. After upgrading, it exposed some gaps in the operators on the non-Python integers.
I am torn between enabling and not enabling this test by default. It was originally disabled because it "takes way too long". Indeed, it takes about 30 seconds on my rig, which I think means it can be some extra 3 minutes on the CI server. In the end I enabled it because I have some resolver-related tinkering planned ahead and would prefer the test to catch as much mistakes as possible.
> Enable test_numtypes

- Documentation/upgrading-from-ipy2.md
> Update notes on upgrading from ipy2 to cover PEP 237

- Build/After.targets
- CurrentVersion.props
- Package/choco/IronPython.nuspec
- Package/msi/Dlr.wxs
- Package/msi/IronPython.Installer.wixproj
- Package/msi/IronPython.wxs
- Package/msi/Product.wxs
- Package/nuget/IronPython.nuspec
- Package/zip/Zip.Packaging.targets
- README.md
- Src/IronPython/Hosting/PythonConsoleOptions.cs
- Src/IronPython/Hosting/PythonOptionsParser.cs
- Src/IronPython/Modules/sys.cs
- Src/IronPython/Runtime/Implementation.cs
- Src/IronPythonConsole/Console.cs
- Tests/test_stdconsole.py
Things left to do for the release:
@BCSharp Any potential PRs you'd like to squeeze in before a release? Can you think of anything else?
> Version 3.4.0-beta

- Src/Scripts/Install-IronPython.ps1
This is meant to bridge the install functionality till we have `dotnet tool` supported. I originally tried to have a script that can install ItonPyton/.NET 6 from just the zipfile packaged by the `package` target, but it turned out that the content of it is not sufficient (esp. on Unix). So the script now pulls additional binaries from the `bin` directory. Ugly, as there is no guarantee  thatthey are in sync. Perhaps a better option would have been to create an additional build target, say `install`, that installs a standalone IronPython runtime in a designated location, but at the moment, this script is sufficient for me. Now I can start testing out my favourite Python packages under IronPython 😃
> Add Install-IronPython.ps1

- Src/IronPython.Modules/_ctypes/Field.cs
- Src/IronPython.Modules/_ctypes/SimpleType.cs
- Src/IronPython.Modules/_ctypes/Structure.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Tests/gen_stdlib_test.py
- Tests/modules/type_related/test_bitfields_ctypes_stdlib.py
- Tests/modules/type_related/test_ctypes.py
Addressed #1439 and a few other issues that caught my attention. The most interesting is a fix for python/cpython#90914, which was reported just 3 months ago and is still not resolved. Funny thought that IronPython on one point will be ahead of CPython. Not that this functionality is used anywhere in the wild, since it is not working yet in CPython.
> Improve handling of bitfields in ctypes

- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Tests/test_str.py
I was hoping this would go away in some new version of CPython, but it's still here in 3.10.
> Support str subclass from repr

- Src/IronPython/Runtime/Converter.cs
This is probably just marginal performance improvement but since the cache is already there, let's use it fully.
> Use type cache in Converter where applicable

- Tests/modules/network_related/test__ssl.py
This replaces www.microsoft.com with www.python.org as the site used for the SSl tests. It will hopefully stop the intermittent `test__ssl` failures during CI. 
The failures were in `test_SSLType_read_and_write` during an attempt to read. At first I thought this might be a bug in the implementation of `_ssl` but it turned out that CPython exhibits the same behaviour (i.e. hangs indefinitely). My best guess now is that www.microsoft.com deploys some sophisticated anti-bot defences that hinder the automatic test. www.python.org seems to respond just fine, even during a repeated test run.
> Use www.python.org for testing _ssl

- Src/Scripts/Enter-IronPythonEnvironment.ps1
Some packages (e.g. `sympy`) install tools in this location on Posix systems.
> Add bin subdir to path on entering IronPython environment

- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Modules/_io.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Tests/test_builtinfunc.py
CPython also accepts any buffer protocol aware object but with a deprecation warning starting from 3.7, so I think it is more an implementation artifact slated for removal than a legitimate use case. I also haven't met such usage in real life (unlike bytes, which are being passed).
> Accept bytes as filename arg to compile

- Src/IronPython/Runtime/Binding/PythonProtocol.Operations.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/PythonList.cs
- Tests/test_regressions.py
This resolves https://github.com/IronLanguages/ironpython3/issues/1475. The patch is not actually correct but it "fixes" the more common scenario. See https://github.com/IronLanguages/ironpython3/issues/560 for details on the remaining issues.
> Workaround for issue with concat and radd

- Src/IronPython.SQLite/Cursor.cs
- Src/IronPython.SQLite/c#sqlite/os_win_c.cs
- Src/IronPython.SQLite/c#sqlite/pager_c.cs
> Support sqlite3 on Linux

- Tests/test_inheritance.py
Hi,
This pull request is a fix to a potential bug about wrong order of function arguments at `Tests/test_inheritance.py`. Please check the changes.
Best,
Jingxuan
> Fix a bug about wrong order of function arguments

- Src/IronPython.Modules/resource.cs
- Src/IronPython/Runtime/PlatformsAttribute.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Tests/modules/system_related/test_resource.py
- Tests/modules/system_related/test_resource_stdlib.py
Module `resource` is Posix-only. The implementation here is fairly complete as far as I know, except for a small incompatibility when attempting to increase a maximum limit while not being a superuser. CPython raises `ValueError` while this implementation raises `OSError`. I think CPython's choice is a mistake. A `ValueError` is supposed to indicate an invalid value, something that the caller should be able to prevent from happening with proper value checks and preconditions. For instance, trying to set a a pair of limits where _current_ is higher than _maximum_ is a legitimate `ValueError`. But to decide whether the caller is or is not allowed to raise the maximum is the domain of the OS. Some lightweight OS implementations may allow it in some circumstances or for some users. Therefore …
> Implement module resource

- Src/IronPython.Modules/_csv.cs
- Src/IronPython.Modules/_functools.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/PythonContext.cs
- Src/StdLib/Lib/types.py
- Tests/modules/type_related/test_types.py
- Tests/test_functools_stdlib.py
The following hello world example is failing:
```py
import jedi
script = jedi.Script(print('Hello World!')
completions = script.complete(1, 3)
```
The failure appears to be caused by `types.MemberDescriptorType` being `<class 'getset_descriptor'>` instead of `<class 'member_descriptor'>`.
In the initial report (by @SebastianBolte on gitter) the sample was run in a hosted scenario and failing with a `TypeError: object of 'NoneType' has no len()`:
```cs
var engine = Python.CreateEngine();
engine.SetSearchPaths(seachPaths);
engine.Execute(@"
import jedi
script = jedi.Script(print('Hello World!')
completions = script.complete(1, 3)
");
```
This is because `sys.executable` is `None` by default. The solution to this is to set its value with `engine.SetHostVariables`. For example:
```cs …
```
> Resolve failure with jedi module

- Src/IronPython.Modules/nt.cs
- Src/IronPython/Interop/Windows/Ucrtbase/Interop.strerror.cs
- Tests/modules/system_related/test_os.py
Besides producing correct error message on Linux and macOS, the main benefit is the elimination of the switch on constants from `PythonErrorNumber`. The values in module `errno` vary depending on OS so cannot be implemented as constants.
On Windows, P/Invoke calls into _ucrtbase_, which may not be available on Windows 7 by default. I don't know if IronPython is still supposed to support Windows 7, if so, the the WIX installer may have to install _msvcrt_ on that system.
This PR also contains a few small fixes of `Mono.Unix` usage (ref. https://github.com/IronLanguages/ironpython3/pull/1490#issuecomment-1157003535)
On a side note: I'm wondering if it wouldn't be cleaner to factor module `posix` out of `nt` (and putting common functionality in an additional static class, e.g. `PythonOS`).
> Use P/Invoke for os.strerror

- Src/StdLib/Lib/multiprocessing/managers.py
There is a small typo in Src/StdLib/Lib/multiprocessing/managers.py.
Should read `identify` rather than `indentify`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, indentify -> identify

- Src/IronPython/Runtime/FormattingHelper.cs
- Src/IronPython/Runtime/NewStringFormatter.cs
- Src/IronPython/Runtime/Operations/BigIntegerOps.cs
- Src/IronPython/Runtime/Operations/FloatOps.cs
- Src/IronPython/Runtime/Operations/IntOps.cs
- Src/IronPython/Runtime/Operations/StringOps.cs
- Src/IronPython/Runtime/StringFormatSpec.cs
- Tests/test_strformat.py
Dispatches the float formatting to `DoubleOps` and resolves some formatting issues, for example:
```py
import System
assert format(-1111, "08,d") == format((-1111).ToBigInteger(), "08,d")
```
Prep work for PEP 515 https://github.com/IronLanguages/ironpython3/issues/105.
> Formatting cleanup

- Src/IronPython.Modules/_ssl.cs
- Tests/test_ssl_stdlib.py
Since I do have IPv6 connectivity, I decided to look into `test_get_server_certificate_ipv6` that is being skipped on CI but fails locally.
The good new is that my solution I tried during #1507 turned out to be the right way, despite causing now some other tests (that were previously failing) to hang indefinitely. The change unblocked those tests to advance and hit another, unrelated problem.
The bad news is that I had to comment them out to let the whole test suite pass, rather than have them as _expected failure_. I also think I got to the root cause of the problem: creating a socket using a descriptor of another existing socket resets the timeout of the existing socket to default (infinite by default). This is because creating a socket around an existing descriptor does not actually …
> Make IPv6 SSL test passing

- Build.proj
- Package/choco/IronPython.nuspec
- Package/deb/Deb.Packaging.targets
- Package/msi/IronPython.Installer.wixproj
- Package/nuget/IronPython.StdLib.nuspec
- Package/pkg/Pkg.Packaging.targets
- Package/zip/Zip.Packaging.targets
- Src/IronPython/Hosting/PythonCommandLine.cs
- Src/IronPython/IronPython.csproj
- Src/IronPython/Runtime/PythonContext.cs
- Src/Scripts/Install-IronPython.ps1
- Src/StdLib/StdLib.pyproj
Resolves #1471 using CPython approach, except that StdLib from NuGet always uses lowercase (i.e. incl. on Windows).
> Use lowercase lib for StdLib dir name on non-Windows systems

- Src/StdLib/Lib/test/test_functools.py
Hi,
This pull request is a fix to a potential variable misuse bug at `Src/StdLib/Lib/test/test_functools.py`. Please check the changes.
Best,
Jingxuan
> Fix a potential variable misuse bug

- Src/IronPython/Runtime/Operations/PythonOps.cs
- Tests/test_class.py
Part of #20.
`test__ssl` fails but not fixing here since a fix is already in the pipeline of #1516.
> DeprecationWarning on failed __classcell__ propagation

- Src/IronPython/Runtime/Binding/MetaPythonFunction.cs
- Src/IronPython/Runtime/PythonFunction.cs
- Tests/modules/network_related/test__ssl.py
- Tests/test_regressions.py
Resolves an invalid `TypeError` when defining/calling certain functions. See https://github.com/IronLanguages/ironpython3/issues/1515 for details.
---
Grammar failure occurs when run after `test_function`:
> .\make.ps1 -f net462 test-"IronPython.test_function|test_grammar_stdlib"
Failure appears to be (note that this only works with CPython 3.7+ since older versions don't accept > 255 arguments):
```py
size = 257
d = {}
exec('def f(' + ','.join(f'a{i}' for i in range(size)) + '): pass', d)
exec('f(*(' + ', '.join(map(str, range(size))) + '))', d)
def d01(a=1): pass
d01(*(1,))
```
Broke in https://github.com/IronLanguages/ironpython3/pull/447
_Originally posted by @slozier in https://github.com/IronLanguages/ironpython3/issues/1515#issuecomment-1191722994_
> Fix function compatibility

- Src/IronPython/Runtime/FormattingHelper.cs
- Src/IronPython/Runtime/Operations/BigIntegerOps.cs
- Src/IronPython/Runtime/Operations/IntOps.cs
- Src/IronPython/Runtime/StringFormatSpec.cs
- Src/IronPython/Runtime/StringFormatter.cs
- Tests/test_long_stdlib.py
- Tests/test_strformat.py
Part of https://github.com/IronLanguages/ironpython3/issues/105
> Add underscore formatting for types dxob

- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Src/IronPython/Compiler/Ast/ScopeStatement.cs
- Src/IronPython/Compiler/Ast/VariableKind.cs
- Tests/test_metaclass.py
- Tests/test_super.py
Part of #20.
Because it effectively changes the name lookup mechanism in a class body lambda, I was curious what performance impact this may have. The old mechanism uses `RuntimeVariableDictionaryStorage`, which is backed by a fixed length array and a linear lookup. In the new code, only `__class__` goes there, all other variables are stored in `CommonDictionaryStorage`, which grows dynamically.  Since the new mechanism is only required for classes created by user metaclasses, it is possible to fall back on the old mechanism if no metaclass is specified, thus maintaining the existing performance profile in most cases.
Intuitively, the old mechanism should be better for small (few methods) classes, while the new approach should outperform for very large classes. But the question was where …
> Use CommonDictionaryStorage for class variables

- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Tests/test_class_stdlib.py
Unfortunately, one test is not passing (#1530), which necessitates `test_class_stdlib`.
3.6 adds two more tests to `test_class`, both pass.
> Enable some tests from test_class in StdLib

- Src/IronPython/Compiler/Ast/AstMethods.cs
- Src/IronPython/Compiler/Ast/CallExpression.cs
- Src/IronPython/Compiler/Ast/FunctionDefinition.cs
- Src/IronPython/Compiler/Ast/Parameter.cs
- Src/IronPython/Compiler/Ast/PythonNameBinder.cs
- Src/IronPython/Compiler/Ast/PythonReference.cs
- Src/IronPython/Compiler/Ast/ScopeStatement.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/RuntimeVariablesDictionaryStorage.cs
- Src/IronPython/Runtime/Super.cs
- Tests/test_inheritance.py
- Tests/test_super.py
It started when I looked into why `super()` generates `NameError`/`UnboundLocalError` while in CPython it is `RuntimeError` (tested for by StdLib). It turns out that the CPython's implementation hence behaviour is different in some corner cases. Specifically, 0-argument `super()` does not have default arguments `__class__` and `self` injected during compilation, but resolved during runtime. One of the consequences is that `__class__` is always resolved to a class cell rather than whatever the namebinder finds in the local scope.
As far as I can see, these are truly obscure cases that would lead to IronPython/CPython differences and almost always bad Python programming, but it was an interesting exercise and you never know what other consequences might be there.
For what I know, most …
> Resolve obscure super errors

- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
Fully resolves #1250.
I have enabled `test_super` from StdLib, but 3.6 adds more tests there, of which one (`test___class___mro`) fails with: _NotImplementedError: Overriding type.mro is not implemented_. Other new tests related to `__class__` pass.
> Handle __class__ pathologies

- Src/IronPython/Compiler/Ast/AstMethods.cs
- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Src/IronPython/Compiler/Ast/ScopeStatement.cs
- Src/IronPython/Runtime/CommonDictionaryStorage.cs
- Src/IronPython/Runtime/CustomDictionaryStorage.cs
- Src/IronPython/Runtime/FunctionCode.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/RuntimeVariablesDictionaryStorage.cs
- Tests/modules/system_related/test_sys_getframe.py
Part of #20.
The "outer context" is basically a local context but created outside of the class lambda. I call it "class context" rather than "local context" because, strictly speaking, the class lambda still creates its own local context inside. The content of both class and local contexts is the same, except that the latter contains the `__class__` variable, if present. I kept the creation of the local context like this since the machinery to handle it is in `ScopeStatement`, which servers all scope-creating constructs: class, function, comprehensions, generators, and AST root, so it was easier to implement it this way. Besides, having a separate context without `__class__` may be useful, I remember in the past having to filter `__class__` out explicitly on some occasions. Perhaps this …
> Execute class body lambda in outer context

- Src/IronPython/Runtime/StringDictionaryStorage.cs
- Src/IronPython/Runtime/Types/CustomInstanceDictionaryStorage.cs
- Tests/test_function.py
Also fixes handling of entries with null or empty string keys.
Frankly, I struggle to see any benefit of `StringDictionaryStorage` over e.g. `CommonDictionaryStorage`. The one thing that `StringDictionaryStorage` does better is the fast test `HasNonStringAttributes`, but since the keys have to be enumerated anyway to match keyword arguments to parameter names, any check against non-strings could be done at that moment, with no extra cost. This is how CPython handles it, I believe.
Perhaps `Dictionary<string, object?>` is faster than the buckets of `CommonDictionaryStorage`. If so, I wonder if `ConcurrentDictionary<string, object?>` wouldn't be even better, but I haven't done any performance measurements. All theses implementations do not preserve order, but order preservation is needed …
> Enable nullable annotations in StringDictionaryStorage

- Src/IronPython/Runtime/Descriptors.cs
- Tests/test_property.py
A subclass of `property` with `__slots__` can lead to an unexpected `AttributeError`. For example:
```py
def getter(x): pass
class MyProperty(property):
__slots__ = ()
def __init__(self, getter, doc):
property.__init__(self, getter, doc=doc)
MyProperty(getter, "").__doc__
```
was raising:
> AttributeError: MyProperty object has no \_\_doc\_\_ attribute
Ran into this while trying to get the `google-cloud-storage` package working (note that it's failing on import even with the fix).
> Fix AttributeError when subclassing property

- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Src/IronPython/Compiler/Ast/ScopeStatement.cs
- Tests/test_namebinding.py
Handles the `nonlocal` part from #1560, making IronPython's behaviour again inconsistent with CPython.
> Resolve explicit nonlocals in class lexically

- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Src/IronPython/Compiler/Ast/Comprehension.cs
- Src/IronPython/Compiler/Ast/FunctionDefinition.cs
- Src/IronPython/Compiler/Ast/Node.cs
- Src/IronPython/Compiler/Ast/PythonNameBinder.cs
- Src/IronPython/Compiler/Ast/ScopeStatement.cs
- Src/IronPython/Compiler/Ast/TryStatement.cs
Point of interest: `Node.Parent`.
This property is initialized to `null` upon construction and stays `null` up to the beginning of the first namebinding phase. So technically its type is nullable (may be null). However, it is used a lot during and after namebinding and during namebinding it is guaranteed to be non-null by `PythonNameBinder`, while it should not be accessed at all beforehand. So a non-nullable type is a better fit. This is what I chose then with some guards around it.
One caveat: previously, the was one exception the rule above: the root node (`PythonAst`) had `Parent` set to `null` at all times. I've changed this so that the root node is its own parent. This makes the nullability of the property consistent with other node types and allows safe and well defined meaning of …
> Enable nullable annotations in Ast.Node

- Src/IronPython/Compiler/Ast/YieldFromExpression.cs
- Src/StdLib/Lib/heapq.py
- Src/StdLib/Lib/xml/etree/ElementPath.py
Resolves https://github.com/IronLanguages/ironpython3/issues/547 by using mangled names. Still not a proper yield from implementation but should at least avoid name conflicts with iter/next/sys.
> Don't use sys/next/iter in yield from AST

- Documentation/differences-from-c-python.md
> Remove int/long section from "Differences frm CPython"

- Src/IronPython/Runtime/LiteralParser.cs
- Src/IronPython/Runtime/Operations/BigIntegerOps.cs
Span-ify integer parsing to make it easier to handle underscores in integer literals. Part of https://github.com/IronLanguages/ironpython3/issues/105
> Span-ify integer parsing

- Build/Tasks.Targets
This is somewhat related to #1472.
When the packaging target created a zip archive, the entries in the zip file had no file permissions set. As a result, unzipping the archive leaves behind a bunch of files that are not readable on Posix systems (until `chmod -R +r` at least).
Note that directories are created with proper permissions because they are not stored in the zip archive but are being created by the unzipping process.
In this PR, zip archive entries are created with the expected `rw-r--r--` permissions, except for `*.sh` and `*.ps1` files, which are supposed to be executable. The permissions are not read from the staged files because they don't exist on Windows (except for the _Archive_ flag, which I haven't bothered dealing with).
> Set Unix file permissions in zip files

- Build/After.targets
- Package/deb/Deb.Packaging.targets
- Package/dotnettool/IronPython.Console.csproj
- Package/pkg/Pkg.Packaging.targets
- Package/zip/Zip.Packaging.targets
- Src/IronPythonTest/IronPythonTest.csproj
This is staging directory cleanup. There is no reason to stage anything from IronPythonTest and then pollute the packaging targets with explicit exclusions.
> Do not stage IronPythonTest products

- Build.proj
This makes the zip archive usable on all supported platforms and systems.
The size of the archive is increased by 5 MB. Apparently no file-deduplication takes place. If we want deduplication, I suppose this would need to be manually handled by hacking the "Zip" task snippet. It would save ca. 2.5 MB. Frankly, I don't think it is worth the effort.
> Stage Mono.Unix

- Package/choco/IronPython.nuspec
- Package/choco/README.md
- Package/nuget/README.md
I forgot this one when preparing #1580. 
I haven't removed the "obsolete" nuspec metadata, because the declaration of their obsolescence was for _NuGet_, maybe _Chocolatey_ still uses them.
The `README.md` is now aligned with the .NET tool, rather than the GitHub project frontpage .
> Clean up choco packaging project

- Build/Tasks.Targets
- Package/dotnettool/README.md
- Package/nuget/README.md
- Package/zip/README.md
- Package/zip/Zip.Packaging.targets
Since the content is zip-file specific, it is being sourced from `Package/zip`, rather than the staging directory (similarly to the _NuGet_ packages). `Package/$(Configuration)/Stage/README.md`, which is a copy of the `README.md` in the project root directory, is, AFACS, now only used by the _MSI_ package.
> Provide README for zip package

- Src/IronPythonConsole/App.config
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
The `AppContextSwitchOverrides` for path handling is no longer relevant now that we target .NET 4.6.2.
> Remove app.config

- Package/zip/README.md
- Package/zip/Zip.Packaging.targets
- Src/Scripts/Install-IronPython.ps1
`Install-IronPython` now can facilitate installation from within the zip file.
`Enter-IronPythonEnvironment` is also being distributed in the zip file.
> Update Install-IronPython and pack in zipfile

- .github/workflows/main.yml
- .vsts-ci.yml
- Src/StdLib/Lib/importlib/_bootstrap.py
Avoid exceptions when loading importlib. While the exceptions are normally caught, not having them occur in the first place makes for a more pleasant debugging experience. Related to https://github.com/IronLanguages/ironpython3/issues/1590
> Avoid exceptions when loading importlib

- Src/Scripts/Install-IronPython.ps1
This used to work when tested on Windows, but now was failing on macOS. Differences in Powershell versions?...
> Fix unzipping 'lib' directory

- Documentation/upgrading-from-ipy2.md
Adds a note about `None` becoming a keyword which seems like a fairly common issue. Also want to add something about `SetOutput` which has come up a number of times (https://github.com/IronLanguages/ironpython3/issues/1204).
> Add to 2 to 3 upgrade guide

- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Tests/test_regressions.py
- Tests/test_regressions_compiled.py
Resolves issue raised in https://github.com/IronLanguages/ironpython3/pull/1601#issuecomment-1336308322.
> Fix class __doc__ type

- Src/IronPython.Modules/_ctypes/NativeFunctions.cs
Resolves #1595. If the tests pass, maybe it can sneak into the 3.4.0 release?
> Use libc iso libdl on newer glibc versions

- Src/IronPython.Modules/select.cs
- Src/IronPython/Runtime/Operations/IntOps.cs
- Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1614 and https://github.com/IronLanguages/ironpython3/issues/1615
> Fix some assertion errors

- Src/IronPython/Compiler/Tokenizer.cs
- Src/IronPython/Runtime/LiteralParser.cs
- Src/IronPython/Runtime/Operations/FloatOps.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
Part of https://github.com/IronLanguages/ironpython3/issues/105
> Allow underscores in integer literals

- Src/IronPython.Modules/_socket.cs
- Src/StdLib/Lib/test/test_socket.py
- Tests/test_socket_stdlib.py
This adds the expected `fileno` parameter handling for the `socket.socket` class (See #1507). It now throws the expected errors before creating the socket instance.
It also backports tests for the `fileno` parameter from Python 3.11. `os_helper` and `socket_helper` get shimmed by classes with the used attributes from the respective module file if they cannot be imported.
Closes #1509
> Fix fileno parameter handling for socket class

- Documentation/differences-from-c-python.md
- Documentation/getting-the-sources.md
- Documentation/installing.md
- Documentation/modifying-the-sources.md
- Documentation/upgrading-from-ipy2.md
Style:
installing.md - Line 21: Changed "a.k.a." to "AKA" to match Line 126: "AKA"
getting-the-sources.md - Line 18: "website" becomes "web URL". Arguably a grammar change, as the website literal is github.com, and this sentence is referring to a particular URL on github.
modifying-the-sources.md - Line 17: Added a period for consistency with other sentences in the list.
Grammar:
installing.md - Line 11: Moved term "already" before "has" for correctness.
installing.md - Line 21: Changed "have been" to "be", since the sentence is making a present suggestion, rather than a past assumption.
differences-from-c-python.md - Line 161: "CPython's" becomes "CPython"
differences-from-c-python.md - Line 173: "IronPython's" becomes "IronPython"
differences-from-c-python.md - Line 183: Added word …
> Docs Grammar Spelling Consistency

- Src/IronPython/Runtime/Binding/PythonExtensionBinder.cs
- Src/IronPython/Runtime/ExtensionMethodSet.cs
- Tests/test_cliclass.py
Resolves https://github.com/IronLanguages/ironpython2/issues/810
> Don't list extension methods multiple times

- Src/IronPython/Runtime/PythonContext.cs
Loading a module with `ModuleOptions.Optimized` makes it uncollectable and so `importlib` ends up keeping all imported modules alive. Might resolve https://github.com/IronLanguages/ironpython3/issues/1658...
> Don't use Optimized when loading importlib

- Src/IronPython.Modules/_winapi.cs
- Tests/modules/network_related/test__ssl.py
Resolves an issue reported on gitter by @danabr:
> Hi. I have a mysterious issue with subprocess.Popen with stdout=subprocess.PIPE. It works fine from the IronPython console, and also when I run IronPython2 embedded in my application. However, when I use embedded IronPython3, I get: `OSError: [WinError 6] The handle is invalid`. Here is a stacktrace:
>
> ```
> File "myscript.py", line 137, in main
>     p = subprocess.Popen(commands, shell=True, stdout=subprocess.PIPE)
>   File "lib\subprocess.py", line 833, in __init__
>     (p2cread, p2cwrite,
>   File "lib\subprocess.py", line 1033, in _get_handles
>     p2cread = self._make_inheritable(p2cread)
>   File "lib\subprocess.py", line 1080, in _make_inheritable
>     h = _winapi.DuplicateHandle(
> ```
>
>The issue only occurs when I the …
> return None instead of 0 in GetStdHandle

- Src/IronPython/Hosting/PythonOptionsParser.cs
- Src/StdLib/Lib/site.py
Removes PYTHONVERBOSE from the cli help (since it doesn't do anything). Use of flags.verbose in site.py is from 3.6.
Related to https://github.com/IronLanguages/ironpython3/issues/1694
> Remove PYTHONVERBOSE from help

- Src/IronPython.Modules/msvcrt.cs
This module is not meant to be used on Linux/macOS.
> Make msvcrt Windows-only

- Src/IronPython/Modules/_fileio.cs
- Tests/test_file.py
Handles `open("nonexistent", 'ab+')`
> Create file if nonexistent with open mode 'ab+'

- Src/IronPython.Modules/nt.cs
- Tests/modules/io_related/test_fd.py
- Tests/modules/system_related/test_nt.py
`NUL` file is now `stat`-able. The special handling of `/dev/null` is removed since this system file is supported by the OS and can be treated like any other file.
> Improve handling of NUL file on Windows

- Src/IronPython.Modules/nt.cs
- Tests/modules/io_related/test_fd.py
Resolves problems when `stat` would fail if the current directory was changed after file opening.
> Use absolute file name for stat

- Src/IronPython/Runtime/Operations/PythonOps.cs
This change makes IronPython 3 buildable without `FEATURE_FULL_CONSOLE` (except for `IronPythonConsole` and `IronPythonWindow`). Such a build behaves properly in LinqPad without a need for stdio redirecting (i.e. like IronPython 2).
> Enable PythonOps.PrintException on basic console builds

- Src/IronPython.Modules/nt.cs
- Src/IronPython/Modules/_fileio.cs
- Tests/modules/io_related/test_fd.py
Now that I know where to look for `closefd`… This addresses https://github.com/IronLanguages/ironpython3/pull/1711#issuecomment-1636935329.
It is still not exactly like CPython, because it will prevent closing of the descriptors even when redirected but perhaps this is good enough. I cannot imagine when this would be desirable, but there isn't a valid use case. Anyway, note that a determined programmer may still force close a standard descriptor by `os.close(fd)`. This is likely not a good idea anyway since it will crash the CPython process on any attempt to use stdio, and those descriptors cannot be reopened.
> Prevent closing of standard descriptors through file objects

- Documentation/upgrading-from-ipy2.md
- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPython/Runtime/PythonOptions.cs
This option is only available for embedding scenarios. There is no corresponding command switch since `ipy` always uses `Full` console support level.
I wonder how to make this option more discoverable.
> Add option ConsoleSupportLevel

- Src/IronPython.Modules/mmap.cs
- Src/IronPython.Modules/msvcrt.cs
- Src/IronPython.Modules/nt.cs
- Src/IronPython/Modules/_fileio.cs
- Src/IronPython/Modules/_io.cs
- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPython/Runtime/PythonFileManager.cs
- Tests/modules/io_related/test_fd.py
This is the second pass of redesign of `PythonFileManager` and `FileIO`. There should be no functional changes (except for some small increase in compatibility with CPython). Basically, a part of `FileIO` has been factored out into `StreamBox`. This has several benefits:
* It simplifies the API of `PythonFileManager`, which now contains only one type of objects and the API becomes strongly typed. The callers do not need to wrestle with downcasting and having different code paths for different type object, which was not done consistently. Indeed, in some places, only one type of objects was handled.
* `StreamBox`, unlike `FileIO`, is not disposable and does not have a finalizer. This should reduce the pressure on the GC, esp. when files are opened using the `PyhonNT` API. 
* It sets the …
> Redesign PythonFileManager

- Src/IronPython/Runtime/PythonOptions.cs
A convenience update that allows for something like:
```C#
var engine = Python.CreateEngine(new Dictionary<string, object> {
{ "ConsoleSupportLevel", "Basic" },
});
```
This brings enums more in line with other option types, since it was already possible to use strings as values of other options:
```C#
var engine = Python.CreateEngine(new Dictionary<string, object> {
{ "RecursionLimit", "10000" }
});
```
I was wondering whether it should not better go into the DLR. Also, I was considering making the enum parsing case-insensitive, but didn't do it because the option names themselves are case-sensitive.
> Implement conversions to enum options

- Src/IronPython.Modules/nt.cs
- Src/IronPython/Modules/_fileio.cs
- Src/IronPython/Runtime/BufferProtocol.cs
- Src/IronPython/Runtime/PythonFileManager.cs
This PR is intended to improve performance on .NET Framework and Mono. .NET (Core), with its `Span`-aware API does not have those performance issues. The main use case is `bytearray` as the buffer. AFAICS, this addition should cover all built-in types plus .NET types, except for `array.array`.
The unsafe `IPythoBuffer` helpers will do their best to extract the underlying CLI-array, to avoid a data copy or the wicked loop spin (see https://github.com/IronLanguages/ironpython3/pull/1729#discussion_r1299501437). This code path may perhaps be not the most popular one, but I thought I saw "opportunities" like this in other places too. At least this will serve as a sample solution.
> Performance improvements of reading and writing through StreamBox

- Src/IronPython.Modules/IterTools.cs
- Src/IronPython.Modules/_ssl.cs
- Src/IronPython.Modules/grp.cs
- Src/IronPython.Modules/xxsubtype.cs
- Src/IronPython.SQLite/Cursor.cs
- Src/IronPython/Modules/Builtin.cs
- Src/IronPython/Modules/_ast.cs
- Src/IronPython/Runtime/Binding/ConversionBinder.cs
- Src/IronPython/Runtime/Binding/MetaPythonFunction.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/ClrModule.cs
- Src/IronPython/Runtime/Enumerate.cs
- Src/IronPython/Runtime/Operations/InstanceOps.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
- Src/IronPython/Runtime/PythonContext.cs
- Src/IronPython/Runtime/PythonList.cs
- Src/IronPython/Runtime/Set.cs
- Src/IronPython/Runtime/Types/PythonType.cs
Partially addresses #1718 (when the wrapping type is `list`).
> Use actual code context for enumerating

- Src/IronPython.Modules/_datetime.cs
- Tests/test_datetime.py
Expecting timestamp to roundtrip:
```py
d = datetime.datetime(2000,1,1)
assert datetime.datetime.fromtimestamp(d.timestamp()) == d
```
> Fix issue with timestamp timezone

- Src/StdLib/Lib/subprocess.py
- Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1135. Thanks @danabr !
> Fix issue with subprocess.Popen not producing any output

- .github/workflows/main.yml
- Src/IronPython/Modules/_io.cs
- Src/IronPython/Runtime/Bytes.cs
- Src/IronPython/Runtime/PythonList.cs
- Src/IronPython/Runtime/Types/NewTypeMaker.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Src/IronPythonTest/Cases/CaseGenerator.cs
- Src/IronPythonTest/Cases/IronPythonCasesManifest.ini
- Src/IronPythonTest/Stress/Engine.cs
- Tests/test_io_stdlib.py
- make.ps1
Also enables some test_io tests and fixes an issue with .NET 9.
> Performance improvement on BufferedReader.seek

- Directory.Build.props
- Src/IronPython.Modules/_ctypes/_ctypes.cs
- Src/IronPython.Modules/_struct.cs
- Src/IronPython.Modules/re.cs
- Src/StdLib/Lib/test/test_struct.py
- Tests/test_struct_stdlib.py
Improves performance on struct.unpack and fixes some failing tests.
Also removes array overloads which are covered by the buffer protocol.
> Improve performance on struct.unpack

- Directory.Build.props
- Package/msi/Version.wxi
- Src/IronPython/Modules/sys.cs
Hi there (again)!
I noticed that the .NET Foundation copyright was missing from some source files and instead showed "IronPython Team", which isn't the official licenseholder specified in the LICENSE file in the root directory.
This is a small fix to change that to the .NET Foundation.
> Code Quality: Update source to show .NET Foundation copyright

- Src/IronPython/Runtime/Operations/ArrayOps.cs
- Tests/test_array.py
This is one of several changes I have stashed since several years ago that never got to the top of the priority list because the functionality looked so fringe or insignificant. I am submitting them now, before the code restructuring tsunami hits.
One of the oddities of .NET is support of arbitrary-based arrays. They are clumsy to create and use, esp. in strongly typed languages, but there they are. Support of them in IronPython is somewhat unfinished, probably for good reason, since it is such a fringe concept, and perhaps never used in anything serious.
Since two arrays with identical content but different bases (lower bounds) are **not** the same, their `repr` string should be different. This PR adds the display of the base in case it is non-zero.
> Display array base when nonzero

- Src/IronPython.Modules/_thread.cs
- Src/IronPython/Compiler/Ast/ClassDefinition.cs
- Src/IronPython/Compiler/Ast/FunctionDefinition.cs
- Src/IronPython/Compiler/Ast/ScopeStatement.cs
- Src/IronPython/Compiler/Parser.cs
- Src/IronPython/Runtime/Binding/WarningInfo.cs
- Src/IronPython/Runtime/BuiltinPythonModule.cs
- Src/IronPython/Runtime/Converter.cs
- Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
- Src/IronPython/Runtime/FunctionCode.cs
- Src/IronPython/Runtime/ModuleDictionaryStorage.cs
- Src/IronPython/Runtime/Operations/ArrayOps.cs
- Src/IronPython/Runtime/Operations/InstanceOps.cs
- Src/IronPython/Runtime/Operations/PythonTypeOps.cs
- Src/IronPython/Runtime/Operations/TypeGroupOps.cs
- Src/IronPython/Runtime/PythonFunction.cs
- Src/IronPython/Runtime/PythonList.cs
- Src/IronPython/Runtime/Types/NewTypeMaker.cs
- Src/IronPython/Runtime/Types/ParameterInfoWrapper.cs
- Src/IronPython/Runtime/Types/PythonType.cs
- Src/IronPython/Runtime/Types/ReflectedExtensionProperty.cs
- Src/IronPython/Runtime/Types/ReflectedProperty.cs
Gets rid of uses of `ArrayUtils.EmptyObjects` and `ArrayUtils.EmptyStrings`. Uses the C# 12 empty collection expression `[]` as a replacement. Ultimate goal is to try and remove dependencies on DLR utils (like `ArrayUtils`) so they can be obsoleted (less code to worry about).
> Get rid of ArrayUtils.EmptyObjects

- Src/IronPython/Runtime/Operations/ArrayOps.cs
- Tests/test_array.py
Fixes `IndexOutOfRangeException` when equating arrays with different index bases (lower bounds).
Example:
```pycon
>>> from System import *
>>> a = Array.CreateInstance(Int32, (5,), (1,))
>>> b = Array.CreateInstance(Int32, (5,), (1,))
>>> a == b
IndexError: Index was outside the bounds of the array.
>>> a != b
IndexError: Index was outside the bounds of the array.
```
This is due to a bug in .NET:
```c#
var a = Array.CreateInstance(typeof(int), new[] { 5 }, new[] { 1 });
var b = Array.CreateInstance(typeof(int), new[] { 5 }, new[] { 1 });
((IStructuralEquatable)a).Equals(b, EqualityComparer<int>.Default);  // IndexOutOfRangeException
```
I'll see …
> Implement equality comparisons on System.Array

- Src/IronPython/Runtime/Operations/ArrayOps.cs
- Tests/test_array.py
Currently IronPython ignores the lowerbound of a CLI array and always treats the array as 0-based. Assume `arr` is a 1-based 2x2 matrix. Using `SetValue` or `GetValue` requires using 1-based indices, but when using subscripts all indices are must be shifted down by 1. This is not .NET-compliant.
```python
from System import *
arr = Array.CreateInstance(str, (2,2), (1,1))
arr.SetValue("a_1,1", Array[Int32]((1,1)))
arr.SetValue("a_1,2", Array[Int32]((1,2)))
arr.SetValue("a_2,1", Array[Int32]((2,1)))
arr.SetValue("a_2,2", Array[Int32]((2,2)))
arr[0, 0] = "a_1,1"
arr[0, 1] = "a_1,2"
arr[1, 0] = "a_2,1"
arr[1, 1] = "a_2,2"
```
After this PR:
```python
arr.SetValue("a_1,1", Array[Int32]((1,1)))
arr.SetValue("a_1,2", Array[Int32]((1,2)))
arr.SetValue("a_2,1", Array[Int32]((2,1))) …
```
> Fix indexing for arrays with non-zero base

- Src/IronPython/Runtime/Operations/ArrayOps.cs
- Tests/test_array.py
This aligns the error raised (exception thrown) with `memoryview`.
> Correct error raised when slicing CLI arrays

- Src/IronPython/SystemRuntimeVersioning.cs
I had added `UnsupportedOSPlatformAttribute` in the past already several times, only to remove it again when the final version submitted as a pull request didn't use it. Now again, I have code that uses it, although it is not the final version so in the end it may again not be using it. Nevertheless, I'd like to add this attribute and get it over with for the future. It doesn't harm if it's unused, but it is good to have it available, if needed.
> Define UnsupportedOSPlatformAttribute

- Src/IronPython/Runtime/Operations/ArrayOps.cs
- Tests/test_array.py
Generally, the `repr` string in Python can be evaluated by `eval`, providing a round-trip-complete string representation of an object. There are exceptions, like deeply nested or circular structures, or nondescript "object type at memory address".
For CLI arrays, representations of 1D arrays are descriptive, while higher dim are not. This PR adds a constructor that is able to handle the representation for 1D arrays with a non-zero base. I'd make the extra parameter keyword-only, but the DLR doesn't support it yet.
> Implement System.Array constructor with base arg

- Src/IronPython/Runtime/Operations/ArrayOps.cs
- Tests/test_array.py
Fixes issue reported by @slozier in https://github.com/IronLanguages/ironpython3/pull/1828#pullrequestreview-2480173778:
> Unrelated to this PR, but noticed a slight asymmetry in `FixSlice` where it does `ostart < lb` vs `ostop < 0`. Don't think it hurts anything but seemed odd.
The problem was happening in some cases for arrays with base >= 2 and a negative slice step.
```pycon
>>> from System import *
>>> arr = Array.CreateInstance(Int32, (3,), (2,))       
>>> arr[-1:-5:-1]
IndexError: Index was outside the bounds of the array.
```
> Fix downward slices for positive base arrays

- Documentation/file-descriptors.md
- Src/IronPython.Modules/nt.cs
- Src/IronPython/Modules/_fileio.cs
- Src/IronPython/Runtime/PythonFileManager.cs
- Tests/modules/io_related/test_fd.py
- Tests/test_file.py
Up until now, file descriptors provided by the Python API (e.g `f.fileno()`) were emulated, that is, they were "fake". This was necessary on Windows, since .NET does not run on top of the C library, but on POSIX systems, at the low level, the genuine file descriptors are used. This PR exposes those genuine file descriptors on the Python API level, making path for a set of POSIX-specific modules, like `fcntl` and `termios`.
I thought that Mono would give me the most problems, because of the [limitation of the `FileStream` constructor](https://github.com/mono/mono/issues/12783), but in the end, it was .NET: it does not share the read/write pointer with duplicated descriptors. I have implemented a workaround (details in the new developer's documentation file), but I am not happy with it. The …
> Use genuine file descriptors on Posix

- Src/IronPython/Compiler/Ast/FunctionDefinition.cs
- Src/IronPython/Runtime/Binding/MetaPythonFunction.cs
- Src/IronPython/Runtime/Operations/PythonOps.cs
Resolves https://github.com/IronLanguages/ironpython3/issues/1518
> Improve performance in argument unpacking

- Src/IronPython.Modules/nt.cs
- Src/IronPython/Modules/_fileio.cs
- Src/IronPython/Runtime/PythonFileManager.cs
- Tests/modules/system_related/test_os.py
I think I understand now why IronPython uses sometimes two streams for accessing one file. I may be wrong, but this is what I think is the case:
1. CPython was build on libc, which supports various file opening modes according to POSIX. `O_APPEND | O_CREAT | O_RDWR` is one of them, tagged as mode `ab+`.
2. .NET Framework was build on Win32, which does **not** support file mode `Append` with read access.
3. When CPython is ported to Win32, it uses MSVCRT, which emulates `Append` with R/W by opening with a regular `Open` and then seeking to the end before every write. This is functionally the same as on POSIX but non-atomic, so it may lead to data loss in some circumstances.
4. When .NET was re-developed on POSIX, it maintained the limitation from Win32 of not supporting R/W with `Append`, …
> Support mode `ab+` equivalent through os.open

- Package/dotnettool/IronPython.Console.csproj
- Package/dotnettool/runtimeconfig.template.json
Since .NET 6 is no longer supported...
> Bump dotnet tool to .NET 8

- Src/IronPython/Modules/_fileio.cs
- Src/IronPython/Runtime/PythonFileManager.cs
- Src/Scripts/generate_os_codes.py
- Tests/test_file.py
Mainly with Mono, which does not accept negative seek positions relative to current position, throwing an overflow exception instead.
> Fix file seek errors

- Src/IronPython.Modules/math.cs
- Tests/modules/misc/test_math.py
Adjusts the `math.degrees` conversion to match CPython.
> Adjust math.degrees to match CPython

- Tests/modules/type_related/test_ctypes.py
- Tests/test_descr_stdlib.py
- Tests/test_io_stdlib.py
- Tests/test_memoryio_stdlib.py
- Tests/test_namebinding.py
Since I changed to a faster macOS machine, these tests are failing on Mono.
There are still two more tests failing (`test__ssl` and, yup, `test__socket`…), but I haven't investigated them yet. They seem to have a different type of issues than `gc.collect()`.
> Disable tests in Mono depending on gc.collect()

- Src/IronPython/Modules/_fileio.cs
- Src/IronPython/Modules/_io.cs
- Src/Scripts/generate_os_codes.py
- Tests/test_file.py
Includes part of the solution for #1225.
> Complete O_flags used for file open

- Src/IronPython.Modules/mmap.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
Establishing a mmap test from StdLib on POSIX to prevent unnoticed regressions from #1855.
The test does not pass on .NET 6.0, which has problems with mmaps not backed by an existing file. A workaround is possible, but likely quite tricky to get it right (i.e. w/o data leaking). I don't think it is worth the effort given that .NET 6.0 is now past its EOL.
The case of Mono seems hopeless; it dumps core when running this test.
> Enable test_mmap on net8.0/POSIX

- Src/StdLib/Lib/test/test_mmap.py
I kept them as a separate PR, in case they need to be reverted when IronPython migrates to later StdLib versions where these patches are already applied. AFAICS, 3.6 does not contain them.
Fixes local test failure in #1864.
> Backport fixes to python/cpython#107888

- Src/IronPython.Modules/mmap.cs
- Src/IronPythonTest/Cases/CPythonCasesManifest.ini
- Src/StdLib/Lib/test/test_mmap.py
One test is failing on my macOS (using Sequoia on ARM64). I have traced it to python/cpython#107888. I wonder what will happen on CI.
It turns out that `test_mmap` passes on .NET 6.0 on Linux, but not on macOS. Go figure. Anyway, I've relaxed the test run condition accordingly.
I have enabled some more tests that were marked TODO. It required some small and self-evident modifications to the test in StdLib. I've left comments at those places, in case there are some merge conflicts with later Python branches.
> Support additional memory protection flag combinations

- Src/IronPython.Modules/_warnings.cs
- Src/IronPython.Modules/mmap.cs
- Src/IronPython.Modules/nt.cs
- Src/IronPython/Modules/_fileio.cs
- Src/IronPython/Runtime/PosixFileStream.cs
- Src/IronPython/Runtime/PythonFileManager.cs
- Tests/test_file.py
- Tests/test_io_stdlib.py
This PR replaces `FileStream` with `PosixFileStream` on .NET/POSIX (not Mono), which offers unbuffered access to the file though its actual file descriptor. This addresses the issue #1846 on .NET/POSIX.
I decided to write own implementation of the stream, rather than encapsulating `UnixStream`. Not only the implementation had similar amount of work involved and complexity as a proxy class to `UnixStream`, but also it allowed me to make different implementation choices than `UnixStream`, some of which I would call problematic. The best example is `UnixStream.Close()`, which retries syscall to `close` if interrupted. This will result in error EBADF at best, and close an unrelated file descriptor at worst. It's because, on most systems (including Linux and macOS), `close` always closes the …
> Use PosixFileStream for files on POSIX

- Src/IronPython.Modules/_socket.cs
- Src/IronPython.Modules/errno.cs
- Src/IronPython.Modules/mmap.cs
- Src/IronPython.Modules/nt.cs
It turned to be more popular than I first thought and more usage is coming. `PythonErrno` is shorter hence more convenient. I would prefer simply `Errno`, but that could be confused with `Mono.Unix.Native.Errno`.
> Rename PythonErrorNumber to PythonErrno

- Src/IronPython.Modules/_overlapped.cs
- Src/IronPython.Modules/_winapi.cs
- Src/IronPython.Modules/mmap.cs
- Src/IronPython.Modules/nt.cs
- Src/IronPython.Modules/posix.cs
- Src/IronPython.Modules/resource.cs
- Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
This adds platform guards to relevant functions in `PythonNT`. By keeping them in a separate file I hope it will be easier to prevent omissions and inadvertent loads of `Mono.Unix` on Windows. Also, it makes `nt.cs` just a little bit smaller, which is always a good thing.
> Isolate POSIX-specific native calls in PythonNT into separate file

- Src/IronPython.Modules/mmap.cs
Implementing https://github.com/IronLanguages/ironpython3/pull/1872#issuecomment-2597357597
> Thread-safe mmap close

- tests/IronPython.Tests/Cases/CaseExecuter.cs
Increases the stack size used by the thread running tests to 2 MiB. [Reportedly](https://github.com/dotnet/runtime/issues/96347) the stack size of background treads on .NET 8.0 on macOS is extremely small (0.5 MiB), so it is easy to hit the limit.
This is essentially the last commit from #1879, which does not belong there but I pushed it there to test it with CI. I could not reproduce the stack overflow locally, probably because I develop on ARM which extensively uses registers for parameter passing so its stack usage is lower than on x64. Once this PR is merged, I will rebase #1879 on top of the current main branch (_sans_ the last commit) and presumably the tests will pass.
> Replace test Task with Thread with increased stack size

- src/core/IronPython.Modules/termios.cs
- tests/suite/modules/io_related/test_termios.py
`termios` — a module for low-level terminal I/O system control. It doesn't do much beside defining a bunch of system-specific constants and a few direct POSIX calls.[[1]][[2]]  The API is old, so old actually that I think it may be obsolete/unused. Anyone needing to set the baud rate to 300 bytes/second? 6 bits per character? On macOS, for instance, some mandatory but kind of obsolete POSIX flags are defined in the header files, but the syscalls don't support them (or not anymore). However, there are a few things that are still quite useful nowadays and perhaps impossible to perform in any other way in a portable fashion. The two common I have encountered:
1. Setting the terminal input mode to _raw_ (and back to _control-break_)
2. Getting (sometimes also setting) the size of the terminal …
> Implement rudimentary version of module `termios`

- .gitattributes
- src/core/IronPython.StdLib/.gitattributes
> @BCSharp while you're fixing this, might as well make this change.
> 
> ---
> 
> This hides files from showing up in GitHub here:
> ![image](https://github.com/user-attachments/assets/cead9079-a811-4c3c-90c8-d283a4f913a2)
> 
> IronPython doesn't use PSQL significantly enough for it to be detected, and HTML is used only for the documentation, which GitHub automatically enables filters for (that seem to not be working).
> So, this is how GitHub works… I had no idea.
> 
> You have raised a valid point, but although it also affects `.gitattributes`, it has nothing to do with code restructuring, so I'd rather it be done separately. Also, it deserves a proper discussion, e.g.:
> 
> * If we were to hide PLSQL, why not Roff?
> * If we hide PSQL and Roff, then perhaps other 0.0%-used languages …
> Code Quality: Removed unnecessary files from GitHub statistics

- make.ps1
Run test tasks sequenially in foreground if `-jobs 0`. The default did not change: it still runs all (up to the processor count) task groups in parallel jobs. `-jobs 1` also runs all tasks sequentially, but because it is run as a PowerShell job, the test output is not real-time, but displayed in 10 sec intervals.
This change has two purposes:
1. To be able to monitor the test progress in real-time, without the filter. This is useful when one or a small subset of tasks is run in a query, and especially useful if some tests that operate on stdin and std out misbehave.
2. On some devcontainer systems, PowerShell's [`Start-Job` does not work](https://github.com/PowerShell/PowerShell/discussions/24382) if not run by `root`. `-jobs 0` avoids `Start-Job` altogether.
> Run test tasks in foreground

- src/core/IronPython.Modules/fcntl.cs
- tests/suite/test_builtin_stdlib.py
This is a mock implementation of `fcntl.ioctl`, supporting only one command: `termios.TIOCGWINSZ` (i.e. Terminal I/O Control Get WINdow SiZe). It doesn't do any syscalls but provides the result using equivalent .NET functions. It ignores the file descriptor, and always returns the size of the console, so is not appropiate for pseudo-terminals (pty, tty). Nevertheless, it is still useful as some packages depend on this call to get the console window size (`prompt_toolkit.terminal.vt100_input`).
> Emulate `fcntl.ioctl` for command `TIOCGWINSZ`

- .gitignore
- NuGet.config
Just a small change, forwarding out #1815
NuGet doesn't need to be here (it is automatically registered as a package source by Visual Studio)
> Code Quality: Improved the way packages are managed in the codebase

- src/core/IronPython.Modules/mmap.cs
Follow-up on #1875. Originally I intended to implement a fully thread-safe mmap `resize`, meaning the tread would wait if there were other threads using mmap at the time. At the same time I wanted to keep the requirement that in normal use (no `resize` in progress), regular threads do no locking, waiting, or other expensive operations (`Interlocked.CompareExchange` deemed not expensive). It actually seemed to be possible, with the following schema:
1. In normal use, regular threads just update the reference count.
2. The exclusive tread, on entry to `resize`, grabs the writer lock of a `ReaderWriterLockSlim`
3. The exclusive thread then sets bit `Exclusive` in the state. This prompts incoming regular threads to fall back on the reader lock and wait on the writer lock be released.
4. The …
> Thread-safe mmap resize

- tests/IronPython.Tests/Cases/CPythonCasesManifest.ini
- tests/IronPython.Tests/Cases/CaseExecuter.cs
I think this is a better way of handling `fcntl_test` failure on Windows (#1893). It is skipping by exception name `SkipTest` rather than `unittest.SkipTest` because I coudn't figure out how to retrieve the defining module name.
> Skip test if exception `SkipTest` is raised

- src/core/IronPython.Modules/fcntl.cs
- tests/IronPython.Tests/Cases/CPythonCasesManifest.ini
This PR implements the main `fcntl`, plus `flock` and `lockf` and enables `test_fcntl` from the StdLib. `ioctl` remains still a mock.
The signature of syscal `fcntl` is variadic, but luckily this call is supported by _Mono.Unix_. It means that there is the extra translation step from the given _fcntl_ command code to Mono's enum, and then back to the actual OS code. This step will also filter out (as unsupported) all commands that were not defined yet by the OS at the time _Mono.Unix_ was built. For one thing, I miss `F_GETPATH`, which was added in Python 3.9. It is only on macOS, but on Linux one can get the path name from a descriptor by `readlink /dev/fd/«fileno»`. Well, maybe I will write a workaround for this one at some point.
The calls `flock` and `lockf` are not supported by …
> Implement `fcntl` syscalls

- src/core/IronPython.Modules/mmap.cs
- src/core/IronPython.Modules/re.cs
Add `IBufferProtocol` to `mmap`. Throws a `NotImplementedException` if the length does not fit in a `int`.
For the case of bigger files I think we'll have to rework `IPythonBuffer`. My initial thoughts on changes would be:
- Use `nint` in place of `int` where applicable (probably where CPython uses `Py_ssize_t`).
- Change `AsSpan`/`AsReadOnlySpan` methods to have an `nint start` argument.
- Fix up everything to use `nint` arithmetic instead of `int`.
Marking as draft since I need to do more testing (and maybe write some tests). @BCSharp I'm not sure if you looked at/thought about this before so if you have any feedback would appreciate it.
Related to https://github.com/IronLanguages/ironpython3/issues/1408
> Add IBufferProtocol to mmap

- src/core/IronPython.Modules/mmap.cs
- src/core/IronPython.StdLib/lib/test/test_mmap.py
The `_offset` was being ignored when resizing on Linux. Since resize should work on all the platforms we currently target (I think), I tweaked tests so they would not swallow the exception.
Also adds `SupportedOSPlatform` to the kernel32 call.
> Fix mmap.resize with offset

- src/core/IronPython/Runtime/Operations/ArrayOps.cs
Followup on https://github.com/IronLanguages/ironpython3/pull/1828#issuecomment-2520379088. In light of proposal #1887 I don't think it is worthwhile to spend effort on those two legacy operator implementations beyond of what was already supported.
> Add checks for non-0-based arrays in addition and multiplication operators

- src/core/IronPython.Modules/fcntl.cs
- src/core/IronPython.Modules/termios.cs
Implements `tcsendbreak`, `tcdrain`, `tcflush`, `tcflow`, which makes `termios` function-complete up to and including Python 3.10. The exported constants are still not complete. `tcgetattr` and `tcsetattr` remain mocks. To implement `tcgetwinsize`, and `tcsetwinsize` added in 3.11, `fcntl.ioctl` needs to be better implemented (currently it's a stub).
> Implement simple termios functions

- make.ps1
The standard way of running a specific test is by using a query. E.g. to test `test_codecs`
```
./make.ps1 test-test_codecs
```
However, this matches tests by substring, so for more popular test names the query may catch several tests. The example above selects the following tests for running:
* CPython.test_codecs (currently ignored)
* IronPython.modules.io_related.test_codecs
* IronPython.test_codecs
* Ironpython.test_codecs_stdlib
Even running more specific
```
./make.ps1 test-IronPython.test_codecs
```
will still match two tests.
To be able to run just one selected test, one must resolve to construct an elaborate query, which is also framework specific:
```
./make.ps1 "test-TestCategory=IronPython&Name=net8.0.IronPython.test_codecs" -framework net8.0
```
This PR adds the possbilility …
> Enable test query for exact test name

- src/core/IronPython.Modules/_ctypes/CData.cs
- src/core/IronPython.Modules/array.cs
- src/core/IronPython.Modules/mmap.cs
- src/core/IronPython/Runtime/BufferProtocol.cs
- src/core/IronPython/Runtime/ByteArray.cs
- src/core/IronPython/Runtime/Bytes.cs
- src/core/IronPython/Runtime/ConversionWrappers.cs
- src/core/IronPython/Runtime/MemoryView.cs
It turns out that `GetBufferNoThrow` is quite popular. However, it entailed a `try`/`catch` of `BufferException`, which incurs a performance penalty. In CPython, it turns out it is fairly common to try to get a buffer that is not supported , and then fall back on some more supported versions, since the error is inexpensive to return. However, it requires checking every return value, which is not convenient to the users of the interface. Besides, it is the provider, not the user, that can describe the error best.
This PR keeps the current of the usage interface the same, while keeping the complexity of implementing `IBufferProtocol` at a similar level, and avoiding the try/catch of the exception for unsupported calls.
> Avoid throw/catch exceptions when requesting optional buffer through `IBufferProtocol`

- src/core/IronPython.Modules/fcntl.cs
This replaces the mock `ioctl` implementation with the actual syscall.
The tricky part of it is that the `ioctl` prototype is variadic, is not supported by the _Mono.Unix_ shim, and .NET does not yet support variadic P/Invoke calls on POSIX. There is a long discussion on this topic (dotnet/runtime#48796) but after 4 years it does not seem to converge on any solution. As one of the commentators wrote: "perfect is the enemy of good". Hopefully in the next several years this will be sorted out, but in the meantime, an obscure workaround is needed to make a variadic P/Invoke work on ARM64. Too bad that we have to manage that level of calling convention detail and not the compiler, but I know of no alternative.
I put pragma `#error` there that gets triggered on any new .NET version we haven't …
> Implement syscall `ioctl`

- src/core/IronPython.Modules/nt.cs
- src/core/IronPython.Modules/posix.cs
It can be seen as an optimization, or a "fast track", but more importantly, it removes the assumption that all open file descriptors on POSIX are registered with `PythonFileManager`. It is currently true (but only as long as only Python code is considered), but it was not always true in the past and may not be true in the future.
Plus some cleanup in `utime` code.
> Improve `isatty` on POSIX

- .gitattributes
High score: 9 languages!
5 from main rounds, 4 from bonus round!
> Code Quality: Hide unnecessary languages from GitHub Linguist

- src/core/IronPython/Runtime/Binding/ConversionBinder.cs
- src/core/IronPython/Runtime/ConversionWrappers.cs
`MemoryBufferProtocolWrapper` was born out of a desire to provide a seamless and efficient conversion from CLR arrays (and `Memory<byte>` etc.) to `IBufferProtocol`, which proliferates the public API for "bytes-like" parameters.
It turns out that the wrapper class can be useful also for adapting `Memory` of other underlying unmanaged types to `IBufferProtocol`, hence the change to the generic `MemoryBufferProtocolWrapper<T>`. The rules in the conversion binder did not change, that is, still only byte-oriented types (`byte[]`, `Memory<byte>`, `ReadOnlyMemory<byte>`) are eligible to be automatically converted by the `ConversionBinder`. However, C# code may now use the class for other conversions, therefore be able to call methods accepting `IBufferProtocol` using arrays/memory with other …
> Convert `MemoryBufferProtocolWrapper` to generic

- src/core/IronPython.Modules/fcntl.cs
I think I've found a way to detect ARM64 on Mono that is reliable enough.
> Support `ioctl` on Mono

- .github/workflows/main.yml
- tests/IronPython.Tests/Cases/IronPythonCasesManifest.ini
The IronPython3 project does not have access to _macos-latest-large_, so the CI runner on macOS always fails on start generating spurious failures (but then restarts and continues as standard and succeeds anyway. Sometimes.)
> Downgrade _macos-latest-large_ to _macos-latest_

- src/core/IronPython.Modules/termios.cs
- src/core/IronPython/Runtime/Operations/PythonOps.cs
These functions are added in Python 3.11, but I implemented them now while I have the internals still fresh in my memory.
> Implement `tcgetwinsize`, `tcsetwinsize` in `termios`

- src/core/IronPython.Modules/nt.cs
- src/core/IronPython.Modules/termios.cs
- tests/IronPython.Tests/Cases/CaseExecuter.cs
OK, let's settle on `is object` test instead of `is not null and var`.
> Apply `is object` test

- src/core/IronPython.Modules/ModuleOps.cs
- src/core/IronPython.Modules/_ctypes/SimpleType.cs
- src/core/IronPython.Modules/_struct.cs
- src/core/IronPython.Modules/array.cs
- src/core/IronPython/Runtime/ConversionWrappers.cs
- src/core/IronPython/Runtime/TypecodeOps.cs
This PR is mostly just reorganizing the code handling typecodes across modules into a consistent ordering. Having a consistent ordering helps comparing implementations and spot irregularities (which may indicate a bug, and indeed, there were a few minor ones related to casting).
The ordering I adopted is based on what was used by `TypecodeOps` and `array` (although even there there were some inconsistencies), grouping by typecode klass:
* Boolean
* character
* integer
* floating point
* object
* pointer
Within one klass, the ordering is by size, within the same size, signed then unsigned, or regular then exotic.
This change is meant to be innocent, primarily code reordering, which is already difficult to review looking at the diffs. The more challenging typecode issues, like handling of …
> Typecode cleanup

- src/core/IronPython.Modules/_thread.cs
- src/core/IronPython.StdLib/lib/test/script_helper.py
- tests/IronPython.Tests/Cases/CPythonCasesManifest.ini
- tests/IronPython.Tests/Cases/IronPythonCasesManifest.ini
- tests/suite/test_threading_stdlib.py
Implement `_thread.RLock` and enable some `test_threading` tests.
I got bit by `functools.lru_cache` which uses a dummy lock if `_thread.RLock` is not available. 😢
> Implement _thread.RLock

- .github/workflows/main.yml
This PR splits each CI run into matrixes to make it easier to debug Ironpython builds and make out what's failing.
> Refactor CI workflow

- src/core/IronPython/Hosting/PythonCommandLine.cs
- src/core/IronPython/Runtime/ClrModule.cs
Resolves #1935 by implementing approach 1.
> Locate dotnet tool ipy launcher

- src/extensions/IronPython.SQLite/IronPython.SQLite.csproj
- src/extensions/IronPython.SQLite/c#sqlite/os_win_c.cs
The file locking strategy in SQLite was basically Windows-oriented, with some provisions for limited-trust environment like Silverlight, WinRT, and Windows Mobile. These are obsolete but somebody repurposed the limited-trust strategy to work on Unix. This worked on Linux (sort of, shared locks were seemingly emulated in a way that only SQLite respected), but wasn't working at all on macOS.
This PR implements proper locking on Linux and macOS through a fcntl syscall via _Mono.Unix_. Locking on Windows is unchanged.
I resisted the temptation to start cleaning up the code (it is even badly formatted), because there would be no end to it, and it is better to replace it by a modern SQLite implementation in a longer run anyway.
> Implement file locking in SQLite on Posix

- src/core/IronPython/Lib/iptest/test_env.py
- tests/suite/test_cliclass.py
- tests/suite/test_datetime_stdlib.py
The recent release of Mono — 6.20.0 — sports native support for ARM64 on macOS. Unfortunately, it appears that conversions to floating point numbers can be one LSB off from what is happening on x86_64. This causes some of the tests to fail. This PR contains a couple of workarounds so that the overall test tun on ARM64/macOS passes.
> ARM64 test workarounds

- src/core/IronPython.Modules/NtSignalState.cs
- src/core/IronPython.Modules/SimpleSignalState.cs
- src/core/IronPython.Modules/nt.cs
- src/core/IronPython.Modules/signal.cs
In preparation for more changes in `PythonSignal` (like making it work on POSIX).
> Clean up and modernize code in PythonSignal

- src/core/IronPython.Modules/_ctypes/StructType.cs
- tests/suite/modules/type_related/test_ctypes.py
This is a new feature in 3.14, which is still in alpha, so I don't know if the string IDs identifying the layout will make to final intact. I find it a bit strange that for `msvc` they use the abbreviation of a company (`ms`) and for `gcc` they use the compiler name, hyphen, an operating system name.
Therefore the tests to interpret the values of `_layout_` are a bit relaxed than what CPython 3.14a6 allows. Once 3.14 is released, it will be easy to fix the actual string IDs to match CPython's.
> Implement `_layout_` on ctypes structs

- src/core/IronPython.Modules/_collections.cs
- src/core/IronPython.Modules/array.cs
- src/core/IronPython.StdLib/lib/test/test_defaultdict.py
- src/core/IronPython/Runtime/ByteArray.cs
- tests/suite/test_isinstance.py
This PR changes the `repr()` on the builtin container types for their subclasses to display the subclass name rather than always the root base type. Similarly what is already done for `set`: `repr(set()` is `set()` but if `class MySet(set): pass` is defined, `repr(MySet())` is `MySet()`. The changed container types are:
- `bytearray`
- `array.array`
- `collections.defaultdict`
- `collections.deque`
This change has been implemented in Python 3.7. but in 3.4 - 3.6 there is one test in StdLib that catches the base class name; this has been upgraded here to the test from 3.7.
> Use actual container type name for repr

- .vsts-ci.yml
Looks like Noble caught up on Azure too. Related: #1867.
> Downgrade Ubuntu to Jammy (on Azure)

- src/core/IronPython.Modules/_collections.cs
- tests/suite/test_deque.py
It's a bit strange that the addition operator preserves the subclass type but multiplication and copy doesn't.
> Miscellaneous improvements in deque

- src/core/IronPython.Modules/IterTools.cs
- src/core/IronPython.Modules/nt.cs
- src/core/IronPython.Modules/resource.cs
- src/core/IronPython.Modules/time.cs
- src/core/IronPython/Runtime/ClrModule.cs
- src/core/IronPython/Runtime/Exceptions/PythonExceptions.BaseException.cs
- src/core/IronPython/Runtime/Operations/PythonOps.cs
- src/core/IronPython/Runtime/PythonFunction.cs
- src/core/IronPython/Runtime/PythonList.cs
- src/core/IronPython/Runtime/PythonTuple.cs
- src/extensions/IronPython.SQLite/Cursor.cs
- src/extensions/IronPython.SQLite/Statement.cs
- src/extensions/IronPython.SQLite/_sqlite.cs
- tests/IronPython.Tests/EngineTest.cs
This further addresses Issue #1718, this time when enumerating `tuple`. It builds on #1721, which handled the case of `list`.
As with `list`, the solution is to specify the context in the constructor that uses enumeration to create the object. However, not always the current context is the best choice. For instance, when the object to enumerate is of one of the .NET types, the default context is a better solution. So alongside the constructor change, I have reviewed all instances of its use and decided whether the current or default context will be a better choice (in most practical cases). It is a heuristic, not a rule, so it is possible that in some scenarios my choices are not optimal (but still functionally correct).
> Eliminate contextless PythonTuple constructor

- src/core/IronPython.Modules/signal.NtSignalState.cs
- src/core/IronPython.Modules/signal.SimpleSignalState.cs
- src/core/IronPython.Modules/signal.cs
- tests/suite/modules/system_related/test_signal.py
This PR removes a lock hold that used to be held during the execution of a custom signal handler. For two main reasons:
1. CPython does not synchronize the execution of custom handlers (although it always runs them on the main thread) — if a signal comes during the execution of a custom signal handler function, the function will be interrupted and re-entered.
2. In theory holding a lock during the callback could create a deadlock — in IronPython any thread can set a signal handler (in CPython — only the main thread), so if the callback waits on a thread that tries to change signal registrations, it will cause a deadlock.
Point 1 would technically be a breaking change since the callback has to be now thread-safe (re-entrant, like in CPython), except that the only signal currently supported …
> Do not lock while calling signal handles

- src/core/IronPython.Modules/_collections.cs
- src/core/IronPython.Modules/_functools.cs
- src/core/IronPython.Modules/_heapq.cs
- src/core/IronPython.Modules/_operator.cs
- src/core/IronPython.Modules/array.cs
- src/core/IronPython.Modules/select.cs
- src/core/IronPython/Modules/Builtin.cs
- src/core/IronPython/Runtime/Binding/PythonBinaryOperationBinder.cs
- src/core/IronPython/Runtime/ByteArray.cs
- src/core/IronPython/Runtime/Bytes.cs
- src/core/IronPython/Runtime/DictionaryOps.cs
- src/core/IronPython/Runtime/Exceptions/PythonExceptions.cs
- src/core/IronPython/Runtime/Importer.cs
- src/core/IronPython/Runtime/Operations/ArrayOps.cs
- src/core/IronPython/Runtime/Operations/ByteOps.cs
- src/core/IronPython/Runtime/Operations/ObjectOps.cs
- src/core/IronPython/Runtime/Operations/PythonOps.cs
- src/core/IronPython/Runtime/PythonDictionary.cs
- src/core/IronPython/Runtime/PythonList.cs
This PR builds further on #1721 and #1946 by using `CodeContext` with various iterables.
> Use module context with iterables

- src/core/IronPython.Modules/signal.SimpleSignalState.cs
- src/core/IronPython/Hosting/PythonCommandLine.cs
- src/core/IronPython/Runtime/PythonContext.cs
This is basically a fix for the `signal` module on POSIX. What was happening was that on POSIX, signals (to be more accurate: `SIGINT` only) are handled by `SimpleSignalState`, which installs a `ConsoleCancelEventHandler` on `Console.CancelKeyPress`. However, `BasicConsole` also installs its handler to handle Ctrl+C, and it happens very early during execution, way before module `signal` can be imported. Since the event handlers are executed in the order of registrations, `BasicConsole` is seeing the event before `signal`, calling `ThreadAbort` (which obviously does not work on .NET), and module `signal` had no chance to even react to `SIGINT`. This means that setting `SIGINT` to be ignored, or to terminate the program, or to call a custom event handler was ineffective.
This problem does …
> Override console Ctrl+C event handler with handler in module `signal`

- src/core/IronPython.Modules/_ctypes/_ctypes.cs
- src/core/IronPython.Modules/_thread.cs
- src/core/IronPython/Runtime/Exceptions/PythonExceptions.cs
- src/core/IronPython/Runtime/Operations/PythonOps.cs
Follow-up to my comment in https://github.com/IronLanguages/ironpython3/pull/1949.
> Obsolete PythonOps.CallWithArgsTuple

- src/core/IronPython.Modules/signal.NtSignalState.cs
- src/core/IronPython.Modules/signal.SimpleSignalState.cs
- src/core/IronPython.Modules/signal.cs
- src/core/IronPython/Runtime/PythonContext.cs
This PR is relevant for hosting scenarios. Importing module `signal` in one IronPython engine registers a Ctrl+C signal handler, but it was not properly unregistered on engine shutdown. This means the handler was being referenced from the static `System.Console` (on Windows I suppose from the callback marshalling code) and caused a memory leak and interference with another later instance of the engine (at best).
The solution in this PR is to make `PythonSignalState` disposable and modify `PythonContext` that it recognizes disposable module states. For good measure I implemented a finalizer too although I think it will never (i.e before process termination) be called because without a call to `Dispose()` reference will stay alive and not being GC-ed.
> Unregister signal handlers during engine shutdown

- src/core/IronPython.Modules/signal.PosixSignalState.cs
- src/core/IronPython.Modules/signal.cs
This  implementation of handling signals on POSIX uses `PosixSignalRegistration`, which is aviavilable since .NET 6. It is not available on Mono, so on Mono, signal handling is unchanged (i.e. only handling of `SIGINT` is supported). Unfortunately, it also means no full POSIX signal handling on .NET Standard. Mono does provide its own API for handling signals (actually, three different approaches), but all of them come with some deficiencies (see below), so even if I had used them, I would still prefer `PosixSignalRegistration` on .NET, hence this is the version I submit here.
Since it works quite fine on .NET, it is quite unlikely I will be working on an alternative implementation that runs on Mono. Therefore I am writing my findings about the Mono API here just in case it might be …
> Implement handling POSIX signals

- src/core/IronPython/Hosting/Python.cs
- src/core/IronPython/Hosting/PythonCodeDomCodeGen.cs
- src/core/IronPython/Hosting/PythonCommandLine.cs
- src/core/IronPython/Hosting/PythonConsoleOptions.cs
- src/core/IronPython/Hosting/PythonOptionsParser.cs
- src/core/IronPython/Hosting/PythonService.cs
Also fixes some related bugs:
- Use `string.IsNullOrEmpty` to check console environment variables.
- Don't crash when the running assembly is on the root.
> Add nullable annotations to Hosting APIs

- Directory.Build.props
- src/core/IronPython.Modules/_ctypes/CData.cs
- src/core/IronPython.Modules/_ctypes/SimpleType.cs
- src/core/IronPython.Modules/_datetime.cs
- src/core/IronPython.Modules/_heapq.cs
- src/core/IronPython.Modules/_sre.cs
- src/core/IronPython.Modules/re.cs
- src/core/IronPython/Compiler/Ast/TupleExpression.cs
- src/core/IronPython/Modules/Builtin.cs
- src/core/IronPython/Runtime/Operations/StringOps.cs
- src/core/IronPython/Runtime/PythonContext.cs
- src/core/IronPython/Runtime/PythonDictionary.cs
- src/core/IronPython/Runtime/StringFormatter.cs
Unify (most of) the C# codebase for 3.4 and 3.6.
Diff can be obtained using:
```
git diff main..3.6 -- :!src/core/IronPython.StdLib/lib :!*_stdlib.py
```
> Unify 3.4 and 3.6
