IronLanguages/ironpython3

Build.proj, IronPython.sln, Src/IronPythonTest/Cases/CPythonCases.cs, Src/IronPythonTest/Cases/CaseGenerator.cs, Src/IronPythonTest/Cases/IronPythonCases.cs, Src/IronPythonTest/IronPythonTest.csproj, Src/IronPythonTest/Program.cs, Src/IronPythonTest/ProtocolTest.cs, Src/StdLib/Lib/test/test_pep3131.py, appveyor.yml, make.cmd, packages.config.template
* Minimum .NET is now 4.0
* IronPythonTest becomes an exe rather than a library
* IronPythonTestConsole is no longer used
Signed-off-by: Tim Orling <timothy.t.orling@linux.intel.com>
=> Update to NUnitLite 3.5.0; add appveyor.yml

appveyor.yml
Signed-off-by: Tim Orling <timothy.t.orling@linux.intel.com>
=> Use correct webhook for gitter/appveyor integration

Src/IronPython.Modules/_functools.cs, Src/IronPython/Modules/Builtin.cs, Src/IronPython/Modules/imp.cs, Src/IronPython/Modules/sys.cs, Src/IronPython/Runtime/Operations/PythonOps.cs
Fix #119, Fix #120, Fix #121, Fix #122, Fix #123, Fix #124, Fix #125, Fix #126, Fix #127, Fix #128, Fix #129
=> Initial clean-up of builtins

Src/IronPython.Modules/nt.cs
=> Add _have_functions to nt module

Src/IronPython/IronPython.csproj, Src/IronPython/Modules/_imp.cs
Rename the builtin imp module to _imp
=> Rename imp to _imp

Makefile, Src/IronPythonTest/Cases/CPythonCases.cs, Src/IronPythonTest/Cases/CaseExecuter.cs
Show the python exception information if available.
=> Updates to test runner output

Src/IronPython/Compiler/Ast/FunctionDefinition.cs
Resolves an assertion error which may be blocking the AppVeyor testing.
=> Fix for assertion error

Src/IronPython/Compiler/Ast/FlowChecker.cs, Src/IronPython/Compiler/Ast/Parameter.cs, Src/IronPython/Compiler/Ast/PythonNameBinder.cs, Src/IronPython/Compiler/Ast/PythonWalker.Generated.cs, Src/IronPython/Compiler/Parser.cs
Removes `SublistParameter` code which is no longer used since #137.
=> Remove SublistParameter

WhatsNewInPython30.md
Add markdown to track progress.
=> Add What's New In Python 3.0

Src/IronPython.Modules/nt.cs, WhatsNewInPython30.md
=> OS cleanup

Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonContext.cs, Src/IronPython/Runtime/Types/PythonType.cs
This isn't quite right since `__prepare__` may end up getting called too often, but it seems to work...
=> Call __prepare__ of metaclass

Src/IronPython.Modules/_bytesio.cs, Src/IronPython/Runtime/Binding/ConversionBinder.cs, Src/IronPython/Runtime/Binding/PythonProtocol.Operations.cs, Src/IronPython/Runtime/Bytes.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/Types/PythonTypeInfo.cs
Removed conditional code which checked for `PythonOptions.Python30`.
I didn't completely remove the option since there's still some code in there dealing with bytes/string conversion which will be required until we start to untangle that mess...
=> Remove some conditional code

Src/IronPython.Modules/_io.cs, Src/IronPython.Modules/nt.cs, Src/IronPython/Runtime/ByteArray.cs, Src/IronPython/Runtime/Bytes.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/Operations/StringOps.cs
Quick fix to make `str.encode` return `bytes`.
=> Change some strings to Bytes

Src/StdLib/Lib/abc.py, Src/StdLib/Lib/enum.py, Src/StdLib/Lib/random.py
Adds super arguments to "core" modules. This should be reverted once super is properly implemented.
=> Temporarily add super arguments

Src/StdLib/Lib/traceback.py
This will need to be reverted once yield from is properly implemented.
=> Temporarily replace yield from with yield in module used by testing

Src/IronPython/Runtime/Operations/PythonOps.cs
If no base is provided, then object should be an implicit base class.
=> Make all classes inherit from object

Src/IronPython/Runtime/Exceptions/PythonExceptions.cs
Next error after adding a dummy clear.
=> Add with_traceback

Src/IronPython/Lib/iptest/__init__.py, Src/IronPython/Lib/iptest/assert_util.py, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Tests/perf_micro_calls.py, Tests/regressions.py, Tests/test_ast.py, Tests/test_bigint.py, Tests/test_class.py, Tests/test_datetime.py, Tests/test_dict.py, Tests/test_file.py, Tests/test_generator.py, Tests/test_ironmath.py, Tests/test_range.py
Fixes a few xranges and a core logging issue.
=> Fix some issues with IronPython tests

Src/StdLib/Lib/doctest.py
Should be reverted once #213 is fixed.
=> Temporary workaround for #213

Src/IronPython.Modules/socket.cs, Src/IronPython/Compiler/Ast/AstMethods.cs, Src/IronPython/Compiler/Ast/RaiseStatement.cs, Src/IronPython/Compiler/Ast/SetExpression.cs, Src/IronPython/Compiler/Parser.cs, Src/IronPython/Modules/_ast.cs, Src/IronPython/Runtime/Exceptions/PythonExceptions.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonContext.cs, WhatsNewInPython30.md
Implement PEP 3109 (#15) and exception chaining (#70) cleanup.
=> PEP 3109 and PEP 3134

Src/IronPython.Modules/atexit.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonContext.cs
Some tests are still failing, but the overall implementation works.
=> Implement the atexit module

Src/IronPython.Modules/math.Generated.cs, Src/IronPython.Modules/math.cs, Src/Scripts/generate_math.py
This gets all the test_math tests passing, however it's still failing when run with the test suite. Looks like it's having trouble finding some files because it's trying to use the following to get the folder:
```Python
if __name__ == '__main__':
file = sys.argv[0]
else:
file = __file__
test_dir = os.path.dirname(file) or os.curdir
```
=> Get test_math passing

Src/IronPython.Modules/_socket.cs, Src/IronPython.Modules/_ssl.cs
=> Fix references to socket module

Src/IronPython.Modules/IronPython.Modules.csproj, Src/IronPython.Modules/_posixsubprocess.cs
Add a dummy module for _posixsubprocess.
=> _posixsubprocess dummy module

Src/IronPython/IronPython.csproj, Src/IronPython/Modules/Builtin.cs, Src/IronPython/Runtime/DictionaryOps.cs, Src/IronPython/Runtime/Operations/TypeTrackerOps.cs, Src/IronPython/Runtime/Types/MappingProxy.cs, Src/IronPython/Runtime/Types/PythonTypeDictSlot.cs
This fixes an issue with the testing infrastructure that started failing a bunch of tests after #255.
=> Change DictProxy to MappingProxy

Build/net40.props, Build/net45.props, Makefile, Src/IronPython.Modules/nt.cs
This helps tests on Linux get further.
=> Add some POSIX stuff

Src/IronPython.Modules/math.cs
=> Apply asinh fix from ipy2

Src/IronPython.Modules/_sre.cs, Src/IronPython.Modules/re.cs
Covers: IronLanguages/main#1371 IronLanguages/main#1372 IronLanguages/main#1485 https://github.com/IronLanguages/main/commit/28060f81ac428e4e33e6d69b1705389ae3486fb8
=> Update re with 2.7 fixes

Src/IronPython.Modules/winreg.cs
Covers: IronLanguages/main#1428 IronLanguages/main#1475 IronLanguages/main#1476 IronLanguages/main#1486 IronLanguages/main#1532
=> Update winreg with 2.7 fixes

Src/IronPython.Modules/_socket.cs, Src/IronPython.Modules/_ssl.cs
Covers: .NET Core stuff (which I may eventually remove), IronLanguages/main#1432, part of IronLanguages/main#1448
=> Update socket and ssl with 2.7 fixes

Src/IronPython.Modules/IronPython.Modules.csproj, Src/IronPython.Modules/_operator.cs
Also adds `_compare_digest` (from IronLanguages/main#1448)
=> Rename operator to _operator

Src/IronPython.Modules/ModuleOps.cs, Src/IronPython.Modules/_bisect.cs, Src/IronPython.Modules/_codecs.cs, Src/IronPython.Modules/_csv.cs, Src/IronPython.Modules/_ctypes/NativeFunctions.cs, Src/IronPython.Modules/_pickle.cs, Src/IronPython/Runtime/ConversionWrappers.cs, Src/IronPython/Runtime/Operations/StringOps.cs
Covers IronLanguages/main#1431, IronLanguages/main#1419, IronLanguages/main#1367, IronLanguages/main#1503, IronLanguages/main#1450, IronLanguages/main#1461 and  	IronLanguages/main@fdd036d
=> Changes from ipy2.7

Src/IronPython/Compiler/Ast/CallExpression.cs, Src/IronPython/Compiler/Ast/ClassDefinition.cs, Src/IronPython/Compiler/Ast/FunctionDefinition.cs, Src/IronPython/Compiler/Ast/PythonNameBinder.cs, Src/IronPython/Compiler/Ast/ScopeStatement.cs, Src/IronPython/Compiler/Parser.cs, Src/IronPython/Modules/_ast.cs, Src/IronPython/Runtime/Super.cs, Src/Scripts/generate_calls.py, Src/Scripts/generate_walker.py, make.cmd
This allows most of the stdlib tests to get by the calls to new super. Reviews would be great.
=> [WIP] new super implementation

Src/StdLib/Lib/abc.py, Src/StdLib/Lib/enum.py, Src/StdLib/Lib/random.py
Now that we have a working super, revert #180.
=> Fix #182 (revert #180)

Src/IronPython/Modules/Builtin.cs, Tests/test_builtinfunc.py
I copied the changes from https://github.com/IronLanguages/main/pull/1637
=> Copy fix from #1636 main issue

Src/IronPython.Modules/_struct.cs
Port of https://github.com/IronLanguages/ironpython2/pull/290
=> Performance improvements for _struct

Build.proj, Package/nuget/IronPython.nuspec
Port of https://github.com/IronLanguages/ironpython2/pull/283
=> Include XML files in the final package

make.ps1
Port of https://github.com/IronLanguages/ironpython2/pull/280
=> Save lastexitcode in make.ps1 Main function

make.ps1
Port of https://github.com/IronLanguages/ironpython2/pull/276
=> Fix make single for multiple platforms

Src/IronPython.Wpf/_wpf.cs, Src/StdLib/Lib/wpf.py
Port of https://github.com/IronLanguages/ironpython2/pull/281
=> Change wpf module implementation, similar to sqlite

Src/IronPython/Runtime/Types/DocBuilder.cs
Port of https://github.com/IronLanguages/ironpython2/pull/312
=> Fix issue with doc builder

Src/IronPython.SQLite/Connection.cs, Src/IronPython.SQLite/Statement.cs
Port of https://github.com/IronLanguages/ironpython2/pull/303
=> Update DLR and replace Microsoft.Scripting.Math.BigInteger usages

Src/IronPython/Modules/Builtin.cs, Src/IronPython/Modules/_io.cs, Tests/test_file.py
=> open now takes an optional opener argument

Src/IronPython/Runtime/Binding/PythonProtocol.Operations.cs
The test has already been ported
=> Bring in update from ipy2

Src/StdLib/Lib/traceback.py
Resolves https://github.com/IronLanguages/ironpython3/issues/193
=> Revert #191

Src/IronPython/Compiler/Ast/AstMethods.cs, Src/IronPython/Compiler/Ast/FunctionDefinition.cs, Src/IronPython/Compiler/Ast/Parameter.cs, Src/IronPython/Compiler/Ast/ScopeStatement.cs, Src/IronPython/Compiler/Ast/SerializedScopeStatement.cs, Src/IronPython/Runtime/FunctionCode.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonFunction.cs
Part of https://github.com/IronLanguages/ironpython3/issues/10
=> Keyword-only args prep work

.github/ISSUE_TEMPLATE.md, Build/steps.yml, NuGet.config, Src/IronPython.Modules/pyexpat.cs, Src/IronPython/Lib/iptest/ipunittest.py, Src/IronPython/Modules/_bytesio.cs, Src/IronPython/Runtime/Binding/MetaPythonType.Calls.cs, Src/IronPython/Runtime/Binding/PythonBinder.Create.cs, Src/IronPython/Runtime/Binding/PythonBinder.cs, Src/IronPython/Runtime/Exceptions/SystemExitException.cs, Src/IronPython/Runtime/Operations/PythonTypeOps.cs, Src/IronPython/Runtime/Types/PythonType.cs, Src/IronPythonTest/Cases/CaseExecuter.cs, Src/StdLib/Lib/ensurepip/__init__.py, Tests/modules/io_related/test__bytesio.py, Tests/test_enum.py, Tests/test_stdconsole.py
https://github.com/IronLanguages/ironpython2/pull/511
https://github.com/IronLanguages/ironpython2/pull/510
https://github.com/IronLanguages/ironpython2/pull/508
https://github.com/IronLanguages/ironpython2/pull/490
https://github.com/IronLanguages/ironpython2/pull/429
https://github.com/IronLanguages/ironpython2/pull/424
https://github.com/IronLanguages/ironpython2/pull/412
https://github.com/IronLanguages/ironpython2/pull/369
=> Port from IronPython2

Src/IronPython.Modules/IterTools.cs
Does not work with pickling, hits an issue with the special handling for reduce
=> itertools.accumulate implementation

Src/IronPython.Modules/IronPython.Modules.csproj, Src/IronPython.Modules/_ctypes/CFuncPtr.cs, Src/IronPython.Modules/_ctypes/_ctypes.cs, Src/IronPython.Modules/grp.cs, Src/IronPython.Modules/msvcrt.cs, Src/IronPython.Modules/nt.cs, Src/IronPython.Modules/pwd.cs, Src/IronPython.Modules/spwd.cs, Src/IronPython.Modules/winsound.cs, Src/IronPython.SQLite/IronPython.SQLite.csproj, Src/IronPython/Compiler/PythonSavableScriptCode.cs, Src/IronPython/Hosting/PythonCommandLine.cs, Src/IronPython/IronPython.csproj, Src/IronPython/Lib/iptest/test_env.py, Src/IronPython/Runtime/ClrModule.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPython/Runtime/Types/DocBuilder.cs, Src/IronPythonConsole/IronPythonConsole.csproj, Src/IronPythonTest/Cases/CaseExecuter.cs, Src/IronPythonTest/IronPythonTest.csproj, Tests/interop/net/type/test___clrtype.py, Tests/interop/net/type/test_defaultmember.py, Tests/interop/net/type/test_reachtype.py, Tests/test_clrtype.py, Tests/test_delegate2.py, Tests/test_methodbinder1.py
Drop support for .NET Core 2.0 since it reached EOL on Oct 1st.
=> Drop support of .NET Core 2.0

Build.proj, Directory.Build.props, Package/msi/Msi.Packaging.targets, make.ps1
BuildFlavour is non-standard, change to standard Configuration
=> Change BuildFlavour to Configuration

Src/IronPython/Runtime/DictionaryOps.cs, Src/IronPython/Runtime/Types/MappingProxy.cs, Src/IronPython/Runtime/Types/PythonType.cs, Tests/test_regressions.py
Reverts some of the "improvements" done in https://github.com/IronLanguages/ironpython3/pull/259. Fixes https://github.com/IronLanguages/ironpython3/issues/458.
=> Fix mappingproxy

Src/IronPython/Compiler/Ast/Comprehension.cs
https://github.com/IronLanguages/main/pull/1199
=> Changes from ipy2

Src/IronPython.Modules/nt.cs
These are no longer in `nt` and end up being overwritten by `os` defined methods.
=> Remove nt methods

Src/IronPython/Modules/Builtin.cs, Src/IronPython/Runtime/Binding/MetaMethod.cs, Src/IronPython/Runtime/ClassMethodDescriptor.cs, Src/IronPython/Runtime/Descriptors.cs, Src/IronPython/Runtime/Method.Generated.cs, Src/IronPython/Runtime/Method.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonFunction.cs, Src/IronPython/Runtime/Types/BuiltinFunction.cs, Src/IronPython/Runtime/Types/BuiltinMethodDescriptor.cs, Src/IronPython/Runtime/Types/PythonType.cs, Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini, Src/Scripts/generate_calls.py, Tests/test_regressions.py, WhatsNewInPython30.md
Resolves https://github.com/IronLanguages/ironpython3/issues/490
=> Remove the concept of unbounded methods

Src/IronPython/Runtime/Converter.cs, Src/IronPython/Runtime/Enumerate.cs, Tests/test_builtinfunc.py, Tests/test_regressions.py
=> Fix overflow error with enumerate

Src/IronPython/Modules/Builtin.cs, Tests/test_builtinfunc.py, WhatsNewInPython34.md
#502 added default keyword arg
=> add default keyword arg for min/max

Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
See https://github.com/IronLanguages/ironpython3/issues/489
=> Reenable tests

Src/IronPython.Modules/_collections.cs, Src/IronPython.Modules/nt.cs, Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini, Src/StdLib/Lib/test/test_deque.py, WhatsNewInPython32.md
More work needs to be done on pickling, but it's blocked by https://github.com/IronLanguages/ironpython3/issues/515.
=> Enable test_deque

Src/IronPython.Modules/time.cs, Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini, Src/StdLib/Lib/test/test_timeit.py
=> Enable test_timeit

Src/IronPython/Modules/_io.cs, Src/IronPython/Runtime/Binding/PythonProtocol.Operations.cs, Src/IronPython/Runtime/ByteArray.cs, Src/IronPython/Runtime/Bytes.cs, Src/IronPython/Runtime/Converter.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini, Src/StdLib/Lib/test/test_index.py
Related to https://github.com/IronLanguages/ironpython3/issues/524
=> Get test_index passing

Src/IronPython.Modules/_codecs.cs, Src/IronPython.Modules/_winapi.cs, Src/IronPython/Compiler/Tokenizer.cs, Src/IronPython/Modules/Builtin.cs, Src/IronPython/Runtime/ByteArray.cs, Src/IronPython/Runtime/Exceptions/PythonExceptions.Generated.cs, Src/IronPython/Runtime/Exceptions/PythonExceptions.cs, Src/IronPython/Runtime/LiteralParser.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPython/Runtime/PythonAsciiEncoding.cs, Src/IronPython/Runtime/PythonContext.cs, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Src/Scripts/generate_exceptions.py, Src/StdLib/Lib/subprocess.py, Tests/encoded_files/cp11334_ok.py, Tests/encoded_files/cp11334_warn.py, Tests/modules/io_related/test_codecs.py, Tests/test_unicode.py
@slide Sorry for yet another massive PR.
=>  Enable test_codecs and test_unicode

Src/IronPython.Modules/hashlib/_hashlib.cs, Src/IronPython.Modules/hashlib/_md5.cs, Src/IronPython.Modules/hashlib/_sha1.cs, Src/IronPython.Modules/hashlib/_sha256.cs, Src/IronPython.Modules/hashlib/_sha512.cs, Src/IronPython.Modules/re.cs, Src/IronPython/Runtime/ByteArray.cs, Src/IronPython/Runtime/Bytes.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPython/Runtime/PythonContext.cs, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Src/StdLib/Lib/unittest/case.py, Tests/modules/misc/test__sha256.py, Tests/modules/misc/test__sha512.py, Tests/test_bytes.py, Tests/test_ironmath.py, Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/537 among other things.
Also resolves https://github.com/IronLanguages/ironpython3/issues/470
=> Enable test_bytes

Src/IronPython.Modules/nt.cs, Tests/test_shutil.py
also adds a some shutil tests.
=> Fix some issues with shutil.copyfile and shutil.copystat

Src/IronPython/Runtime/Operations/StringOps.cs
Helps with testing and debugging.
=> Make EncodingWrapper transparent

Src/IronPython.Modules/_collections.cs, Src/StdLib/Lib/test/test_deque.py
... that were disabled in https://github.com/IronLanguages/ironpython3/pull/516
=> Re-enable some tests in test_deque

Src/StdLib/Lib/doctest.py
Reverts IronLanguages/ironpython3#214
=> Revert "Temporary workaround for #213"

Src/IronPython/Modules/_fileio.cs, Src/IronPython/Runtime/PythonFileManager.cs, Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/580
=> #580 fix open(bogus file descriptor) to raise OSError

Src/IronPython/Runtime/Operations/ListOfTOps.cs, Tests/test_list.py
Fix bug in code path that was never hit before https://github.com/IronLanguages/ironpython3/pull/601.
=> Fix issue with List<T> slicing

Src/IronPython/Runtime/MemoryStreamContentProvider.cs
This fixes the regression in #603.
=> Bugfix in MemoryStreamContentProvider

Src/StdLib/Lib/test/test_urlparse.py
See https://github.com/IronLanguages/ironpython3/issues/614
=> Handle test failure on Mono

Src/IronPython/Runtime/ByteArray.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini, Src/IronPythonTest/Cases/CaseExecuter.cs
Tests for PEP-263 and PEP-3120 (#22).
=> Enable AllCPython.test_source_encoding

Build/netcoreapp3.0.props, IronPython.sln, Src/IronPython.Modules/IronPython.Modules.csproj, Src/IronPython.Modules/_codecs.cs, Src/IronPython.Modules/_ctypes/_ctypes.cs, Src/IronPython.Modules/nt.cs, Src/IronPython.SQLite/IronPython.SQLite.csproj, Src/IronPython/Hosting/PythonCommandLine.cs, Src/IronPython/IronPython.csproj, Src/IronPython/Lib/iptest/test_env.py, Src/IronPython/Modules/Builtin.cs, Src/IronPython/Modules/sys.cs, Src/IronPython/Runtime/Binding/ConversionBinder.cs, Src/IronPython/Runtime/ClrModule.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPython/Runtime/StringFormatter.cs, Src/IronPython/Runtime/Types/DocBuilder.cs, Src/IronPythonConsole/IronPythonConsole.csproj, Src/IronPythonTest/Cases/CaseExecuter.cs, Src/IronPythonTest/EncodingTest.cs, Src/IronPythonTest/IronPythonTest.csproj, Tests/modules/io_related/test_codecs.py, Tests/test_file.py, Tests/test_formatting.py, Tests/test_ironmath.py, Tests/test_isinstance.py, Tests/test_regressions.py, make.ps1
Covers https://github.com/IronLanguages/ironpython2/pull/630 and https://github.com/IronLanguages/ironpython2/pull/633
=> Add .NET Core 3.0 target

Src/IronPython/Runtime/PythonEncoding.cs, Src/IronPythonTest/EncodingTest.cs
@BCSharp See any issues with this change?
=> Get matching encoding names

Src/IronPython/Compiler/Ast/PythonAst.cs, Src/IronPython/Compiler/Ast/PythonNameBinder.cs, Src/IronPython/IronPython.csproj, Src/IronPython/Runtime/Importer.cs, Src/IronPython/Runtime/PythonContext.cs, Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini, Src/IronPythonTest/Cases/CaseExecuter.cs, Src/IronPythonTest/Stress/Engine.cs
Resolves https://github.com/IronLanguages/ironpython3/issues/414
=> [wip] Bootstrap importlib

Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini
Removes https://github.com/IronLanguages/ironpython3/issues/414 as a failure reason
=> Update test failure reasons

Src/IronPython/Hosting/PythonCommandLine.cs
Port of https://github.com/IronLanguages/ironpython2/pull/657
=> Fix https://github.com/IronLanguages/ironpython2/issues/654

Tests/test_regressions.py
https://github.com/mono/mono/issues/17192
=> Disable failing test on Mono

Src/IronPython.Modules/_codecs.cs, Tests/modules/io_related/test_codecs.py, Tests/test_codecs_stdlib.py
=> Implement UTF-16 support in codecs module

Src/IronPython.Modules/_warnings.cs, Src/IronPython/Hosting/PythonOptionsParser.cs, Src/IronPython/Modules/sys.cs, Src/IronPython/Runtime/Binding/BindingWarnings.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonContext.cs, Src/IronPython/Runtime/PythonOptions.cs
=> Remove py3k_warning and WarnPython30

Src/IronPython.Modules/_socket.cs, Src/IronPython.Modules/_ssl.cs, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Tests/modules/network_related/test__ssl.py
The whole ssl module is messed up, but this enables the tests on what we have.
=> Enable test__ssl

Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Tests/test_range.py
Resolves https://github.com/IronLanguages/ironpython3/issues/469
=> Enable IronPython.test_range

Src/IronPython/Hosting/PythonCommandLine.cs, Src/IronPython/Lib/iptest/test_env.py, Src/IronPython/Modules/sys.cs, Src/IronPython/Runtime/PythonContext.cs
Resolves https://github.com/IronLanguages/ironpython3/issues/702, https://github.com/IronLanguages/ironpython3/issues/703 and https://github.com/IronLanguages/ironpython3/issues/704.
=> sys.platform cleanup

Src/IronPython.Modules/_struct.cs, Tests/test_struct.py
Hi, I believe this resolves #674.
=> Add support for 'n'/'N' formats in struct

Src/IronPython.Modules/_struct.cs, Tests/test_struct.py
...and this should resolve #675.
=> Add support for struct.iter_unpack

IronPython.sln, Src/IronPython/Runtime/Types/PythonType.cs, Src/IronPythonConsole32/IronPythonConsole32.csproj
https://github.com/IronLanguages/ironpython2/pull/692
=> Prevent Mono crash during CI

Src/IronPython/Runtime/Operations/StringOps.cs
=> Bugfix in escape encoding of surrogate pairs

Src/IronPython.Modules/_codecs.cs, Tests/modules/io_related/test_codecs.py
Just like for `charmap_encode` in #748, only the regular, unoptimized `dict`-type charmap variant addressed.
=> Fix codecs.charmap_decode

Tests/modules/network_related/test__ssl.py
Hopefully it will reduce a few false negatives from CI tests.
=> Remedy intermittent failures of test__ssl

Src/IronPython/Runtime/ByteArray.cs, Tests/test_bytes.py
No functionality change in this PR, just a fast track for `bytearray` slice assignment. In a few circumstances data copy will be avoided.
The added tests to not cover any new bugs. If the slice assignment is from `memoryview`, currently a data copy is always made, even if `memoryvierw ` is on another `bytearray`. If in the future this it optimized further, precautions have to be made when `bytearray` is assigning to itself. The added tests are to ensure proper precautions are in place.
=> Optimize bytearray slice assignment

Src/IronPython.Modules/binascii.cs, Src/IronPythonTest/Cases/AllCPythonCasesManifest.ini, Src/StdLib/Lib/base64.py
Related to https://github.com/IronLanguages/ironpython3/issues/791
=> Enable test_base64

Src/IronPython/Runtime/PythonBytesIterator.cs, Tests/test_bytes.py
Because CPython has it and it was easy to do... 😃
=> Implement __length_hint__ in bytes_iterator

Src/StdLib/Lib/pickle.py
Workaround for https://github.com/IronLanguages/ironpython3/issues/809
=> Workaround for #809

Src/StdLib/Lib/sre_compile.py
Workaround for https://github.com/IronLanguages/ironpython3/issues/817
=> Fix import sre_compile

Src/IronPython/Modules/_ast.cs, Tests/test_ast.py
The following did not generate the proper AST:
```Python
ast.parse("[a for b in c for c in d]")
```
=> Fix comprehension ast

Src/IronPython.Modules/nt.cs, Src/IronPython/Modules/_io.cs, Src/IronPython/Runtime/ByteArray.cs, Src/IronPython/Runtime/Bytes.cs, Src/IronPython/Runtime/Operations/IntOps.cs, Src/IronPython/Runtime/Operations/StringOps.cs
- Add a dummy `os.get_terminal_size`
- Fix `BufferedReader.__new__`
- Add some `SequenceTypeInfo` annotations
- Update `int.from_bytes` to accept iterables
=> Misc changes

Src/IronPython.Modules/_thread.cs, Src/IronPython/Runtime/Converter.cs, Tests/interop/net/event/test_delegate.py, Tests/interop/net/method/test_returnvalue.py
See https://github.com/IronLanguages/ironpython2/issues/547
=> Prevent cast of float to int

Src/IronPython/Compiler/Ast/AstMethods.cs, Src/IronPython/Compiler/Ast/ClassDefinition.cs, Src/IronPython/Compiler/Ast/PythonNameBinder.cs, Src/IronPython/Compiler/Parser.cs, Src/IronPython/Modules/_ast.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Tests/test_clrtype.py, Tests/test_metaclass.py
Resolves https://github.com/IronLanguages/ironpython3/issues/272
=> Enable single line classes with metaclass

Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Tests/test_unpack.py
Also resolves https://github.com/IronLanguages/ironpython3/issues/841
=> Enable test_string

Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/StdLib/Lib/fractions.py, Src/StdLib/Lib/test/test_fractions.py
Bypasses the following issues:
- https://github.com/IronLanguages/ironpython3/issues/52
- https://github.com/IronLanguages/ironpython3/issues/844
=> Enable test_fractions

Src/IronPython/Runtime/Operations/MarshalOps.cs, Src/IronPython/Runtime/PythonDictionary.cs, Src/IronPython/Runtime/Set.cs, Src/IronPython/Runtime/SetStorage.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/Scripts/generate_set.py, Src/StdLib/Lib/test/test_set.py
Related issues:
- https://github.com/IronLanguages/ironpython3/issues/847
- https://github.com/IronLanguages/ironpython3/issues/848
=> Enable test_set

Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Tests/test_isinstance2.py
Related to https://github.com/IronLanguages/ironpython3/issues/854
=> Add type check to isinstance

Build/net46.props, Build/netcoreapp2.1.props, Build/netcoreapp3.1.props, Build/netstandard2.0.props, Documentation/feature-symbols.md, Src/IronPython.Modules/_codecs.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPython/Runtime/PythonAsciiEncoding.cs, Src/IronPython/Runtime/PythonContext.cs, Src/IronPython/Runtime/PythonEncoding.cs
[As discussed](https://github.com/IronLanguages/ironpython3/pull/765#discussion_r395986390).
=> Remove FEATURE_ENCODING

Src/IronPython.Modules/_codecs.cs, Src/IronPython/Runtime/IBufferProtocol.cs, Src/IronPython/Runtime/MemoryView.cs
Intended for constructors/initializers of `bytes`/`bytearray`, `memoryview` comparisons, and #846.
=> Implement enumeration of bytes for IPythonBuffer

Src/IronPython.Modules/_operator.cs, Src/IronPython.Modules/binascii.cs, Src/IronPython.Modules/hashlib/_hashlib.cs, Src/IronPython.Modules/hashlib/_md5.cs, Src/IronPython.Modules/hashlib/_sha1.cs, Src/IronPython.Modules/hashlib/_sha256.cs, Src/IronPython.Modules/hashlib/_sha512.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Tests/modules/misc/test__sha256.py, Tests/modules/misc/test__sha512.py
@BCSharp requested a review since this is adding `StringOps.TryEncodeAscii`
=> Enable test_hmac

Src/IronPython/Modules/_bytesio.cs, Src/IronPython/Modules/_fileio.cs, Src/IronPython/Modules/_io.cs, Src/IronPython/Runtime/IBufferProtocol.cs, Tests/modules/io_related/test__bytesio.py, Tests/modules/io_related/test__fileio.py
Includes https://github.com/IronLanguages/ironpython2/pull/712 and resolves https://github.com/IronLanguages/ironpython2/issues/713
=> Remove array usages

Src/IronPython/Lib/iptest/ipunittest.py, Src/IronPython/Runtime/Operations/InstanceOps.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPython/Runtime/Types/MappingProxy.cs, Tests/interop/net/derivation/test_ctor_override.py, Tests/test_bool.py, Tests/test_dict.py, Tests/test_exceptions_generated.py, Tests/test_function.py, Tests/test_generator.py, Tests/test_nonetype.py, Tests/test_specialcontext.py, Tests/test_str.py
Part of https://github.com/IronLanguages/ironpython3/issues/863
=> Get some tests passing with CPython

Src/IronPython/Compiler/Ast/PythonAst.cs, Tests/test_doc.py
Resolves https://github.com/IronLanguages/ironpython3/issues/887. Looks like a regression in https://github.com/IronLanguages/ironpython3/pull/599
=> Resolve intermittent failure in test_doc

Src/IronPython/Runtime/Operations/LongOps.cs, Src/StdLib/Lib/test/test_fractions.py, Tests/test_number.py
=> Calculate fraction of BigInteger division

Tests/test_regressions.py
=> Enable test importing cp20472.py from Python

Tests/modules/io_related/test_cPickle.py, Tests/modules/io_related/test_fd.py, Tests/modules/network_related/test__socket.py, Tests/modules/system_related/test_sys.py, Tests/modules/system_related/test_thread.py, Tests/test_class.py, Tests/test_cliclass.py, Tests/test_file.py, Tests/test_isinstance.py, Tests/test_iterator.py, Tests/test_namebinding.py, Tests/test_regressions.py, Tests/test_superconsole.py, make.ps1
Tests are split per framework, category.
They are executed in the powershell background job.
Parameter '-jobs' is used to define max concurrent jobs, whose default value is the number of cores.
=> Run test in parallel

Src/IronPython.Modules/zlib/zlib.net/Adler32.cs, Src/IronPython.Modules/zlib/zlib.net/Deflate.cs, Src/IronPython.Modules/zlib/zlib.net/InfBlocks.cs, Src/IronPython.Modules/zlib/zlib.net/InfCodes.cs, Src/IronPython.Modules/zlib/zlib.net/InfTree.cs, Src/IronPython.Modules/zlib/zlib.net/Inflate.cs, Src/IronPython.Modules/zlib/zlib.net/StaticTree.cs, Src/IronPython.Modules/zlib/zlib.net/Tree.cs, Src/IronPython.Modules/zlib/zlib.net/ZStream.cs, Src/IronPython.Modules/zlib/zlib.net/ZStreamException.cs, Src/IronPython.Modules/zlib/zlib.net/Zlib.cs, Src/IronPython.Modules/zlib/zlib.net/history.txt, Src/IronPython.Modules/zlib/zlib.net/license.txt, Src/IronPython.Modules/zlib/zlib.net/readme.txt
Equivalent to https://github.com/IronLanguages/ironpython2/pull/726
=> Move zlib from DLR

Src/IronPython/Modules/Builtin.cs, Src/IronPython/Runtime/Binding/ConversionBinder.cs, Src/IronPython/Runtime/Enumerate.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/Types/PythonType.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Tests/test_iterator.py
Add a `__reduce__` to the iterator type and make the enumerator type check
for changes to the `__next__` method of the iterator which it is
enumerating over.
=> Get test_iter passing

Src/IronPython/Compiler/GeneratorRewriter.cs, Src/IronPythonTest/IronPythonTest.csproj, Tests/test_json.py
Resolves https://github.com/IronLanguages/ironpython3/issues/926. Underlying issue is explained at https://github.com/IronLanguages/dlr/issues/231
=> Use MutableTuple.GetAccessPath with size

Tests/modules/network_related/test__ssl.py
Hopefully good for another 4 years.
=> Update Microsoft SSL certificate

Src/IronPython/Runtime/PythonEncoding.cs, Tests/modules/io_related/test_codecs.py
=> Fix BOM handling for custom error handlers

Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPython/Runtime/PythonContext.cs
See discussion in https://github.com/IronLanguages/ironpython3/pull/962
@BCSharp
=> Override DefaultLanguage

Src/IronPython.Modules/re.cs, Src/IronPython/Runtime/PythonContext.cs
Part of https://github.com/IronLanguages/ironpython3/issues/811
=> Add PythonContext.GetCopyRegModule

Src/IronPython.Modules/_multiprocessing.cs, Src/IronPython.Modules/pyexpat.cs
`_multiprocessing.send` => no data copy
`pyexpat.parse(str)` => eliminated one data copy on .NET Framework
`pyexpat.parse(byteslike)` => eliminated one data copy on .NET Core for input types other than `Bytes` or `byte[]`
=> Use IBufferProtocol in pyexpat and _multiprocessing

Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/StdLib/Lib/test/test_descrtut.py
Related issues:
https://github.com/IronLanguages/ironpython3/issues/995
https://github.com/IronLanguages/ironpython3/issues/996
=> Enable test_descrtut

Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/StdLib/Lib/test/support/__init__.py
Workaround for https://github.com/IronLanguages/ironpython3/issues/1005
=> Disable reap_threads on Mono

Src/IronPythonTest/MethodParametersStubs.cs, Tests/test_dlrkwarg.py
=> Support `IReadOnlyDictionary` with `ParamDictionaryAttribute`

Src/IronPython.Modules/binascii.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/StdLib/Lib/test/test_binascii.py, Src/StdLib/Lib/test/test_quopri.py, Tests/modules/io_related/test_binascii.py
Part of https://github.com/IronLanguages/ironpython3/issues/673. Related issues: https://github.com/IronLanguages/ironpython3/issues/1009
=> Implement binascii qp methods

Src/IronPython/Modules/_fileio.cs, Tests/modules/system_related/test_nt.py, Tests/test_io.py, Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/392
=> Don't buffer FileIO

Src/Scripts/generate_comdispatch.py
Matches  IronLanguages/dlr#248.
=> Update code generation script for COM dispatch in DLR

Src/IronPython/Hosting/PythonCommandLine.cs, Src/IronPythonConsole/IronPythonConsole.csproj, Src/IronPythonConsole/ipy-mono.sh, Src/IronPythonConsole/ipy.sh, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/IronPythonTest/Cases/CaseExecuter.cs, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Tests/modules/io_related/test_codecs.py, Tests/test_traceback.py
They were disabled due to https://github.com/IronLanguages/ironpython3/issues/541 which has since been resolved. Resolves https://github.com/IronLanguages/ironpython3/issues/937
=> Enable some tests on posix

Src/IronPython/Runtime/Binding/MetaPythonFunction.cs, Src/IronPython/Runtime/Binding/PythonInvokeBinder.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1015
=> Lookup keyword-only argname

Src/IronPython/Runtime/Types/PythonTypeInfo.cs, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Tests/test_protected.py
Brings in code that was added to ipy2 in https://github.com/IronLanguages/ironpython2/pull/1
=> Enable test_protected

Src/IronPython/Compiler/Parser.cs, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Tests/test_compiler.py, Tests/test_syntax.py
Related issues: https://github.com/IronLanguages/ironpython3/issues/1034
=> Enable test_syntax

Tests/modules/io_related/test__fileio.py
This depends on #983 to be effective.
=> Make test__fileio parallel-safe

Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Tests/test_exec.py
Brings in changes from https://github.com/IronLanguages/ironpython2/pull/291
=> Enable test_exec

Src/IronPython.SQLite/IronPython.SQLite.csproj, Src/IronPython.Wpf/IronPython.Wpf.csproj
Resolves https://github.com/IronLanguages/ironpython3/issues/1045 (hopefully).
=> Clean up WPF project

Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/StdLib/Lib/unittest/test/test_assertions.py
and update reasons of some test ignores.
=> Enable some tests

Src/IronPython/Runtime/Binding/PythonProtocol.Operations.cs, Src/IronPython/Runtime/DictionaryOps.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonList.cs, Src/IronPython/Runtime/PythonTuple.cs, Src/IronPython/Runtime/Slice.cs, Src/IronPython/Runtime/Types/PythonTypeInfo.cs, Src/StdLib/Lib/test/test_sort.py
Resolves https://github.com/IronLanguages/ironpython3/issues/664
=> Fix list/tuple/slice comparisons

Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/957
=> Add test for #957

Src/IronPython.Modules/_socket.cs, Src/IronPython.Modules/_weakref.cs, Src/IronPython.Modules/math.cs
Resolves https://github.com/IronLanguages/ironpython3/issues/1107
=> Add some CPython 3.5 functions

Src/IronPython.Modules/_posixsubprocess.cs, Src/IronPython.Modules/winsound.cs, Src/IronPython/Runtime/Reversed.cs
=> reversed release object

Src/IronPython.Modules/_csv.cs, Src/StdLib/Lib/test/test_csv.py
Also brings in some minor changes from CPython 3.5 (such as allowing writerow with non-sequence iterables).
=> _csv cleanup

Src/IronPython/Compiler/Ast/Comprehension.cs, Tests/test_closure.py
=> Use unique context param for ComprehensionScope

Src/IronPython/Runtime/Descriptors.cs, Tests/test_class.py, Tests/test_property.py
=> Make property.__doc__ writable

Src/IronPython/Compiler/Ast/ReturnStatement.cs, Src/IronPython/Compiler/GeneratorRewriter.cs, Src/IronPython/Runtime/Generator.cs, Tests/test_generator.py, Tests/test_pep380_stdlib.py
Resolves https://github.com/IronLanguages/ironpython3/issues/260
=> Fix StopIteration value

Src/IronPython.Modules/re.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Tests/modules/io_related/test_re.py, Tests/test_re_stdlib.py
by mapping to `RegexOptions.ECMAScript`. Far from perfect but works for basic cases.
=> Do simple re.ASCII matching

Src/IronPython/Compiler/Ast/Comprehension.cs, Src/IronPython/Compiler/Ast/PythonAst.cs, Src/IronPython/Compiler/Ast/PythonNameBinder.cs, Src/StdLib/Lib/pickle.py, Tests/test_dictcomp.py, Tests/test_listcomp.py, Tests/test_setcomp.py
=> Evaluate first comprehension iterator in outer scope

Src/IronPython.Modules/_datetime.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini
Resolves https://github.com/IronLanguages/ironpython3/issues/1133
=> Add datetime.timezone

Src/IronPython/Modules/sys.cs, Src/StdLib/Lib/test/test_sys.py
=> Replace sys.long_info with sys.int_info

Tests/test_namebinding.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1028
=> Restore pow in test_namebinding

Src/IronPython/Compiler/Ast/Comprehension.cs, Src/IronPython/Modules/_ast.cs, Tests/test_listcomp.py
Resolves #1132 and at the same time fixes #1082.
=> Properly bind references in comprehension scopes

Src/IronPython/Lib/iptest/__init__.py, Src/IronPython/Lib/iptest/type_util.py, Src/IronPython/Runtime/Operations/IntOps.cs, Tests/test_int.py
Fixes regression in https://github.com/IronLanguages/ironpython3/pull/991 and adds test.
=> Add test for int ctor

Src/IronPython/Modules/_ast.cs, Tests/test_ast.py
Resolves https://github.com/IronLanguages/ironpython3/issues/686
=> Revert ast.Starred

Src/IronPython/Runtime/StringFormatter.cs, Tests/test_formatting.py
```Python
assert "%x" % (-1 << 31) == '-80000000'
assert "% 9x" % (1 << 31) == ' 80000000'
```
=> Fix some % formatting issues

Src/IronPython/Compiler/Ast/Arg.cs, Src/IronPython/Compiler/Ast/CallExpression.cs, Src/IronPython/Compiler/Parser.cs
This removes some of the bugginess... 😸
=> Optimize IronPython.Compiler.Ast.Arg

Src/IronPython/Compiler/Ast/CallExpression.cs, Src/IronPython/Compiler/Ast/ClassDefinition.cs, Src/IronPython/Compiler/Ast/Expression.cs, Src/IronPython/Compiler/Ast/Keyword.cs
This should address the comments from https://github.com/IronLanguages/ironpython3/pull/1175#pullrequestreview-638355520.
The only think I haven't changed yet is the `EmptyArray` pending feedback from @BCSharp.
=> Update after review

Src/StdLib/Lib/sysconfig.py
Uses an implementation similar to that of PyPy. Resolves https://github.com/IronLanguages/ironpython3/issues/1185
=> Update paths in sysconfig

Src/StdLib/Lib/distutils/msvc9compiler.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1198
=> Patch msvc9compiler to not throw DistutilsPlatformError on import

Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonFunction.cs, Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1197
=> Fix tuple/list comparison

Src/IronPython/Modules/_io.cs, Src/IronPythonTest/EngineTest.cs
Resolves https://github.com/IronLanguages/ironpython3/issues/961
=> Use SharedIO.GetStreamProxy in PythonIOModule.CreateConsole

Src/IronPython.Modules/_collections.cs, Tests/test_deque.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1216
=> Fix issue with deque equality

Src/IronPython/Runtime/Operations/StringOps.cs, Tests/test_str.py
Resolves:
```py
class test(int):
def __str__(self):
return "success"
assert str(test()) == "success"
```
=> Add Extensible<int> str constructor

Src/IronPython/Compiler/Ast/PythonAst.cs, Src/IronPython/Compiler/Ast/PythonNameBinder.cs, Src/IronPython/Hosting/PythonCommandLine.cs, Tests/test_regressions.py, Tests/test_stdconsole.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1229
=> Set __package__ to None

Package/msi/IronPython.wxs
Resolves https://github.com/IronLanguages/ironpython3/issues/1187
=> Add Python registration to the win registry

Package/nuget/IronPython.nuspec
Resolves https://github.com/IronLanguages/ironpython3/issues/1227
=> Don't add net5.0 build to NuGet package

Src/IronPython/Runtime/Types/PythonType.cs, Tests/test_slots.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1235
=> Fix NRE when setting new attribute

Src/IronPython/Runtime/Types/PythonType.cs, Tests/test_slots.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1237
=> Resolve subclassing issue with slots

Src/IronPython.Modules/_overlapped.cs, Src/IronPython.Modules/_winapi.cs, Src/IronPython.Modules/nt.cs, Src/IronPython.Modules/time.cs, Src/IronPython/Compiler/Ast/YieldFromExpression.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/StdLib/Lib/asyncio/tasks.py, Src/StdLib/Lib/socket.py, Src/StdLib/Lib/test/test_asyncio/test_tasks.py, Tests/test_socket_stdlib.py
- Cleans up `_winapi`
- Adds a stub `_overlapped`
- Adds a dummy `time.get_clock_info`
=> Enable some asyncio tests

Src/IronPython/Runtime/Operations/PythonOps.cs, Tests/test_isinstance2.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1255
=> Fix issue with isinstance and tuple subtype

Src/IronPython/Runtime/ByteArray.cs, Src/IronPython/Runtime/Bytes.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/StringFormatter.cs
Adds a basic implementation of % formatting to bytes and bytearray (https://github.com/IronLanguages/ironpython3/issues/103)
=> Add % formatting to bytes and bytearray

Src/IronPython/Runtime/Types/PythonType.cs, Src/IronPython/Runtime/Types/PythonTypeDictSlot.cs, Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1271
=> Fix overwriting descriptor on class

Src/IronPython/Compiler/Ast/ScopeStatement.cs, Tests/test_closure.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1275
=> Properly access closure tuple

Src/IronPython.Modules/pyexpat.cs, Tests/test_sax_stdlib.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1279
Related issues: https://github.com/IronLanguages/ironpython2/issues/537
=> Unblock xml.sax.parse

Directory.Build.props, Package/nuget/IronPython.nuspec, Package/zip/Zip.Packaging.targets, Src/IronPython.Modules/IronPython.Modules.csproj, Src/IronPython.SQLite/IronPython.SQLite.csproj, Src/IronPython.Wpf/DynamicXamlReader.cs, Src/IronPython.Wpf/_wpf.cs, Src/IronPython/IronPython.csproj, Src/IronPython/Lib/iptest/test_env.py, Src/IronPython/Modules/sys.cs, Src/IronPython/Runtime/ClrModule.cs, Src/IronPython/Runtime/ExtensionMethodSet.cs, Src/IronPythonConsole/IronPythonConsole.csproj, Src/IronPythonTest/IronPythonTest.csproj, Tests/test_methodbinder1.py, Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1287
=> Remove .NET Core 2.1

Src/IronPython/Hosting/PythonOptionsParser.cs, Src/IronPythonConsole/Console.cs, Src/StdLib/Lib/venv/__init__.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1074, https://github.com/IronLanguages/ironpython3/issues/1075 and https://github.com/IronLanguages/ironpython3/issues/1194.
=> Improved command line options handling

Src/IronPythonCompiler/Config.cs, Src/IronPythonCompiler/ConsoleOps.cs, Src/IronPythonCompiler/Program.cs, Src/IronPythonCompiler/README.md
Resolves https://github.com/IronLanguages/ironpython3/issues/1310
=> Add /sta option to ipyc

Src/IronPython/Runtime/Operations/ArrayOps.cs, Tests/test_array.py
=> Apply customary type conversions when assigning values to ndim Array

Src/IronPython/Runtime/Operations/ArrayOps.cs, Tests/test_array.py
=> Align CLI array access errors with memoryview

Src/IronPython/Runtime/CustomDictionaryStorage.cs, Src/IronPython/Runtime/ModuleDictionaryStorage.cs, Src/IronPython/Runtime/PythonDictionary.cs, Src/IronPython/Runtime/PythonModule.cs, Tests/test_builtin_stdlib.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1309
=> Improve perf while iterating over globals

Src/IronPython.Modules/IterTools.cs, Src/IronPython.Modules/_collections.cs, Src/IronPython.Modules/_opcode.cs, Src/IronPython.Modules/_socket.cs, Src/IronPython.Modules/_struct.cs, Src/IronPython.Modules/_warnings.cs, Src/IronPython.Modules/math.cs, Src/IronPython/Modules/Builtin.cs, Src/IronPython/Modules/_bytesio.cs, Src/IronPython/Modules/_io.cs, Src/IronPython/Runtime/Binding/MetaUserObject.cs, Src/IronPython/Runtime/ByteArray.cs, Src/IronPython/Runtime/Bytes.cs, Src/IronPython/Runtime/Converter.cs, Src/IronPython/Runtime/Operations/ByteOps.cs, Src/IronPython/Runtime/Operations/IntOps.cs, Src/IronPython/Runtime/Operations/LongOps.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPython/Runtime/Types/PythonType.cs, Src/IronPython/Runtime/Types/PythonTypeInfo.cs, Tests/modules/misc/test__opcode.py, Tests/test_bytes.py, Tests/test_deque.py
Follow-up on #1329 (issue #52).
=> Eliminate Extensible<int>

Src/IronPython/Hosting/PythonOptionsParser.cs, Tests/test_stdconsole.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1337
=> Fix -Wargument parsing

Src/IronPython/Runtime/ByteArray.cs, Src/IronPython/Runtime/Bytes.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini
It's been on my todo list for too long. Resolves #1327.
=> BytesWarning on bytes/str comparison

Src/IronPython/Runtime/Operations/BigIntegerOps.cs, Src/IronPython/Runtime/Operations/IntOps.Generated.cs, Src/IronPython/Runtime/Operations/IntOps.cs, Src/Scripts/generate_alltypes.py, Tests/test_isinstance.py
=> Cleanup of constructors in BigIntegerOps/IntOps

Src/IronPython/Runtime/ClrModule.cs, Tests/test_cliclass.py
=> Fix serialization of non-int-based enum instances

Src/IronPython/Runtime/Operations/BigIntegerOps.cs, Src/IronPython/Runtime/Operations/PythonOps.cs
Follow-up on https://github.com/IronLanguages/ironpython3/pull/1347.
=> Enable nullable annotations in BigIntegerOps

Src/IronPython/Runtime/ClrModule.cs, Tests/test_cliclass.py
=> Improve clr.Serialize

Src/IronPython/Runtime/Operations/IntOps.Generated.cs, Src/IronPython/Runtime/Operations/IntOps.cs, Src/Scripts/generate_alltypes.py
=> Implement __int__ across all integer types

Src/StdLib/Lib/importlib/_bootstrap.py
Removes some loaders (for pyc, pyd, pyw) from `meta_path` which don't do anything on IronPython.
=> Remove unsupported code from _bootstrap

Src/IronPython.Modules/_ctypes/CData.cs, Src/IronPython.Modules/_ctypes/MemoryHolder.cs
=> Implement Dispose for CData

Src/IronPython/Runtime/Types/PythonTypeInfo.cs, Src/IronPythonTest/InheritTest.cs, Tests/test_inheritance.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1375
=> Filter undefined property getters/setters

Src/IronPython/Hosting/PythonCommandLine.cs, Src/IronPython/Hosting/PythonOptionsParser.cs, Src/IronPython/Runtime/PythonContext.cs, Src/IronPython/Runtime/PythonOptions.cs
Part of https://github.com/IronLanguages/ironpython3/issues/1425
=> Set isolated flag when run with -I

Src/IronPython/Runtime/PythonEncoding.cs
I'm cleaning out my stash of old unfinished work of low importance that should not interfere with changes on 3.6.
=> Use MemberNotNullAttribute in PythonEncoding

Src/IronPython.Modules/_ctypes/_ctypes.cs, Src/IronPython.Modules/nt.cs, Tests/modules/type_related/test_ctypes.py
Follow-up on #1467. As it turns out, I had some time.
=> Consolidate winerror message handling in modules _ctypes and nt

.github/workflows/main.yml, Build/net462.props, IronPython.sln, Package/choco/IronPython.nuspec, Package/deb/Deb.Packaging.targets, Package/msi/IronPython.Installer.wixproj, Package/msi/IronPython.wxs, Package/nuget/IronPython.nuspec, Package/nuget/NuGet.Packaging.csproj, Package/pkg/Pkg.Packaging.targets, Src/IronPython.Modules/IronPython.Modules.csproj, Src/IronPython.SQLite/IronPython.SQLite.csproj, Src/IronPython.Wpf/IronPython.Wpf.csproj, Src/IronPython/IronPython.csproj, Src/IronPython/Runtime/Types/PythonType.cs, Src/IronPython/Runtime/Types/PythonTypeInfo.cs, Src/IronPythonCompiler/IronPythonCompiler.csproj, Src/IronPythonConsole/IronPythonConsole.csproj, Src/IronPythonConsole32/IronPythonConsole32.csproj, Src/IronPythonTest/IronPythonTest.csproj, Src/IronPythonWindow/IronPythonWindow.csproj, Src/IronPythonWindow32/IronPythonWindow32.csproj, make.ps1
Resolves https://github.com/IronLanguages/ironpython3/issues/1481
=> Bump up to .NET Framework 4.6.2

Src/IronPython/Modules/unicodedata.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPython/Runtime/StringFormatter.cs, Tests/test_regressions.py, Tests/test_unicode_stdlib.py
See https://github.com/IronLanguages/ironpython3/pull/1447 and https://github.com/IronLanguages/ironpython3/pull/1469
=> Fixes from 3.6

Src/IronPython.Modules/_functools.cs, Tests/modules/system_related/test_resource_stdlib.py, Tests/test_functools_stdlib.py
Follow-up to https://github.com/IronLanguages/ironpython3/pull/1507
=> Fix StackOverflow in test_functools

Src/IronPython.Modules/re.cs, Tests/modules/io_related/test_re.py
Resolves https://github.com/IronLanguages/ironpython2/issues/821
=> Don't include unnamed groups in groupdict

Src/IronPython/Modules/_io.cs, Src/IronPython/Modules/_locale.cs, Tests/modules/system_related/test__locale.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1527
=> Use default encoding as preferred encoding

Src/IronPython/Runtime/Bytes.cs, Tests/test_iterator.py
Workaround for https://github.com/IronLanguages/ironpython3/issues/1519
=> Get pip working again

Src/IronPython.Modules/_codecs.cs, Src/IronPython.Modules/grp.cs, Src/IronPython/Runtime/Operations/StringOps.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/StdLib/Lib/test/test_global.py
Updates test_global to match CPython 3.8 which correctly reports the offset. Also resolves https://github.com/IronLanguages/ironpython3/issues/1451
=> Re-enable some tests

Src/IronPython/Runtime/StringFormatter.cs
Updates the DLR and fixes a formatting issue with .NET 7.
=> Fix formatting issue

Src/IronPython/Runtime/CustomDictionaryStorage.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/RuntimeVariablesDictionaryStorage.cs
=> Support arbitrary PythonStorage as backing for RuntimeVariablesDictionaryStorage

Src/IronPython/Runtime/Operations/FloatOps.cs, Src/IronPython/Runtime/StringFormatter.cs, Tests/test_formatting.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1549
=> Add missing decimal point

Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/StdLib/Lib/heapq.py
Workaround for https://github.com/IronLanguages/ironpython3/issues/547
=> Re-enable test_heapq

Src/IronPython.Modules/_thread.cs, Src/IronPython/Compiler/Ast/ClassDefinition.cs, Src/IronPython/Compiler/Ast/ScopeStatement.cs, Src/IronPython/Runtime/CommonDictionaryStorage.cs, Src/IronPython/Runtime/ConstantDictionaryStorage.cs, Src/IronPython/Runtime/CustomDictionaryStorage.cs, Src/IronPython/Runtime/DebuggerDictionaryStorage.cs, Src/IronPython/Runtime/DictionaryStorage.cs, Src/IronPython/Runtime/EmptyDictionaryStorage.cs, Src/IronPython/Runtime/ObjectAttributesAdapter.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonDictionary.cs, Src/IronPython/Runtime/ScopeDictionaryStorage.cs, Src/IronPython/Runtime/StringDictionaryStorage.cs, Src/IronPython/Runtime/WrapperDictionary.cs, Src/IronPythonTest/StringDictionaryStorage.cs, Tests/modules/system_related/test_sys_getframe.py, Tests/test_class.py, Tests/test_metaclass.py, WhatsNewInPython30.md
Part of #20 and resolves #1154.
Keeping up with the venerable tradition of convoluted code handling `PythonStorage` for the sake of performance. 😄
=> Complete implementation of __prepare__ 

Src/IronPython/Compiler/Ast/ClassDefinition.cs, Tests/test_namebinding.py
Handles the `global` part from #1560, making IronPython's behaviour consistent with CPython. Changes to `HasLateBoundVariableSets` are just for consistency; this property is not used when binding names in a class definition.
I intend to handle the `local` part in a separate PR (assuming no other tests fail), for clarity and to allow an easy revert in case it's needed.
`test_namebinding.py` fails when run with `ipy` from the command line, but passes when run with `make test`. This is an unrelated issue, likely #1028, although it is now closed. The issue has all the symptoms of a bug in the expression rewriting code, so that would be my guess.
=> Resolve explicit globals in class lexically

Src/IronPython/IronPython.csproj, Src/IronPythonCompiler/Program.cs
Resolves https://github.com/IronLanguages/ironpython3/issues/1562
=> Embed missing assemblies with ipyc

Package/dotnettool/IronPython.Console.csproj, Package/nuget/IronPython.StdLib.nuspec, Package/nuget/IronPython.nuspec, Package/nuget/README.md
=> Update nuspec metadata

Package/zip/Zip.Packaging.targets, Src/IronPythonCompiler/App.config, Src/IronPythonConsole/ipy.bat
Resolves https://github.com/IronLanguages/ironpython3/issues/1584
=> Exclude netstandard2.0 from zip package

Src/IronPython/Runtime/PythonContext.cs
Resolves https://github.com/IronLanguages/ironpython3/issues/1596
=> Prevent occasional deadlock

Src/IronPython/Modules/_fileio.cs, Src/StdLib/Lib/importlib/_bootstrap.py, Src/StdLib/Lib/importlib/_bootstrap_external.py, Tests/test_ordered_dict_stdlib.py
Similar to https://github.com/IronLanguages/ironpython3/pull/1391 and https://github.com/IronLanguages/ironpython3/pull/1594
=> Bootstrap changes from 3.4

Src/IronPython/Runtime/Binding/PythonBinder.cs, Src/IronPython/Runtime/Operations/IntPtrOps.cs, Src/IronPython/Runtime/Operations/UIntPtrOps.cs, Tests/test_regressions.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1649
=> Add some extension types for IntPtr/UIntPtr

Src/IronPython.Modules/re.cs, Tests/modules/io_related/test_re.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1654
=> Fix IndexError on empty group

Src/IronPython/Runtime/Types/PythonType.cs, Tests/test_metaclass.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1661
=> Call __setattr__ on metaclass

Src/IronPython.Modules/nt.cs, Src/IronPython/Hosting/PythonCommandLine.cs, Src/IronPython/Hosting/PythonOptionsParser.cs, Src/IronPython/Modules/_io.cs, Src/IronPython/Modules/sys.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonContext.cs, Src/IronPython/Runtime/PythonOptions.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Src/StdLib/Lib/_bootlocale.py, Src/StdLib/Lib/locale.py, Src/StdLib/Lib/test/test_builtin.py, Src/StdLib/Lib/test/test_sys.py, Src/StdLib/Lib/test/test_utf8_mode.py, Tests/test_python26.py, Tests/test_utf8_mode_stdlib.py
Part of https://github.com/IronLanguages/ironpython3/issues/1695.
- Does not handle the PYTHONUTF8 environment variable
- May require additional changes related to https://github.com/IronLanguages/ironpython3/issues/1156
- Automatically activation based on POSIX locale
=> utf-8 mode

Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Src/StdLib/Lib/test/mod_generics_cache.py, Src/StdLib/Lib/test/test_typing.py, Src/StdLib/Lib/typing.py, Tests/test_typing_stdlib.py
Resolves https://github.com/IronLanguages/ironpython3/issues/1676
=> Add typing backport

Src/IronPython.Modules/_datetime.cs, Src/IronPython.Modules/time.cs, Tests/test_datetime_stdlib.py
Also resolves https://github.com/IronLanguages/ironpython3/issues/1136
=> Add nullable annotations to time and _datetime

Src/IronPython/Runtime/Binding/PythonGetMemberBinder.cs
Use Linq for faster Getter accessors
=> Use Linq to compile getters

Src/IronPython.Modules/mmap.cs, Src/IronPython.Modules/msvcrt.cs, Src/IronPython.Modules/nt.cs, Src/IronPython/Modules/_fileio.cs, Src/IronPython/Runtime/PythonContext.cs, Src/IronPython/Runtime/PythonFileManager.cs, Tests/modules/io_related/test_fd.py, Tests/test_file.py
Something that has caught my attention while reading the code trying to understand how `PythonFileManager` works.
=> Fix file descriptor leak in FileManager

Build/net462.props, Build/net6.0.props, Build/netcoreapp2.1.props, Build/netcoreapp3.1.props, Build/netstandard2.0.props, Documentation/feature-symbols.md, Src/IronPython.Modules/bz2/dotnetzip/BZip2/BZip2OutputStream.cs, Src/IronPython.Modules/bz2/dotnetzip/BZip2/ParallelBZip2OutputStream.cs, Src/IronPython/Hosting/PythonCommandLine.cs, Src/IronPython/Hosting/PythonConsoleOptions.cs, Src/IronPython/Hosting/PythonOptionsParser.cs, Src/IronPython/Runtime/Operations/PythonOps.cs, Src/IronPython/Runtime/PythonContext.cs, Src/IronPython/Runtime/Types/DocBuilder.cs
Follow up on IronLanguages/dlr#272.
=> Remove FEATURE_BASIC_CONSOLE and FEATURE_FULL_CONSOLE

Src/IronPython/Runtime/Binding/PythonGetMemberBinder.cs
Fallback to (old) reflection method for getter accessors when NotImplementedException is thrown (on Mono). The regression was caused by the changes done in https://github.com/IronLanguages/ironpython3/pull/1706. Resolves https://github.com/IronLanguages/ironpython3/issues/1728
=> catch System.NotImplementedException: byref delegate

Src/IronPython/Runtime/Operations/ObjectOps.cs, Src/IronPythonTest/Cases/CPythonCasesManifest.ini, Src/IronPythonTest/Cases/IronPythonCasesManifest.ini, Tests/test_descr_stdlib.py
Related to https://github.com/IronLanguages/ironpython3/issues/1722. Also resolves https://github.com/IronLanguages/ironpython3/issues/1259.
=> Enable some test_descr tests

Src/IronPython/Runtime/PythonFileManager.cs
=> Use ArrayPool for buffered reading in StreamBox

Src/IronPython.Modules/time.cs, Tests/test_time_stdlib.py, WhatsNewInPython33.md
Resolves https://github.com/IronLanguages/ironpython3/issues/7
=> Add clocks

Src/IronPython/Runtime/Operations/StringOps.cs
=> Fix debug check of codecs names

Src/IronPython.Modules/_ssl.cs
Resolves https://github.com/IronLanguages/ironpython3/issues/1769
=> Don't call Read multiple times in _SSLSocket.read

Src/StdLib/Lib/pathlib.py
Makes the 3.4 branch more compatible with "modern" code. Resolves https://github.com/IronLanguages/ironpython3/issues/1773
=> Add __fspath__ to pathlib
